### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by PonyOny** [jneilliii/OctoPrint-Tasmota#1]
I would like to know if this plugin is currently operational, i have been looking at the code and where you send the request to "tasmota" you are using "ip + /plugin/tasmota" + payload parameters, and i have been looking at the tasmota and only see MQTT integration and HTTP request and they look like this

```
http://sonoff/cm?cmnd=Power%20TOGGLE
http://sonoff/cm?cmnd=Power%20On
http://sonoff/cm?cmnd=Power%20off
http://sonoff/cm?user=admin&password=joker&cmnd=Power%20Toggle
```
[Tasmota Commands](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#web)

do i have to use any custom tasmota firmware or something?

Thanks.

**Comment by jneilliii** [comment]
To the best of my knowledge this plugin is fully functional, at least with the flashed sonoff S20 plug I have. In theory it should work with any tasmota device, but that's the only one I have.  I think you're looking at the part of the code where the commands are sent back from the web client to the python backend, which is where the commands are sent to the tasmota device.  An example command is being sent at line [89](https://github.com/jneilliii/OctoPrint-Tasmota/blob/master/octoprint_tasmota/__init__.py#L89).

**Comment by PonyOny** [comment]
Sorry for that, you are right it's working... my mistake, thanks.
