### ISSUE TITLE
Unable to switch on my light

### ISSUE THREAD

**Issue by dushyantahuja** [jneilliii/OctoPrint-Tasmota#10]
Hi - first of all thanks for creating this plugin. It is exactly what I needed. I have a Sonoff Basic flashed with the latest tasmota firmware. It connects to my network and I'm able to switch it on / off using the web interface at IP address 192.168.1.225.
However, whenever I try to use the plugin, I get the following error:
<img width="328" alt="screen shot 2017-12-30 at 09 51 24" src="https://user-images.githubusercontent.com/6416649/34453271-94778a6e-ed47-11e7-985a-635daa2b9584.png">

Not sure what to do. Thanks for you help.

**Comment by jneilliii** [comment]
I notice you have a username/password entered. Unless you changed the firmware the username should be admin and the password is what you habe configured for the web interface password, not mqtt.

**Comment by dushyantahuja** [comment]
Yes - am using the web interface password. I manually tried the following line replacing the values

http://" + plugip + "/cm?user=" + username + "&password=" + password + "&cmnd=Power" + str(plugidx) + "%20on

http://192.168.1.225/cm?user=admin&password=1234&cmnd=Power1%20on

and get the following response:
{"POWER":"ON"}

So, not really sure what's happening here. Have tried to uninstall and reinstall - to no avail.

**Comment by jneilliii** [comment]
Can you re-post the most recent log file again so I can see the communication back and forth please?

**Comment by jneilliii** [comment]
Also, is it possible your octoprint server is unable to communicate with the plug, but your machine can?  I had another person mention a similar issue to this with the TP-Link-Smartplug plugin I developed and it ended up being network related.

**Comment by dushyantahuja** [comment]
I tried to access the switch from the raspberry pi using curl 'http://192.168.1.225/cm?user=admin&password=1234&cmnd=Power1%20on' and received {"POWER":"ON"} as the response. The switch also turned on. 
Attached is the latest log:

[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1598407/plugin_tasmota_debug.log)

**Comment by jneilliii** [comment]
Try this, change the index to be blank.

**Comment by dushyantahuja** [comment]
Same error. Updated log attached. 
[plugin_tasmota_debug (1).log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1598987/plugin_tasmota_debug.1.log)

**Comment by dushyantahuja** [comment]
Created a fork to hard code the commands:
https://github.com/dushyantahuja/OctoPrint-Tasmota

Here are the changes:
https://github.com/dushyantahuja/OctoPrint-Tasmota/commit/eed47c745c97541ef3ce0dea911ba8650ac9dc52#diff-d65fe7ffeb0d8e45cc309a4f9c905de8

However still get the same error. Really not sure what's going wrong here. See updated log. 
[plugin_tasmota_debug (2).log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1599002/plugin_tasmota_debug.2.log)

**Comment by lnx13** [comment]
I have the same error message on octoprint, but plugin debug log little bit different:

```
[2018-01-04 00:16:46,119] DEBUG: Checking status of 192.168.88.14 index 1.
[2018-01-04 00:16:50,478] DEBUG: 192.168.88.14 index 1 response: RESULT = {"POWER1":"ON"}
POWER1 = ON
[2018-01-04 00:16:50,479] ERROR: Invalid ip or unknown error connecting to 192.168.88.14.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 135, in check_status
    chk = response["POWER"]
KeyError: 'POWER'
[2018-01-04 00:16:50,480] DEBUG: 192.168.88.14 index 1 is UNKNOWN
[2018-01-04 00:16:50,481] DEBUG: unknown error with 192.168.88.14.
```

Sonoff Dual Module Program Version  5.10.0
Octoprint version 1.3.6

**Comment by jneilliii** [comment]
In your case @Inx13 I see the bug and will work on the issue when I can, probably tomorrow.

**Comment by dushyantahuja** [comment]
Thanks for all your help. I've moved to your MQTT plugin - that works perfectly. Thanks a lot.

**Comment by jneilliii** [comment]
@lnx13 The changes were already done in my dev branch, so I just released a new version with those changes incorporated.  This should resolve your issue, please report back.

**Comment by lnx13** [comment]
@jneilliii thanks, all works well!

**Comment by Quintin9801** [comment]
confused as to what I need to put in as values for the switch, maybe I'm just a noob but I've been trying forever. Do I need to use MQTT? I'm hitting the sonoff through octoprint and it shows up in the console for Tasmota but it only switches it on, not off. Id like to use web commands because I don't know how to set up an MQTT Broker either.

**Comment by jneilliii** [comment]
I think you are probably running into the issue because of the index value.  Set that to be blank and it should work, it's resolved the problem for others in #13

**Comment by Quintin9801** [comment]
Switching the index didn't seem to work but I have my logs if you could help me.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1617547/plugin_tasmota_debug.log)
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1617548/octoprint.log)

**Comment by jneilliii** [comment]
Try this for me @Quintin9801.  Delete the plugin_tasmora_debug.log file, and then add a new plug with the following settings. Once added save the settings and restart octoprint and then send me the new log file it creates that you deleted earlier.  Nowhere in your log file that you sent did I see a clean ip address and a blank index value.

ip: 10.0.0.10
index: (leave blank)

**Comment by Quintin9801** [comment]
I tied and here’s the new log file after deleting the old one, adding the new plug, and restarting octoprint. I should note that I am using an Ethernet cable to my pi and I will try without it but I don’t see how it would harm the communication of an ip from the same router

[2018-01-10 05:59:03,006] DEBUG: {u'username': u'admin', u'ip': u'10.0.0.10', u'password': u'12345678', u'command': u'checkStatus', u'idx': u''} [2018-01-10 05:59:03,007] DEBUG: Using authentication for 10.0.0.10. [2018-01-10 05:59:03,007] DEBUG: Checking status of 10.0.0.10 index . [2018-01-10 05:59:03,103] DEBUG: 10.0.0.10 index response: {"POWER":"OFF"} [2018-01-10 05:59:03,104] ERROR: Invalid ip or unknown error connecting to 10.0.0.10. Traceback (most recent call last): File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 134, in check_status response = json.loads(webresponse.split()[2]) IndexError: list index out of range [2018-01-10 05:59:03,105] DEBUG: 10.0.0.10 index is UNKNOWN [2018-01-10 05:59:03,106] DEBUG: unknown error with 10.0.0.10. [2018-01-10 05:59:14,977] DEBUG: {u'username': u'admin', u'ip': u'10.0.0.10', u'password': u'12345678', u'command': u'checkStatus', u'idx': u''} [2018-01-10 05:59:14,978] DEBUG: Using authentication for 10.0.0.10. [2018-01-10 05:59:14,979] DEBUG: Checking status of 10.0.0.10 index . [2018-01-10 05:59:15,084] DEBUG: 10.0.0.10 index response: {"POWER":"OFF"} [2018-01-10 05:59:15,085] ERROR: Invalid ip or unknown error connecting to 10.0.0.10. Traceback (most recent call last): File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 134, in check_status response = json.loads(webresponse.split()[2]) IndexError: list index out of range [2018-01-10 05:59:15,086] DEBUG: 10.0.0.10 index is UNKNOWN [2018-01-10 05:59:15,086] DEBUG: unknown error with 10.0.0.10.

**Comment by rewegit** [comment]
Same problem at me. 
- SONOFF S20
- no pw set
- testet with Index 1 and empty Index

My log:
[2018-01-10 17:55:09,869] DEBUG: {u'username': u'admin', u'ip': u'192.168.99.124', u'password': u'', u'command': u'checkStatus', u'idx': u''}
[2018-01-10 17:55:09,870] DEBUG: Using authentication for 192.168.99.124.
[2018-01-10 17:55:09,871] DEBUG: Checking status of 192.168.99.124 index .
[2018-01-10 17:55:10,003] DEBUG: 192.168.99.124 index  response: {"POWER":"ON"}
[2018-01-10 17:55:10,004] ERROR: Invalid ip or unknown error connecting to 192.168.99.124.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 134, in check_status
    response = json.loads(webresponse.split()[2])
IndexError: list index out of range
[2018-01-10 17:55:10,005] DEBUG: 192.168.99.124 index  is UNKNOWN
[2018-01-10 17:55:10,006] DEBUG: unknown error with 192.168.99.124.

**Comment by jneilliii** [comment]
Just curious, what tasmota version are you guys running @rewegit and @Quintin9801? I wonder if there is a difference between your version and the one I have installed on mine, which is 5.8.0?

I think tasmota software may have changed the reponse in newer versions, but haven't really had a chance to look into it yet, but based on your line

> [2018-01-10 17:55:10,003] DEBUG: 192.168.99.124 index response: {"POWER":"ON"}

I think that is the issue.  When I run it on my OctoPrint I get this as a response.

> [2018-01-10 22:22:22,971] DEBUG: 192.168.1.144 index  response: RESULT = {"POWER":"OFF"}
> POWER = OFF

What do you guys get if you go to the following url?

http://<ip>/cm?user=admin&password=&cmnd=Power

I get this:

> RESULT = {"POWER":"OFF"}
> POWER = OFF

**Comment by jneilliii** [comment]
You guys don't even need to check, I just upgraded my tasmota software to the latest 5.11.1 and can see that is definitely the issue.  I will work on getting this fixed for you guys tomorrow.

**Comment by rewegit** [comment]
Thank you for your effort

**Comment by Quintin9801** [comment]
Greatly appreciated and impressed with your speed and work ethic, then you so much @jneilliii

**Comment by jneilliii** [comment]
The change was actually easier than expected.  I just release a new version that should work for you guys now.  Unfortunately, it will break older tasmota firmware, so I put a note for minimum firmware version.

**Comment by Quintin9801** [comment]
Currently, I'm in the middle of a print and cannot install the new version yet but I'm soooo excited to see it work, thank you again for all of your speedy work!

**Comment by elcattivo** [comment]
Thanks for the fix. It resolved the issue for me.

**Comment by jneilliii** [comment]
I'm gong to assume this issue is fixed now.

**Comment by TheDiNi74** [comment]
Something i found..

The Tasmota plugin, doesn't get the reply from tasmota switch:
like:
{"POWER":"OFF"}
{"POWER":"ON"}

I have turned off in all my tasmota Switches:
Web-Log Level
to level 0

So there's no reply for web...
Now i turned to Level 1 (INFO) all works fine..
;)

No Script error. Configuration Error at sonoff tasmota switch by User (me)

If Using Sonoff RF, check 1 Relay in plugin Config or leave Index empty.
I don't set 1 Relay, because using also sonoff 4chpro with index 1-4 at samt time.

Sorry.. for fast german englisch...

Tested sonoff rf & sonoff 4chpro


may be nice the Status of Switches may be polled some time,
if somone using parallel rf 433mhz remotes :-D

__________________________________________________________________________________________________
Was habe ich herausgefunden...
Das Tasmota plugin, bekommt nicht die erwartete Antwort vom Tasmota Schalter, wie z.B.:
{"POWER":"OFF"}
{"POWER":"ON"}

Ich habe aus gewohnheit, direkt immer überall auf den Tasmota Schaltern
das Logging fürs Web ausgechaltet...

Einstellungen->Logging konfigurieren->Web-Log Level
Level 0 = keine
Somit gibt es dann im Web auch keinerlei Rückmeldungen....

Nachdem ich dieses nun auf den Level 1 (INFO) umgestellt habe, funktioniert alles wie
erwartet.
Der Fehler lag nicht beim Script sondern beim User der das Einstellte (ich)... ;-D


Bei dem Sonoff RF, entweder den haken: 1 Relay in der Plugin Config setzen oder das Index Feld leer lassen.
Ich habe den haken bei 1 Relay weg gelassen, damit ich parallel ebenfalls einen SONOFF 4CH PRO steuern kann mit Index 1-4


Tested sonoff rf & sonoff 4chpro



Meine Sonoff Daten
Version:
___________________________________
Tasmota Version
6.6.0(release-sonoff) 
Build-Datum & -Uhrzeit
2019.07.06 13:17:19 
Core-/SDK-Version
2_3_0/1.5.3(aec24ac9) 
___________________________________

Meine Plugin Daten
Tasmota (0.8.5)        
Simple plugin to control sonoff devices that have been flashed with Tasmota.
