### ISSUE TITLE
 Tasmota Error Status unknown using an index, no error in blank

### ISSUE THREAD

**Issue by legeantbleu** [jneilliii/OctoPrint-Tasmota#101]
Hello 

Thanks for your plugin that I've been using for a long time, I just restarted an octopi and problem... 

When I configure the tasmota with an index "1" I'm unable to use it (I get the error " " ), without index it works via the octoprint interface but it's impossible to use the M81 command in the end gcode, it's not taken into account. 

My tasmota sonoff is up to date (5.12.0), I tried changing the IP of the sonoff, changing the password. I also reinstalled the tasmota plugin.

A bug ? 

Thanks for your help :)

Translated with www.DeepL.com/Translator (free version)

**Comment by jneilliii** [comment]
This is probably related to the SetOption26 of the Tasmota. When you press the test button in the Tasmota editor it should give an option to set that variable to on and then the index will work.

**Comment by trevor229** [comment]
I have the same issue. SetOption26 is enabled and I am running Tasmota 9.2.0 on a Gosund WP3 plug and I get the error
```
ERROR: Invalid ip or unknown error connecting to <IP HERE>.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 448, in check_status
    response = webresponse.json()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 458 (char 457)
[2020-12-30 01:54:47,809] DEBUG: <IP HERE> index 1 is UNKNOWN
[2020-12-30 01:54:47,810] DEBUG: unknown error with <IP HERE>

**Comment by jneilliii** [comment]
This is with gcode commands @trevor229? The plugin works otherwise?

**Comment by trevor229** [comment]
No, this is just using the button provided in the nav bar in the main page. No gcode involved.

**Comment by jneilliii** [comment]
almost sounds like a network routing issue or a bad response from the plug. If you go to the below ip from your laptop/pc what is returned?

```
http://<IP HERE>/cm?cmnd=Status%200
```

**Comment by trevor229** [comment]
Here is the output.
```
{
    "Status": {
        "Module": 0,
        "DeviceName": "3D Printer",
        "FriendlyName": ["3D Printer"],
        "Topic": "tasmota",
        "ButtonTopic": "0",
        "Power": 0,
        "PowerOnState": 3,
        "LedState": 1,
        "LedMask": "FFFF",
        "SaveData": 1,
        "SaveState": 1,
        "SwitchTopic": "0",
        "SwitchMode": [0, 0, 0, 0, 0, 0, 0, 0],
        "ButtonRetain": 0,
        "SwitchRetain": 0,
        "SensorRetain": 0,
        "PowerRetain": 0
    },
    "StatusPRM": {
        "Baudrate": 115200,
        "SerialConfig": "8N1",
        "GroupTopic": "tasmotas",
        "OtaUrl": "http://ota.tasmota.com/tasmota/release-7.2.0/tasmota.bin	",
        "RestartReason": "Power On",
        "Uptime": "0T05:56:24",
        "StartupUTC": "2020-12-30T18:14:57",
        "Sleep": 50,
        "CfgHolder": 4617,
        "BootCount": 12,
        "BCResetTime": "2020-12-30T02:34:22",
        "SaveCount": 45,
        "SaveAddress": "FA000"
    },
    "StatusFWR": {
        "Version": "9.2.0(tasmota)",
        "BuildDateTime": "2020-12-21T15:03:40",
        "Boot": 31,
        "Core": "2_7_4_9",
        "SDK": "2.2.2-dev(38a443e)",
        "CpuFrequency": 80,
        "Hardware": "ESP8285",
        "CR": "373/699"
    },
    "StatusLOG": {
        "SerialLog": 2,
        "WebLog": 2,
        "MqttLog": 0,
        "SysLog": 0,
        "LogHost": "",
        "LogPort": 514,
        "SSId": ["<My SSID Here>", ""],
        "TelePeriod": 300,
        "Resolution": "558180C0",
        "SetOption": ["04008001", "2805C8000100060000005A00000000000000", "00000000", "00006000", "00000000"]
    },
    "StatusMEM": {
        "ProgramSize": 586,
        "Free": 416,
        "Heap": 25,
        "ProgramFlashSize": 1024,
        "FlashSize": 1024,
        "FlashChipId": "144051",
        "FlashFrequency": 40,
        "FlashMode": 3,
        "Features": ["00000809", "8FDAC787", "04368001", "000000CF", "010013C0", "C000F981", "00004004", "00001000"],
        "Drivers": "1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45",
        "Sensors": "1,2,3,4,5,6"
    },
    "StatusNET": {
        "Hostname": "tasmota-3543",
        "IPAddress": "10.0.3.3",
        "Gateway": "10.0.0.1",
        "Subnetmask": "255.0.0.0",
        "DNSServer": "1.1.1.1",
        "Mac": "60:01:94:C4:2D:D7",
        "Webserver": 2,
        "WifiConfig": 4,
        "WifiPower": 17.0
    },
    "StatusTIM": {
        "UTC": "2020-12-31T00:11:21",
        "Local": "2020-12-31T01:11:21",
        "StartDST": "2020-03-29T02:00:00",
        "EndDST": "2020-10-25T03:00:00",
        "Timezone": "+01:00",
        "Sunrise": "08:43",
        "Sunset": "17:02"
    },
    "StatusSNS": {
        "Time": "2020-12-31T01:11:21"
    },
    "StatusSTS": {
        "Time": "2020-12-31T01:11:21",
        "Uptime": "0T05:56:24",
        "UptimeSec": 21384,
        "Heap": 25,
        "SleepMode": "Dynamic",
        "Sleep": 50,
        "LoadAvg": 19,
        "MqttCount": 0,
        "POWER1": "OFF",
        "Wifi": {
            "AP": 1,
            "SSId": "<My SSID Here>",
            "BSSId": "<BSSID Here>",
            "Channel": 5,
            "RSSI": 92,
            "Signal": -54,
            "LinkCount": 1,
            "Downtime": "0T00:00:03"
        }
    }
}
```

**Comment by jneilliii** [comment]
Yeah, that's what I would expect to see, and is what the plugin should be parsing as json, which is where you are getting that error. I'm a little confused as to why it's not pulling a status. So it's when the icon is grayed out and you click the icon for it to determine if the device is on or off?

**Comment by trevor229** [comment]
Yeah. I click it, it spins and then does not change and I see that error in the debug log.

**Comment by jneilliii** [comment]
This must be a plugin conflict of some kind. I just upgraded to 9.2.0 and am unable to reproduce this issue at all. Could you please grab your octoprint.log @trevor229 and share here (drag the file into a comment) so I can see if there is a common thread somewhere or any other potential error message I might be missing?

**Comment by trevor229** [comment]
Here is `octoprint.log` and `plugin_tasmota_debug.log` right after I deleted the old logs, re enabled the Tasmota plugin and tried setting up/connecting. Also may be worthy of note, the "Verify" button does say it is configured and responding properly.

[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5760120/octoprint.log)
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5760121/plugin_tasmota_debug.log)

Plugins I have installed besides this one:

- Bed Visualizer (Disabled)
- Creality-2x-temperature-reporting-fix
- GcodeEditor
- HeaterTimeout
- Octoprint-Display-ETA
- PortLister
- PrintTimeGenius
- UI Customizer

**Comment by jneilliii** [comment]
I've added a couple of additional debug logging lines to the check status method. Could you please try this version for me and re-share your plugin_tasmota_debug.log file after trying again? Copy/Paste the URL below into plugin manager > get more > ...from URL and click Install. You can install right over your 

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/develop.zip
```

**Comment by trevor229** [comment]
Just got the chance to install the new version as I had a long print going. Here is the new debug log, I verified that the config page still says the plug is responding and the behavior is the same as before.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5762402/plugin_tasmota_debug.log)

**Comment by jneilliii** [comment]
Ok, strangest thing. Can you check your OTA upgrade URL in Tasmota settings and remove the tab at the end of the line and see if it makes a difference?

**Comment by trevor229** [comment]
I changed the URL now and it partially works. I was able to click the toggle button in the UI and it turned the plug on, but when I clicked it again to turn it off, the dialog box says `<IP> is currently unknown. Are you sure you want to proceed?`. Clicking proceed does turn the plug off though.

**Comment by jneilliii** [comment]
Ah, good point. I haven't updated the confirmation prompts from when I split the settings data from the state data in one of the recent updates. I'll open a new issue for that.
