### ISSUE TITLE
Tasmota Settings configuration isn't displaying on Octoprint Version 1.5.0rc1

### ISSUE THREAD

**Issue by ZeekWorld** [jneilliii/OctoPrint-Tasmota#102]
After updating to Octoprint Version 1.5.0rc1, the existing device Tasmota configuration under the plugin settings page disappeared.
The device is still functioning but there is no way to view nor delete the device.
Also, I've tried to add a new device, the device was added, but still not showing under the settings page.
Tested the Tasmota settings page plugin on Chrome, Firefox, Safari and experienced the same behavior.

**Comment by ZeekWorld** [comment]
![image](https://user-images.githubusercontent.com/16088952/98988535-09797e80-24e5-11eb-9b42-31e7961d200d.png)

**Comment by jneilliii** [comment]
Please test with the RC version. Copy/Paste the URL below into plugin manager > get more > ...from URL. and click install

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.16rc1.zip
```

**Comment by ZeekWorld** [comment]
Your suggestion did the trick, all good now. Thanks!
