### ISSUE TITLE
[BUG]: Polling For Status Not Working

### ISSUE THREAD

**Issue by DodgeDeBoulet** [jneilliii/OctoPrint-Tasmota#106]
I use the OctoPrint UI from both a laptop in my shop and another in my office. I've noticed that when I turn a Tasmota device on or off via the browser on one computer, the status is not reflected by a color change of the icon on the other computer.

Is there any way to have the icon periodically refresh its status?

I'm running Chromium Edge on my Windows office system and Chromium on my Ubuntu 20 shop laptop, if it matters ...

**Comment by jneilliii** [comment]
That's what the polling option is for in the plugin's settings.

**Comment by DodgeDeBoulet** [comment]
Ok, then I guess I need to file a bug report? That option is checked (and apparently has been) but isn't working for me.

**Comment by jneilliii** [comment]
Nope, if it's not working then we can just flip this one.

**Comment by DodgeDeBoulet** [comment]
If you need logs or any other forensic data, please let me know.

**Comment by jneilliii** [comment]
That would be helpful. In the plugin's settings enable debug logging and restart octoprint for the change to be recognized, then let's see what the logs tell us. You'll find it in the logging section of octoprint, named `plugin_tasmota_debug.log`.

**Comment by DodgeDeBoulet** [comment]
Here's the log. I don't see any evidence of polling, but I probably don't know what to look for. I did flip a light on and off to generate some activity.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5638479/plugin_tasmota_debug.log)

**Comment by jneilliii** [comment]
can you also share screenshots of your settings so I can replicate exactly when I get some time to debug?

**Comment by DodgeDeBoulet** [comment]
Sure, here you go:
<img width="678" alt="Tasmota-Settings" src="https://user-images.githubusercontent.com/4532366/101082321-47644280-3579-11eb-9781-16f6ca1562d7.png">
<img width="908" alt="E5Plus-Settings" src="https://user-images.githubusercontent.com/4532366/101082345-4e8b5080-3579-11eb-8dac-71a79ca3f529.png">
<img width="907" alt="PrinterLights-Settings" src="https://user-images.githubusercontent.com/4532366/101082351-51864100-3579-11eb-932d-0a89ef731b7b.png">

**Comment by jneilliii** [comment]
ok, I don't see anything in the debug log at all that would cause this. Could you please check your octoprint.log for any errors that may be occurring? The only thing that stands out to me from your settings is the sensor identifier. Your status responses in the log don't indicate any data related to the sensor at all, so I'm wondering if that's breaking something in the polling since nothing for Ender5Plus is being logged.

**Comment by nquick** [comment]
Hi, 

I've also got this issue. I am using an S20 with v9.2.0. Latest octoprint and plugin. When clicking the power button on the top right, it says status unknown. 
I've checked http://172.16.16.49/cm?user=admin&password=&cmnd=Power and get {"POWER1":"OFF"}

It does turn the power on and off successfully

I'll grab the logs

**Comment by jneilliii** [comment]
Looks like I need to update to Tasmota version 9.2.0 and test, this seems very similar to #101.

**Comment by jneilliii** [comment]
This must be a plugin conflict of some kind. I just upgraded to 9.2.0 and am unable to reproduce this issue at all. Could you please grab your octoprint.log @DodgeDeBoulet and @nquick and share here (drag the file into a comment) so I can see if there is a common thread somewhere or any other potential error message I might be missing?

**Comment by jneilliii** [comment]
@DodgeDeBoulet checking back in on the original bug, are you still experiencing this issue with the latest version release 0.1.17.

**Comment by DodgeDeBoulet** [comment]
Hey, sorry about my recent silence. I've been involved in a time critical
project for a couple of weeks that has left me little time for anything
else. I'll see if I can confirm tonight or tomorrow and will get back to
you.

**Comment by DodgeDeBoulet** [comment]
Confirmed. Status updates immediately across multiple browsers on separate hosts. Thanks!

**Comment by jneilliii** [comment]
Thanks for confirming. I think it was the changes that I had made to split the state data from the settings data, which also broke the OctoPod app. Once I got that sending out messages to the clients again everything was back to working as before that change.
