### ISSUE TITLE
Autoshut-off not working: Sonoff S31 w/ Tasmota firmware 8.5.1

### ISSUE THREAD

**Issue by nnguyen555** [jneilliii/OctoPrint-Tasmota#107]
I am having trouble getting my Ender 3 V2 to turn off after a print. I can turn off/on the sonoff s31 manually using the lightening bolt and even send the m81 command in terminal and it turns off the unit. I have googled and a few others had the same issue, but none of the threads I found had a solution. I have also applied the Creality 2x temperature fix v0.4.0. which I found in one of the threads saying that before the fix the Ender V2 was reporting the temperature incorrectly causing the plugin to not work. The fix did not solve my issue. I have taken screen shots of the plugins I currently have installed, just in case someone sees a plugin that may be interfering with it as well as the Tasmota plugin settings. I am at my wits end and hoping someone has a solution for this. Thank you in advance.

![BUKDgkF](https://user-images.githubusercontent.com/48057598/101289871-af5a9900-37c4-11eb-96a6-982390c0d747.png)
![JDIbyx6](https://user-images.githubusercontent.com/48057598/101289872-af5a9900-37c4-11eb-8b51-9b631020e31a.png)
![WhHd5LG](https://user-images.githubusercontent.com/48057598/101289873-aff32f80-37c4-11eb-85ac-03b7cd4390d0.png)
![ZOj3gP0](https://user-images.githubusercontent.com/48057598/101289874-aff32f80-37c4-11eb-932a-4bcad588676c.png)

Edit: I have just downloaded the newest tasmoto plugin (0.8.16) just now and it doesn't resolve anything. :/

**Comment by jneilliii** [comment]
check that box in the specific tasmota config for "Off on Idle".

**Comment by nnguyen555** [comment]
> 
> 
> check that box in the specific tasmota config for "Off on Idle".

Awesome that worked. Thank you. I can't believe I missed that. I figured that having "Power off on idle" ticked was all that was needed.

**Comment by jneilliii** [comment]
Yeah, because you might control more than one device it has to be set that way.
