### ISSUE TITLE
Difference between shutdown via "M81 192.168.0.100 1" or the "green flash"?

### ISSUE THREAD

**Issue by dermigoe** [jneilliii/OctoPrint-Tasmota#108]
When I shutdown my Printer with the "green flash" in the topbar, my Octorprint shutdown normal an the Tasmota device gets it's delay time. After the delay the Tasmota device switches off. Everything as expected. The Tasmota consol says: 
10:35:41 MQT: stat/ender3/RESULT = {"Delay":450}
10:36:26 MQT: stat/ender3/RESULT = {"POWER1":"OFF"}
10:36:26 MQT: stat/ender3/POWER1 = OFF

But when i use the Shutdown Printer plugin an send a M81 command to the OctoPrint-Tasmota plugin the Octorpint shutdown normal but the Tasmota device stays on. When i open the Tasmota console an look at it nothing happens when the M81 command was send. Over hours. But when i power off the Tasmota device manual the delay time starts an shut off the Tasmota device again after the delay time. The Tasmota console says:
10:31:54 MQT: stat/ender3/RESULT = {"POWER1":"OFF"}
10:31:54 MQT: stat/ender3/POWER1 = OFF
10:31:54 MQT: stat/ender3/RESULT = {"Delay":450}
10:32:39 MQT: stat/ender3/RESULT = {"POWER1":"OFF"}
10:32:39 MQT: stat/ender3/POWER1 = OFF

The first off is that what i send manual.

Is there a difference between these two shutdown's?

This are the Version:

Tasmota device: 9.1.0
Octoprint: 1.5.1
OctoPrint-Tasmota: 0.8.16
Shutdown Printer: 1.0.9

Is this a bug or a operator error?

**Comment by jneilliii** [comment]
Could be a plugin conflict too, you don't need that other plugin to achieve what you want it can be accomplished with the idle timer. But can you share you're settings with me please? Both the overall plugin's settings and the specific individual device config.

**Comment by dermigoe** [comment]
I use the other Plugin to shutdown the printer when the temperature of the hotend is below 50°C. Then this plugin sends the M81 command.
Here are my Settings.
![Tasmota_1](https://user-images.githubusercontent.com/47417406/101393686-c3d38a00-38c7-11eb-847b-52dd2cfdc0d7.jpg)
![Tasmota_2](https://user-images.githubusercontent.com/47417406/101393697-c8983e00-38c7-11eb-9173-c5da25685d8a.jpg)
![Tasmota_3](https://user-images.githubusercontent.com/47417406/101393709-cb932e80-38c7-11eb-8a1b-19e7bdbf1279.jpg)

**Comment by jneilliii** [comment]
Interesting, did you not notice the same options under the "Power Off on Idle" option when it's enabled? I wonder if this is a conflict or not. If you want to try that idle option, you'll need to enable the setting on the main page and then also there are option inside the device configuration as well "off on idle".

**Comment by dermigoe** [comment]
Thank you for this hint. I will try this, but it is more comfortable for my if i can choose to shutdown the printer or not.

**Comment by jneilliii** [comment]
Do me a favor, enable debug logging by checking the box on the main settings and then restart octoprint. Run a print that has the `M81 192.168.27.50 1`  command in it and then take a look at the file `plugin_tasmota_debug.log` in the logging section of OctoPrint for possible errors. You can share that file with me by dragging it into a comment here.

**Comment by dermigoe** [comment]
Here are the Logs (with index *_1). At first the shutdown with M81 command at  nearly 19:55.
I switched off the tasmota device off at nearly 20:00 with a MQTT command

[octoprint_1.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5671038/octoprint_1.log)
[plugin_tasmota_debug_1.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5671039/plugin_tasmota_debug_1.log)
[Tasmota_Console_1.txt](https://github.com/jneilliii/OctoPrint-Tasmota/files/5671040/Tasmota_Console_1.txt)

Then i shutdown with the button  in the topbar at nearly 20:05. Here the tasmota device switched off automatically. These are the logs with the index *_2

[plugin_tasmota_debug_2.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5671055/plugin_tasmota_debug_2.log)
[Tasmota_Console_2.txt](https://github.com/jneilliii/OctoPrint-Tasmota/files/5671056/Tasmota_Console_2.txt)
[octoprint_2.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5671057/octoprint_2.log)

**Comment by dermigoe** [comment]
I tried to analyze my problem with wireshark. I saw the difference betwen the M81 command and the button in the topbar.

When i switch off with the button in the topbar the command with the delay is send an about 0.2 seconds later a status%200 command is send to the tasmota plug. 

When i switch off with the M81 command only the delay message is send and not the status%200.

So i send at first the *cmnd=backlog%20delay%20150%3BPower1%20off%3B to the tasmota plug. Nothing happend. Only this was showing in my browser window: "{"WARNING":"Enable weblog 2 if response expected"}". The tasmota console shows nothing.
Only when i send the *cmnd=Status%200 after the first command i see the delay in the tasmota console an the plug switch off after the delay time.

I hope you can understand what i am meaning.

**Comment by jneilliii** [comment]
I think this issue may be related to #109 and some of the internal changes that were made to split the state data from the settings data. I just need to check to see in the gcode processing stuff how that's being handled since making those previously mentioned changes. Can you check my current rc version to see if the problem still exists for you? Copy/paste the URL below into plugin manager > get more > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.17rc1.zip
```

**Comment by dermigoe** [comment]
I checked the rc version and the problem is still there. With the M81 shutdown no *cmnd=Status%200 is send and the tasmota plug dont shut off.

**Comment by jneilliii** [comment]
I'll have to walk through the process logic again for the countdown timers. I will look into it once I have some spare time.

**Comment by dermigoe** [comment]
Today i upgrade my tasmota plug to the newest development release 9.1.0.2. Now the M81 shutdown is rigt but the button shutdown wents wrong. When i try to shutdown with the button the plug goes off within a second. I thing its a bug of the tasmota firmware. When the status web command is send the tasmota firmware forget the delay an shut down immediately.
Thank you for your help and sorry to waste your time.

**Comment by jneilliii** [comment]
It's not a waste of time, and may be something that's still an issue if the button now no longer works properly. The one thing that I would make sure of on the new install of Tasmota is that SetOption26 is ON, because that is what makes the plugin's callbacks work properly. Otherwise, if you leave that SetOption26 OFF you need to remove the index from the settings, but that will surely break the M81 command.

**Comment by dermigoe** [comment]
Thank you. The SetOption26 is ON. I think the `*cmnd=Status%200` directly after the backlog command isn't right. I read the [Tasmota Commands](https://tasmota.github.io/docs/Commands/#the-power-of-backlog) an in the example they wrote: 
> in case of command Backlog Power1 OFF; Delay 600; Power1 ON the usage of an additional Backlog command without any argument within the delay time of 1 minute will delete the whole queue Power1 OFF; Delay 600; Power1 ON. Therefore Power1 ON command will not be executed and the power would remain off.

So i think the M81 Shutdown with no `*cmnd=Status%200` is correct. And the shutdown with the button wich sends the `*cmnd=Status%200` a short time after the backlog command breaks the backlog an so it shut off immediately.

**Comment by jneilliii** [comment]
I would agree with that if the backlog command was being used for the status check command, but it's not so the relevant note in the docs for Tasmota should not apply. Could you do me a favor and test this with the older version of the plugin? Copy/Paste the URL below into plugin manager > get more > ...from URL and clicking install. Just trying to rule out if some of the recent changes I've made broke this possibly. After restarting OctoPrint make sure to not upgrade and see if the issue persists.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.16rc1.zip
```

**Comment by jneilliii** [comment]
I've been able to re-create the issue. Best I can tell it looks like it's sending the system command to shutdown the pi prior to the backlog command being sent to the tasmota device. I'll see if I can track down why that's happening with gcode commands.

**Comment by dermigoe** [comment]
Since the 0.8.17 release the plugin works flawless. Thank you for the fix an the work on this plugin!
