### ISSUE TITLE
Release 0.8.16 no longer works with OctoPod

### ISSUE THREAD

**Issue by gdombiak** [jneilliii/OctoPrint-Tasmota#109]
Hi @jneilliii, OctoPod works with many of your plugins for controlling switches. With the release of 0.8.16 of this plugin, it stopped working and someone created [this issue](https://github.com/gdombiak/OctoPod/issues/423).

After some investigation, I see that #check_status no longer returns the status via plugin commands but instead is returned in the same response. OctoPod is expecting the answer to come via websockets and not in the HTTP response so it never gets the status if the plug. Since status is unknown then users cannot turn them on/off from OctoPod.

All your plugins follow the same API design so I coded it once and it works with all your plugins. This is the first plugin that stopped working so I wanted to know how to proceed:
1. Are you going to change all your other plugins to work like this one?
1. If not, would it be possible to keep sending the status via websockets? Not super efficient but you can still send it in the HTTP response and still send it via websockets. Maybe there are other clients besides OctoPod that integrates with this plugin. 

Let me know what you think and I will know how to fix (if needed) OctoPod.

Thanks,
Gaston

**Comment by jneilliii** [comment]
Thanks for letting me know @gdombiak I wasn't aware OctoPod supported any of these. We can revert back to websocket messages in favor of the API responses, shouldn't be an issue. I had done that as part of the separation of status data and settings data, but getting the info back to multiple clients makes more sense the other way now that I think about it. You sure this is still working with all the other ones because I thought I had taken out websocket responses in TPLink a long time ago.

**Comment by gdombiak** [comment]
Thanks @jneilliii. OctoPod supports many of your plugins. See [list](https://github.com/gdombiak/OctoPod/wiki/Supported-Plugins). I have not received other reported issues but if websocket communication got removed then they are also broke. Let me know if you are also planning on adding back websocket communication to the other plugins.

I do not have any of these kind of switches (my house runs on zwave + custom made sensors and of course my own server and iPhone app) so I do not usually test that these plugins keep working. I rely on end users to report when this happens.

Regards,
Gaston

**Comment by gdombiak** [comment]
Looking at [the source code ](https://github.com/jneilliii/OctoPrint-Tasmota/commit/95648d7b277d322748cdc4c6349725f4635513e5)I think that the #send_plugin_message is still missing from #check_status(self, plugip, plugidx). That is the function that will report current status of the plugs via websockets. OctoPod need to know current plug status to know if a click is for turning on or off the plug.

**Comment by jneilliii** [comment]
You sure @gdombiak, it's right [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/95648d7b277d322748cdc4c6349725f4635513e5/octoprint_tasmota/__init__.py#L403).

**Comment by gdombiak** [comment]
When I debugged the code flow I saw [this method](https://github.com/jneilliii/OctoPrint-Tasmota/blob/95648d7b277d322748cdc4c6349725f4635513e5/octoprint_tasmota/__init__.py#L405) being called. It then returns JSON [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/95648d7b277d322748cdc4c6349725f4635513e5/octoprint_tasmota/__init__.py#L458) which is now returned with an HTTP response 200 (before used to be 204 with no content) [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/c86efa5856a397b609929339e6a84f1921a7376c/octoprint_tasmota/__init__.py#L501).

OctoPod was expecting a 204 response and for check status to return the data via websockets.

**Comment by jneilliii** [comment]
Yeah, the method for check is being called [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/95648d7b277d322748cdc4c6349725f4635513e5/octoprint_tasmota/__init__.py#L403) for polling and on startup IIRC. That return is then being sent via websocket in the for each loop. But I see that the check status API wouldn't be doing the websocket send. I'll add that in to the API call.

**Comment by jneilliii** [comment]
Have confirmation from your ticket from two users that the last change resolved the issue, have release 0.8.17 officially.
