### ISSUE TITLE
OctoPrint: 1.5.2 

### ISSUE THREAD

**Issue by philipp-andreas** [jneilliii/OctoPrint-Tasmota#110]
Tasmota plugin don´t work anymore, after upgrade octoprint to 1.5.2 version.

**Comment by jneilliii** [comment]
I use in 1.5.2, so you're going to have to be more specific.

**Comment by philipp-andreas** [comment]
Sorry, it was a strange problem with my router. only my pi had no connection to may tasmota switch. after a router restart the tasmota plugin work now as expected. thank you for your work!
