### ISSUE TITLE
M80 workaround

### ISSUE THREAD

**Issue by smulle48** [jneilliii/OctoPrint-Tasmota#112]
Hi

I have been struggling with the M80 command, just to find out it does not work if the printer is off :-/

I finally managed to get it working, with some tinkering with the config.yaml :-D

In the OctoPrint/OctoPi config.yaml file (located ~/.octoprint/config.yaml) I've added the following:

`events:`
`    enabled: true`
`    subscriptions:`
`    -   command: sh /home/pi/startprinter.sh`
`        event: Upload`
`        type: system`

Then I've created the sh file (/home/pi/startprinter.sh) with the following code:

`#!/bin/bash`

`curl http://<TASMOTA IP>/cm?cmnd=Power%20On`
`echo “Wait for 10 seconds”`
`sleep 10`
`echo “Completed”`
`curl -H "Content-Type: application/json" -H "X-Api-Key:<API KEY>" -X POST -d "{ \"command\" : \"connect\" }" http://<OCTIPI IP>/api/connection`

The code first turn on the tasmota plug, then wait 10 seconds and then send the connect command to octoprint to make it connect to the printer.

Then save it all and restart octoprint. Now when uploading a file, the printer turns on, waits 10 seconds and then octoprint connects to the printer.

Now I just have to figure out how to make it print the last uploaded file. So far I'm just uploading it from PrusaSlicer, then I wait until the printer is online, and then upload again :-D

**Comment by jneilliii** [comment]
The upload event monitoring option should work when uploading from prusa if the option to auto print its checked when sending.

**Comment by jneilliii** [comment]
I'm sorry, I think that option is in my tplink plugin, not this one yet.

**Comment by jneilliii** [comment]
Added the upload event monitoring in the above commit. When sending files from PrusaSlicer/SuperSlicer if the option is selected to autostart the print, after the file is uploaded the configured tasmota device will be powered on, connect to printer (if enabled), and upon connection to the printer the uploaded file will automatically start printing. If you would like to test it out, please copy/paste the URL below into Plugin Manager > get more > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.17rc4.zip
```

**Comment by smulle48** [comment]
> Added the upload event monitoring in the above commit. When sending files from PrusaSlicer/SuperSlicer if the option is selected to autostart the print, after the file is uploaded the configured tasmota device will be powered on, connect to printer (if enabled), and upon connection to the printer the uploaded file will automatically start printing. If you would like to test it out, please copy/paste the URL below into Plugin Manager > get more > ...from URL and click Install.
> 
> ```
> https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.17rc4.zip
> ```

It's working perfect now. Thank you for the quick update :-D

**Comment by jneilliii** [comment]
Cool. I already had the programming logic from my other plugin, just had to merge it over.
