### ISSUE TITLE
Pre and Post Command

### ISSUE THREAD

**Issue by delucs** [jneilliii/OctoPrint-Tasmota#114]
As I understand, the pre and post commands are only system commands, could you add a web command, I would like to switch a tasmota light on when the printer goes on, and off when the printer goes off...
like: http://192.168.1.123/cm?cmnd=Power%20off
several commands would be even better :-)

**Comment by jneilliii** [comment]
The plugin actually sends those exact commands directly and you can have multiple devices configured in the plugin, so I'm not quite sure where the confusion is here?

**Comment by delucs** [comment]
I found the solution or better someone suggested to add "curl" before the command and this works now perfectly. what does not work is if I upload a file to octoprint by drag and drop in the web interface, it will not automatically switch the tasmota device on, so that that printer comes online. Only if the printer is online it seems to be possible to auto-start printing (with a plugin).  maybe you have a solution to that too?

**Comment by jneilliii** [comment]
Yeah, the upload event monitoring option released in the latest version will work from PrusaSlicer/SuperSlicer/Slic3r when you send directly to octoprint and the option to autostart the print is enabled. if you use Cura, the OctoPrint Connection plugin for Cura will allow you to automatically control the power state when it sends the file to OctoPrint. I use both actually.

**Comment by delucs** [comment]
I use cura, but will not work when independantly drag and dropped in the octoprint webpage...

**Comment by jneilliii** [comment]
Since Cura has this capability with the OctoPrint connection plugin, I'm going to close this issue. I may consider in a future update to include a toggle option for web uploads.
