### ISSUE TITLE
Powering on with icon triggers last upload to start printing.

### ISSUE THREAD

**Issue by rullywowpcb** [jneilliii/OctoPrint-Tasmota#118]
Hey, great plugin btw!

I have "start print upon upload" enabled which is wonderful and works great. The issue I seem to be having is that the printer starts printing the last file when I manually power on. It's extra annoying because I can't cancel the print until the bed warms up to temp by using the Octoprint cancel button.

Steps to recreate:

1) Make sure the "monitor for uploads" is enabled
2) Print and after finished I let plugin turn off by idle timeout
3) Turn on printer using the web interface Tasmota button on top of main Octoprint page
4) Printer powers on and starts printing last upload

Maybe I have a setting incorrect?

**Comment by jneilliii** [comment]
This very well could be a bug. I will see if I can reproduce. One question though, did you let the uploaded file complete all the way, or was it cancelled mid-print when this happened? I'm pretty sure I clear the file from the queue on print completion, but would have to go back in code and verify.

**Comment by jneilliii** [comment]
Confirmed bug. I just looked through the code real quick again and I didn't migrate that clearing of the uploaded file on print completion when I merged these features in from my other plugin. I'll try to get that fixed this weekend.

**Comment by jneilliii** [comment]
This should be fixed by the above commit. If you want to test it out, you should be able to switch the release channel to `Development` in the Software Update settings of OctoPrint and you will get prompted to update.

**Comment by jneilliii** [comment]
actually, I take that back. Just noticed I didn't add the development release channel. You'll have to manually install by copying/pasting the URL below into plugin manager ? get more > ...from URL and clicking Install over the existing installation.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.18dev1.zip
```
