### ISSUE TITLE
Update 1.0.0 Breaks when Passwords with Special Characters are Used

### ISSUE THREAD

**Issue by TheDiNi74** [jneilliii/OctoPrint-Tasmota#121]
After Update to new Release 1.0
25.01.2020

all functional bevor update only this plugin

system octoprint 1.5.3@octopi 

1.)
The Status does not working any more in "top status bar"
2.)
Switch (mouse click at status) power status does not work anymore.
3.)
Error Message shown as popup
"Tasmota Error
Status off for 192.168.50.117. Double check IP Address\Hostname in Tasmota Settings."

If check the config.. no changes from previous working config..
Press the 'verfiy' Message.. say all ok

The Setup working fine..over many versions and updates;)

p.s. nice work

Need infos&tests? Send a Message

**Comment by TheDiNi74** [comment]
Look like an old issue, i have seen.. and you solved.

I habe enabled the webui password protection in tasmota device.
if i remove this pw, 
the plugin.. works finde(version 1.0)
;-)
The Password contain a:
!
if this helps
Incorporate Status Polling (#41)

**Comment by TheDiNi74** [comment]
If i remove the webui Password in the tasmota device itself..(Dont change the plugin config..do not remove the password)
the plugin status display...switch status with click at status..working ...all working fine

hint the password using a
!

**Comment by jneilliii** [comment]
Thanks for your report @TheDiNi74, I'll take a look. I did change things around a little and thought that I moved everything with the encoding over the same. I will attempt to reproduce on my end and report back when I have some time.

**Comment by jneilliii** [comment]
I got this fixed in 1.0.1rc1 and ready to release. If you want to test it out you can go into OctoPrint's Software Update settings and switch the plugin's Release Channel to `Release Candidate` and it should prompt you to install.

**Comment by TheDiNi74** [comment]
changed to releas candidate.. rc1
now the plugin works as expected .
no other tasks done..only update ;)
Thx..good work
solved

**Comment by domhardt** [comment]
> I got this fixed in 1.0.1rc1 and ready to release. If you want to test it out you can go into OctoPrint's Software Update settings and switch the plugin's Release Channel to `Release Candidate` and it should prompt you to install.

Had the same problem but this solved it.

**Comment by jneilliii** [comment]
Thanks guys. I'll get this updated tonight to full release 1.0.1.
