### ISSUE TITLE
IP address changed, Tasmota stopped working

### ISSUE THREAD

**Issue by mpzross** [jneilliii/OctoPrint-Tasmota#123]
I had the Tasmota plugin working beautifully. I set a reserved IP address for it in my router. My router failed. With the new router the Tasmota picked a different IP address so I made it reserved and changed the IP in the plugin settings. The plugin stopped working. Monitoring the Terminal in Octoprint I saw that the plugin was still sending the old IP address OFF command. I deleted the plugin and its settings and reinstalled. Set up a new Tasmota with the correct IP but the plugin was still sending the old IP command. I changed the IP in my router. It works again. I'm just curious why?

**Comment by jneilliii** [comment]
I've never heard of this before. After making all the changes did you attempt to restart octoprint just to see if it was some stuck setting that wasn't getting update properly maybe? I'd need you to enable debug logs and provide logs after the fact to be able to troubleshoot this further.

**Comment by jneilliii** [comment]
Also, you might not be aware of this, but you can also use the hostname of the device rather than IP address if you want.

**Comment by mpzross** [comment]
Thank you for your reply.
Yes I did restart octopi. No difference. My router doesn't recognise
devices by name, unfortunately. It's not a problem since I worked out how
to fix it!

**Comment by Barracuda666** [comment]
I had the same issue today, but: it was caused by leaving the INDEX blank. When i enter "1" on a single relais Tasmota (SP111 v1.1") = > it works.

**Comment by mpzross** [comment]
I'll have to try that, thank you.

**Comment by jneilliii** [comment]
The Index is only required if your Tasmota has SetOption26 enabled (which the verify button will check for) and enable when prompted to do so. Is SetOption26 is turned off on your tasmota then you should be able to leave index blank.
