### ISSUE TITLE
Backlog Timer backlog_off_delay 

### ISSUE THREAD

**Issue by dajupp** [jneilliii/OctoPrint-Tasmota#125]
please have a look at __init__.py at line 458

variable backlog_on_delay is used instead of backlog_off_delay

I think this is wrong :)

**Comment by OperatorB** [comment]
Hi,
is this related to the phenomenon when after boot this plugin shuts the system down then turns off the tasmota device with backlog delay? (so it does not wait for the idle time to expire)

**Comment by dajupp** [comment]
No. After idle timer is running out and shutdown is initiated the tasmota device turns off without timeout because the backlog_on_delay is set to zero. 

I think the developer used the wrong variable

**Comment by dajupp** [comment]
![image](https://user-images.githubusercontent.com/75271113/106265497-686aac00-6227-11eb-8273-fc2fa363b39f.jpeg)

**Comment by OperatorB** [comment]
Ok thanks, I think we are on separate issue. I just had to set 'Abort Power Off Timeout' like 120sec long to be able to cancel the immediate shutdown process after Raspberry boot. Then the whole stuff works like it should.
![image](https://user-images.githubusercontent.com/34603896/106286614-200eb680-6246-11eb-8333-17ccf062b3ae.png)
![image](https://user-images.githubusercontent.com/34603896/106286654-2ac94b80-6246-11eb-9e22-7924e9aa1e7d.png)

**Comment by jneilliii** [comment]
@OperatorB you are totally right, that's probably a copy/paste error that was missed since I don't really use this plugin with backlog commands. I'll get that fixed for the next release. Thanks for spotting that.

**Comment by jneilliii** [comment]
This should be fixed with the above commit and available in the Release Candidate 1.0.1rc2, you can switch to that Release Channel in OctoPrint's Software Update settings if you want to try it out and verify.
