### ISSUE TITLE
Feature Request: Switch On/Off on GPIO input

### ISSUE THREAD

**Issue by Delta-38** [jneilliii/OctoPrint-Tasmota#127]
Hi, would it be possible to add the option to toggle power based on GPIO status? Similar to the Gcode based functionality.
In my use case, I would like to be able to enable the controlled tasmota unit to switch off power if a given GPIO goes high/low, in my case it is a sensor, and going high is a good case for emergency poweroff. But it would also be convenient to power on when away from a phone or other interface device (My tasmota is under and behind the printer assembly so not very convenient, but useful to keep AC voltage far from my tinkering hands).

I know I could connect the sensor to the Tasmota unit directly but it seems more straightforward to have Octoprint control this kind of behavior.

**Comment by jneilliii** [comment]
I personally don't want to get into GPIO programing for the plugin as that will restrict it's compatibility to only Pi devices, but I can offer you an alternative. Find a script that allows you to monitor GPIO (pretty easy to find examples floating around the internet) and use that to run the curl API commands. 

https://github.com/jneilliii/OctoPrint-Tasmota/wiki/API
