### ISSUE TITLE
icon/button control

### ISSUE THREAD

**Issue by gregsyoung** [jneilliii/OctoPrint-Tasmota#129]
have plugin setup using a 4 outlet power board (0ne IP address) with 4 index’s. - all good working fine.
(index 1 = overhead LED light, index 2 = OctoPi, Index 3 = Printer)
after setting up the editor with a labl “light” & “printer” (with warnings ticked) 
these show up on top bar - with the respective Icon i chose.. all good so far.

However when i click on the icon - it brings up the warning message .. but it “only” uses the IP address 
(which is the same for all the relay outputs on the powerboard) 

would it be  possible  to add the label into the warning message? (or at least add it along with IP address on the warning message) 
.. obviously I donw want to switch of the printer mid activity, but I do switch Light on/off periodically to check print progress in octoprint. (& the icons are small and only show the label when its pressed) 

Hence that way it would have a warning .. like ..
” LED light is currently on are you sure you wish to proceed” .
and “Printer is currently on ... are you sure you wish to proceed” 

and my compliments on a great plugin... 
....

**Comment by jneilliii** [comment]
I don't think that would take too much effort, thanks for pointing this out.

**Comment by jneilliii** [comment]
The label should be added with the above commit. If you want to test it out switch the Release Channel to `Release Candidate` in OctoPrint's Software Update settings and upgrade when prompted.

**Comment by gregsyoung** [comment]
hi
confirming the RC installed ok & is working correctly (now showing the 
label of the device in the proceed dialog box)

all working as expected - many thanks as this will help prevent 
incorrect device switchoff.

------ Original Message ------
