### ISSUE TITLE
Latest Version Breaks Existing Configuration

### ISSUE THREAD

**Issue by thetonto** [jneilliii/OctoPrint-Tasmota#13]
Just auto updated to the latest version and Tasmota has stopped working.  Was working before the update so configuration was correct.

Have confirmed the IP address is correct and index is one.  I have a simple Sonoff Switch.

Cheers

**Comment by jneilliii** [comment]
Have you tried with setting the index to blank? The simple single relay devices may not respond correctly with 1, but leaving the index blank should work.  If it doesn't please post your octoprint.log so I can see if there are any errors.

**Comment by thetonto** [comment]
Setting the index to blank worked.  I had tried setting to 0 as thinking that direction.  You might want to update the documentation, or if possible remediate the code as 1 did work before this update.  Many thanks
