### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by oxicottin** [jneilliii/OctoPrint-Tasmota#132]
@jneilliii I'm now having a similar issue apart from the TPlink one. I purchased a pre config EZPlug from TH3D and it was quite easy to set up. I set a manual IP and it logs into the tasmota plug using its IP in the browser. I installed your OctoPrint-Tasmota and added the IP address and clicked the Verify button and nothing happens so I saved and rebooted octoprint. It comes up with the error message below. I go into my browser and enter the EZPlug IP and it comes right up and I can toggle it on and off from the browser.  Ideas?

![error](https://user-images.githubusercontent.com/34151610/109203259-ef9d3800-7771-11eb-9990-95a64f60b037.jpg)

**Comment by jneilliii** [comment]
If the verify button doesn't work, then there's something blocking the communication with the plug. Could be network routing related. Did you enter anything into the index field?

**Comment by oxicottin** [comment]
No I left the index as 1.

**Comment by jneilliii** [comment]
Can you please enabled debug logging in the plugin, restart OctoPrint, and try the process again. Once it still doesn't work grab the octoprint.log and plugin_tplinksmartplug_debug.log files from the OctoPrint's logging section and upload it here in a comment to debug more.

**Comment by oxicottin** [comment]
@jneilliii this has to be an issue with my router because I'm having the same issue sort of with that TP link before I purchase this one to give it a go because it was local. I'm not even seeing it on my Asus RT-AC3200 router unless I turn the plug on/off. I just purchased a new router TP-Link Archer C4000 I will see if that is any better I'm sick of this ASUS one anyway...

**Comment by jneilliii** [comment]
Oh, ASUS there's a setting I think....stand by.

**Comment by jneilliii** [comment]
If your router has the WMM APSD (automatic power save delivery) you should disable it.

https://community.octoprint.org/t/octopi-wifi-network-connection-troubleshooting-megatopic/2608/264?u=jneilliii

**Comment by oxicottin** [comment]
I found it in my routers settings under Wireless/Professional Ill give it a try! Thanks!!!

![Capture](https://user-images.githubusercontent.com/34151610/109376015-9fb49300-788f-11eb-94ae-831107cb4adb.JPG)

**Comment by oxicottin** [comment]
@jneilliii, I recieved my TP link router today and boom showed it working! The ASUS router is horrible and was time for new... Thanks for the help!
