### ISSUE TITLE
Thermal Runaway only triggered once

### ISSUE THREAD

**Issue by Roxolasu** [jneilliii/OctoPrint-Tasmota#136]
Steps to reproduce:
1. Trigger thermal runaway -> power is cut
2. Repower the printer without restarting octoprint
3. Try to trigger Thermal runaway again

Expected Result: 
- Power down is triggered

Actual Result: 
- Power remains on

**Comment by jneilliii** [comment]
Did you enable the option inside of the individual device configuration as well?

**Comment by Roxolasu** [comment]
Interesting - thermal runaway is triggered only the first time. Issue updated accordingly.

**Comment by jneilliii** [comment]
That does make sense now that I look at the code [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/3251efd584d60cbc1ee6b89b6548ff708a4078c4/octoprint_tasmota/__init__.py#L714). The thermal_runaway_triggered flag never gets reset back to False and therefore is getting bypassed once triggered once until the next OctoPrint restart. I need to reset that back to False on a new connection to printer after it has been triggered once. Thanks for the heads up.

**Comment by jneilliii** [comment]
Should be fixed in the above commit I think. If you want to try it out switch your Release Channel for the plugin to `Release Candidate` and update when prompted.

**Comment by Roxolasu** [comment]
Its working, thank you!

Minor point: "Thermal Runaway was triggered prior to the last printer connection." seems somewhat hard to understand - maybe just "Thermal Runaway was triggered previously"?

**Comment by jneilliii** [comment]
> Minor point: "Thermal Runaway was triggered prior to the last printer connection." seems somewhat hard to understand - maybe just "Thermal Runaway was triggered previously"?

Fair point, I'm sharing the same pop-up message for when it's triggered and was trying to make sure I knew where it was happening during debugging.
