### ISSUE TITLE
Graph stuck at "Jan 2000 - Jan 2001"

### ISSUE THREAD

**Issue by Airwolf1544** [jneilliii/OctoPrint-Tasmota#137]
Hi,

the Graph in Octoprint only shows timerange "Jan 2000" till "Jan 2001".
I can choose another Start and/or End Time, but the "Update" Button don't do anything.
Toogle Legend also not working.

Tom

**Comment by jneilliii** [comment]
Can you please check your browser's developer console (F12) for any errors on initial page load? Also, you can enable debug logging in the plugin's settings, restart OctoPrint and then try again, and then share the plugin_tasmota_debug.log and octoprint.log file from the OctoPrint's logging section. You can drag them into a comment here.

**Comment by Airwolf1544** [comment]
Have some warnings in the developer Console:
`The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.0.69/static/vendor/font-awesome-5.15.1/webfonts/fa-regular-400.woff2?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.0.69/static/vendor/font-awesome-5.15.1/webfonts/fa-solid-900.woff2?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.0.69/static/vendor/font-awesome-5.15.1/webfonts/fa-brands-400.woff2?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.0.69/static/vendor/font-awesome-5.15.1/webfonts/fa-solid-900.woff?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.0.69/static/vendor/font-awesome-5.15.1/webfonts/fa-regular-400.woff?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.0.69/static/vendor/font-awesome-5.15.1/webfonts/fa-brands-400.woff?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

I've enabled debug logging in Tasmota and restartetd Octoprint at 2021-03-20 11:28:08
Then i go to Octoprint Webpage.
Switched on the Printer with the nav bar toggle (Tasmota).
Then i went to Tasmota Tab and tried a few things: Toggle Legend, Change the date to display and press "Update".
Here the Logs
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6175311/octoprint.log)
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6175312/plugin_tasmota_debug.log)

**Comment by jneilliii** [comment]
Do you have a sensor connected and/or using a power monitoring enabled device like the sonoff POW2? I don't see any data responding from your tasmota that would indicate it does, and in theory you shouldn't even see the tab because there isn't any data that it can graph.

**Comment by Airwolf1544** [comment]
I have a Sonoff S26 in my network (but without Tasmota). Nothing else...

Am Di., 30. März 2021 um 05:28 Uhr schrieb jneilliii <
***@***.***>:

**Comment by jneilliii** [comment]
Well the plugin requires tasmota to be able to function.

**Comment by Airwolf1544** [comment]
Yeah, i know.. i have a Sonoff S20 with Tasmota (used for my Ender 3 V2)
But i also have a Sonoff S26 with original FW somewhere else...

Sonoff S20 works fine in Octoprint with your plugin. The only problem is
the graph...

Thy

Am Di., 30. März 2021 um 14:40 Uhr schrieb jneilliii <
***@***.***>:

**Comment by jneilliii** [comment]
Ok, looking at the specs of the S20 it does not have power monitoring capabilities, so the reason the tab isn't graphing anything is because your device doesn't report the data necessary to be able to be graphed. You would have to add an external sensor for temp/humidity or replace the S20 with a device that includes power monitoring capabilities. You've basically hit a physical hardware limitation. 

I am confused why the tab is showing up in your OctoPrint though, because like I mentioned before it should know that there is no capabilities and hide itself.

**Comment by Airwolf1544** [comment]
You are right.. S20 doen't have power monitoring :-) i was blind. Ok.. 
So.. if there is nothing.. Tasmota plugin cannot shot anything :-)
Thx for searching ;-) 
You did a great job with this plugin!!!

Thank you!
