### ISSUE TITLE
customize tasmota http request timeout value

### ISSUE THREAD

**Issue by togeis** [jneilliii/OctoPrint-Tasmota#142]
Hi, 
i have the problem, that my tasmota device sometimes needs more than 3sec to react for a webrequest. 

```
time curl "http://192.168.178.91/cm?user=admin&password=&cmnd=Status 0"
{"Status":{"Module":0,"FriendlyName":["LED Drucker","Gosund Steckdose 6"],"Topic":"LEDDrucker","ButtonTopic":"0","Power":2,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
real	0m0.062s
user	0m0.002s
sys	0m0.005s

time curl "http://192.168.178.91/cm?user=admin&password=&cmnd=Status 0"
{"Status":{"Module":0,"FriendlyName":["LED Drucker","Gosund Steckdose 6"],"Topic":"LEDDrucker","ButtonTopic":"0","Power":2,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
real	0m4.825s     <<--- response > 3sec
user	0m0.002s
sys	0m0.004s
```

I use Tasmota 8.2.0

So i see in the plugin logs the following:

```
[2021-04-11 18:06:19,442] ERROR: Invalid ip or unknown error connecting to 192.168.178.91.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 498, in check_status
    webresponse = requests.get("http://{}/cm".format(plugip), params={"user": plug["username"], "password": plug["password"], "cmnd": "Status 0"}, timeout=3)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='192.168.178.91', port=80): Read timed out. (read timeout=3)

```

Can you implement a input box to set a custom timeout value? Maybe a dropdown box with values from 3-10Sec ?

Thx&regards
togeis

**Comment by jneilliii** [comment]
I had added that lower timeout fairly recently. I have no issue with either making it configurable, or possibly just increasing the value to something higher like 10 seconds? The only reason I added the timeout is because a request would go forever without it and in cases where a device wasn't responding it would just create a memory leak in the plugin.

**Comment by togeis** [comment]
making the timeout configurable would be great. Thx 👍

**Comment by jneilliii** [comment]
I've enabled a configurable option in the above commit. If you want to test out and confirm you can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted.

**Comment by togeis** [comment]
thx for implementing. I have installed 1.0.4rc1 but there is no option for the timeout. I see in git, that you have changed it in the "rc" branch, but its not changed in the tagged 1.0.4rc1 code.

**Comment by jneilliii** [comment]
My bad, I pushed the changes to my rc branch but forgot to create the release. You should be able to force check for updates and get an update notice now.

**Comment by togeis** [comment]
Test was successful. Thx for implementation.
