### ISSUE TITLE
Sensor not displaying sensor values

### ISSUE THREAD

**Issue by TheToxicant** [jneilliii/OctoPrint-Tasmota#144]
I have a DHT11 [sensor](https://lensdump.com/i/IfSmmQ) linked to the [Tasmota](https://lensdump.com/i/IfSBIM) relay and the plugin recognizes the device but does not display sensor [values](https://lensdump.com/i/IfSdUA). Lensdump links attached to display the problem I am encountering.

**Comment by jneilliii** [comment]
Can you enable debug logging, restart octoprint and check the status, toggle the switch, etc. and then grab the plugin_tasmota_debug.log file from the logging section of octoprint's settings.

**Comment by TheToxicant** [comment]
Turns out i already had debugging enabled so here is todays
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6332537/plugin_tasmota_debug.log)

**Comment by jneilliii** [comment]
Log seems to indicate a connection issue. You sure you got the ip correct? I also see two different ips in the log, both of which are not responding to the command request.

**Comment by TheToxicant** [comment]
I had an ip address issue for a little bit because my router was in need of an update and it renewed my ip address a few times before I manually assigned it one and the device itself is hooked to a Wi-Fi extender the connection is significantly more stable now  but both prior to the update and extender I was never able to get the sensor values to display.

**Comment by TheToxicant** [comment]
It has never had issues toggling the relay just displaying sensor values it would display the relay state correctly.

**Comment by jneilliii** [comment]
This is stranger then, because if debug logging was enabled it should be showing a lot more in the log than just errors. There should be information displayed from the process of toggling the relay, etc. Do you have status polling in the plugin enabled? Are there any other random errors in octoprint.log?

**Comment by TheToxicant** [comment]
I did not have polling enabled and the IP connection errors would display even if the plugin said  "Tasmota device responded and is configured properly." and scrolling through the OctoPrint logs you can see where I was having the connectivity issues and fixed them then started/finished printing and then updated to the RC for the plug in. I've attached the OctoPrint log but scrolling through it I don't see anything that jumps out at me other than my now fixed Wi-Fi connection. There are also two short Tasmota debug logs form the 15/16 that only just display a brief connection issue.
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6332841/octoprint.log)

**Comment by TheToxicant** [comment]
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6332908/plugin_tasmota_debug.log)
Here is an updated debug log the last one i supplied did not have the debug feature enabled on it and this show the switch toggling. i just noticed that i forgot to click save aver clicking the debug box

**Comment by jneilliii** [comment]
Could you switch the plugin release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted to see if it makes any difference? We possibly may need to try increasing the Request Timeout in the plugin's settings with this version as well to see if it makes a difference on pulling that sensor data.

**Comment by TheToxicant** [comment]
Yeah no problem

**Comment by TheToxicant** [comment]
still displaying undefined for the sensor readings.

**Comment by jneilliii** [comment]
Interesting, that makes me believe there may be an issue with the bindings used in the pop-up. Do you have any errors in the developer console of your browser (typically F12 on your keyboard will open it) and see if there are any errors on initial page load?

**Comment by TheToxicant** [comment]
I had the following errors

 
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.50.5/static/vendor/font-awesome-5.15.1/webfonts/fa-solid-900.woff?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.50.5/static/vendor/font-awesome-5.15.1/webfonts/fa-regular-400.woff2?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.50.5/static/vendor/font-awesome-5.15.1/webfonts/fa-solid-900.woff2?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.50.5/static/vendor/font-awesome-5.15.1/webfonts/fa-brands-400.woff?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.50.5/static/vendor/font-awesome-5.15.1/webfonts/fa-brands-400.woff2?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/#tab_plugin_tasmota:1 The resource http://192.168.50.5/static/vendor/font-awesome-5.15.1/webfonts/fa-regular-400.woff?v=5.15.1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/disable-console.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

packed_core.js?22357642:350 Terminal: Detected slow client (needed 629ms for processing new log data), disabling fancy terminal functionality

packed_core.js?22357642:350 Terminal: Detected slow client (needed 616ms for processing new log data), disabling fancy terminal functionality

**Comment by TheToxicant** [comment]
This error seems to be coming in and out.
packed_core.js?22357642:350 Terminal: Detected slow client (needed 616ms for processing new log data), disabling fancy terminal functionality
Terminal: Client speed recovered, enabling fancy terminal functionality

**Comment by jneilliii** [comment]
Nope, no major errors there. That terminal message is in core OctoPrint and is pretty common. I know there is work being done on a lot of the core components right now to hopefully improve that. I'll try to debug this over the weekend as I have your exact setup with DHT11, just have to get it powered back up.

**Comment by jneilliii** [comment]
@TheToxicant could you enable status polling in the plugin settings and see if once the first polling interval has passed that it changes the pop-up or not?

**Comment by TheToxicant** [comment]
> @TheToxicant could you enable status polling in the plugin settings and see if once the first polling interval has passed that it changes the pop-up or not? 

Yeah I can do that. I'm in shift work so I won't be able to get to it tomorrow.

**Comment by TheToxicant** [comment]
It is enabled with 5 min polling interval.

**Comment by jneilliii** [comment]
I think I may have this issue resolved with the above commit. If you could test the 1.1.0rc2 release and verify that would be great. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. If you are already on that release channel, you should get an update notice once your local cache times out, or if you force a check.

**Comment by TheToxicant** [comment]
As soon as my prints finish I'll force an update.

**Comment by TheToxicant** [comment]
That seems to have fixed it the pop up window is now displaying values.

**Comment by jneilliii** [comment]
Awesome, thanks for confirming.
