### ISSUE TITLE
Setting this up Killed MQTT communications in the Sonoff Tasmota device

### ISSUE THREAD

**Issue by ZhuDaHai** [jneilliii/OctoPrint-Tasmota#145]
This has not been my week for MQTT...won't bore you with details

I have a sonoff 2sx module running release-sonoff 6.5.0 and it is configured with MQTT to talk to my Home Assistant server for monitoring and control.

Install this module in OctoPi and everything installed in OctoPi is current and up to date.
OctoPrint 1.5.3 
Python 2.7.16 
OctoPi 0.17.0

Installed this plugin: OctoPrint-Tasmota v1.0.3

When I entered the IP address, Username and Password for the Sonoff switch, and clicked 'Verify' I got this message:
![OctoPrint-Tasmota 2](https://user-images.githubusercontent.com/14084743/115379408-158c0980-a204-11eb-9004-eea137e5868b.PNG)

Clicked OK to let it do its thing:
![OctoPrint-Tasmota 3](https://user-images.githubusercontent.com/14084743/115379597-41a78a80-a204-11eb-98f0-f88000cd8b08.PNG)

However, now at this point, that switch no longer responds to MQTT Commands from my Home Assistant Server. 
It no longer knows the state of the switch, and when I try to turn it off or on, it either doesn't work or does it and then switches it back after a few seconds.

If I restore a backup of that Sonoff Tasmota switch, MQTT works properly again. But of course, OctoPrint-Tasmota does not as whatever that 'SetOption26' ON did is not longer set from the restore.

Ideas?
Thanks!

**Comment by jneilliii** [comment]
SetOption26 means that if you send the command power1 on it will respond with power1 on, if you send command power on it will return power1 on. 

![image](https://user-images.githubusercontent.com/5249455/115407345-f10d3e80-a1bd-11eb-8296-01276259c2ce.png)

You have two options...modify your HA to utilize power1 status instead of power or change SetOption26 off and then remove the index from the device's settings in the plugin.

**Comment by ZhuDaHai** [comment]
More Info. 
I ran MQTT Explorer and noted that the Sonoff switch is no longer sending MQTT Events events after updating SetOption26 to ON. 

So Home Assistant Sends a Power=OFF MQTT command to the Sonoff switch, which powers it off, but never gets a response back. So the UI resets the switch ICON back to ON. 

Clicking on the Switch Icon in Home Assistant to turn it off does nothing, because its already off. And because its not getting a response from the Sonoff switch, it resets the Switch Icon back to ON again.

And like I said, pressing the physical button on the Sonoff switch to turn it off an on sending nothing to the Home Assistant MQTT Server to tell it its current state.

**Comment by ZhuDaHai** [comment]
OK. Another update. I think I see what's happening.

Before setting SetOption26 to ON. On/Off MQTT messages where sent from the Sonoff Switch as:
`cmnd/sonoff-a4/POWER=ON/OFF`

Now, after SetOption26 is set to ON. These messages are now being set from the Sonoff Switch as:
`stat/sonoff-a4/POWER1=ON/OFF`

There does not appear to be any way to set the Index to 0 in the Tasmota Editor with the current version.
So I will see if I can change my code in Home Assistant to look for 'stat' messages instead of 'cmnd'

**Comment by jneilliii** [comment]
Yeah, you should use the stat topic to know current state rather than depend on intercepting commands being sent to the device. However, you don't have to set the index to 0, you just delete it like below and run the command `SetOption26 off` in your tasmota console.

![image](https://user-images.githubusercontent.com/5249455/115411474-80682100-a1c1-11eb-98ca-bbafebf76b45.png)

**Comment by jneilliii** [comment]
just don't use the verify button...

**Comment by ZhuDaHai** [comment]
I'll constantly forget to NOT click on 'Verify' :)
So I updated my Home Assistant config to look for POWER1 stat instead of POWER, and of course: It Worked!
I know this was in your instructions on GitHub or in another Issue I found here. I read it, I just didn't get it. 
"A mind is a terrible thing to..." Dang, can't remember the rest of that....
Sorry for wasting your time.
Cheers!
