### ISSUE TITLE
Icon spins and Tasmota switch turns off without the 30 second delay

### ISSUE THREAD

**Issue by ZhuDaHai** [jneilliii/OctoPrint-Tasmota#146]
I don't know what the heck is going on. I tested this yesterday and it worked flawlessly.
Today, the Bolt Icon for OctoPrint-Tasmota just spins and when I click on it to shut it down, it warns appropriately, and when I click on the button to shutdown, it turns off the switch Immediately instead of waiting 30 seconds.
What have I screwed up now????

![Tasmotta A4](https://user-images.githubusercontent.com/14084743/115488377-f38a9980-a28c-11eb-8374-f8cf00892892.PNG)

I even clicked on the Verify button and it came back that everything was OK.

**Comment by ZhuDaHai** [comment]
Here's more clues:
If I click on the spinning Bolt to shut down, but select cancel instead. Then the bolt stops spinning.
Clicking on it again and selecting 'Proceed' to shutdown and everything works correctly:
5 seconds: sudo shutdown now
30 seconds: tamotta switches off

**Comment by ZhuDaHai** [comment]
Another Clue!
I installed this plugin on another OctoPi server and it behaved badly: instant shutdown. However its icon did not spin...oddly
But again, if I click on the bolt, select 'cancel', then click on the bolt again, and 'Proceed' it works correctly:
5 seconds: sudo shutdown now
30 seconds: tamotta switches off

Same model of Sonoff Switch S26, and same Tasmotta version 6.5.0

Hope this helps

**Comment by jneilliii** [comment]
Probably off on disconnect monitoring with a backpowered printer. That's been reported before. To be sure though you would have to enable debug logging in the plugins settings, restart octoprint, and then try it again. Once it fails, or acts unexpectedly grab the plugin_tasmota_debug.log file and share it by dragging it here into a comment.

**Comment by ZhuDaHai** [comment]
Attached are the tasmota plugin log and the octoprint log.
Here's what I did and what happended:

First Attempt: 
Green Bolt NOT spinning. 
Clicked on Bolt to shutdown and selected 'Proceed'. 
Bolt started spinning. 
Shut down properly with 'sudo shutdown now' and 30second delay before powering off switch

Second Attempt:
Green Bolt NOT spinning.
Clicked on Bolt to shutdown and selected 'Proceed'
Shut down Immediately without waiting 30 seconds.

Third Attempt:
Green Bolt AND Spinning.
Clicked on Bolt and selected 'Cancel'
Bolt stopped spinning
Clicked on Bolt again and selected 'Proceed'
Shut down Immediately without waiting 30 seconds.

Hope this helps

[octoprint (3).log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6348224/octoprint.3.log)

[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6348226/plugin_tasmota_debug.log)

**Comment by ZhuDaHai** [comment]
P.S. I noted all those errors in the plugin_tasmota_debug.log:
`ERROR: Invalid ip or unknown error connecting to sonoff-A4.asgard.`
So I replaced the URL with its IP address: 172.27.3.14
Both OctoPi and this sonoff switch are on the same subnet.

Tried it again:
Bolt was GREY
Clicked on Bolt, it turned Green
Clicked on Bolt again, and selected 'Proceed'. Bolt started spinning
Shut down immediately without waiting 30 seconds.

Here's the plugin_tasmota_debug.log file

[plugin_tasmota_debug (2).txt](https://github.com/jneilliii/OctoPrint-Tasmota/files/6348306/plugin_tasmota_debug.2.txt)

**Comment by jneilliii** [comment]
could you try with delay of 5 for the system command as documented in the examples?

https://github.com/jneilliii/OctoPrint-Tasmota#examples

**Comment by jneilliii** [comment]
and disable disconnect event monitoring...that is causing it to double power off I think.

**Comment by ZhuDaHai** [comment]
Here are my test results, and the octoprint-tasmota log file

[plugin_tasmota_debug (1).log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6355050/plugin_tasmota_debug.1.log)

Made those change (pic posted below)

Tries 1, 2: (Worked Properly)
Powered Switch ON
Bolt turned Green
Click on Bolt, clicked on Proceed
Worked properly: Pi Shutdown and switch turned off after 30 seconds

Try 3: (Not working Properly)
Powered Switch ON
Bolt is RED (should be Green)
Clicked on Bolt, then it turned Green
Clicked on Bolt, clicked on Proceed
Shut down Pi and shut down switch after 30 seconds

Try 4: Worked Properly (same as try 1 & 2)

Try 5: Worked Properly
Powered Switch ON
Bolt is Green
Clicked on Bolt
Clicked on Cancel
Clicked on Bolt
Clicked on Proceed
Shut down Pi and shut down switch after 30 seconds

Tasmota Editor: Off on Disconnect (CHECKED)
Tasmota Editor: Close, Save

Try 6: (FAILED)
Powered Switch ON
Bolt is Green
Clicked on Bolt
Clicked on Proceed
Bolt started Spinning
Powered Switch of Immediately

Tasmota Editor: Unchecked 'Off on Disconnect'
Tasmota Editor: Changed IP to 'sonoff-A4.asgard' 
Tasmota Editor: Clicked on Verify, verified OK
Tasmota Editor: Close, Save

Try 7: (small issue)
Powered Switch ON
Bolt is Grey (small issue)
Clicked on Bolt
Bolt Turned GReen
Clicked on Bolt
Clicked on Proceed
Shutdown Pi and shut down switch after 30 seconds

Try 8: (small issue)
Powered Switch ON
Bolt is GReen
Click on Bolt, Bolt starts spinning (small issue)
Click on Proceed
Shutdown Pi and shut down switch after 30 seconds

Try 9: (small issue)
Powered Switch On
Bolt is RED (small issue)
Clicked on Bolt
Bolt Spins
Bolted turns Green
Clicked on Bolt
Clicked on Proceed
Shutdown Pi and shut down switch after 30 seconds

So, it doesn't work properly with 'Off on Disconnect' Checked.
And it has small issues with using a Domain Name instead of an IP address for the Switch

![OctoPiTas 1](https://user-images.githubusercontent.com/14084743/115646539-eafd9600-a354-11eb-8a24-40449bf1a92b.PNG)

**Comment by ZhuDaHai** [comment]
P.S. I really would like (need) for 'Off on Disconnect' to work - for safety reasons.

If OctoPi becomes disconnected from the printer (communications error, firmware freezes, etc) I need to have it shut down the printer. 

Without OctoPrint knowing what the printer is actually doing ( it could be holding the heaters on, or overheating them, or a smoldering short on the mainboard), there is no way to know if its operating safely and therefore needs to turn the power off.

I originally had this set up via MQTT on a Home Assistant server to monitor these events and turn off the switch on an Error or Disconnect event. But MQTT and Home Assistant has always been flaky, and now its even worse. After dozens finger pointing on their forum and lack of any progress towards a fix (an NO response to my BUG report on MQTT Github site), I've given up on getting that to work reliably. 

Then I saw this plugin and realized I could bypass MQTT, Home Assistant, and all that BS and talk directly to the Switch. Yay!

So one little issue left (Off on Disconnect) and I can once again run multi day prints without having to worry (too much) about the printer running away and causing chaos, or worry about Home Assistant and its crappy MQTT Broker deciding to just turn the switch off because it felt like it.

So, thanks for all your help. Hope we can get this last issue resolved and let me know if you need anything else from me.

**Comment by jneilliii** [comment]
Wild guess, your pi is powered by your printer's PSU? I might be able to go through the disconnect logic again in the future.

**Comment by jneilliii** [comment]
It just dawned on me. What if you disable auto disconnect and enable off on disconnect?

**Comment by ZhuDaHai** [comment]
Yes, Pi is inside the Printer and powered by its PSU. So it needs to shutdown first before powering off the switch to the printer.

I disabled 'Auto Disconnect' and enabled 'Off on Disconnect' and tested it 3x on 2 printers (6 times total):

It shut down the Pi and then powered off the switch 30 seconds later every time! YAY!

The Bolt icon still Occasionally spins after clicking on 'Proceed' to power off.

I then tried Disconnecting from the printers (both with the Disconnect button in OctoPi and by unplugging the USB Cable.
3x times on each printer (6x total)

Everything worked properly with it shuting down the Pi and then powering off the Switch 30 seconds later.

Occasionally, the Bolt would come up in the 'OFF' state when I powered everything on (like before), but clicking on it reset it to the ON color (so this is pretty minor)

So, YAY! I'm a happy camper! 
It shuts down everything properly under the correct conditions and it seems to handle domain names with just occasional spinning or wrong icon state (but it does not affect safety operations)

P.S. I think the Bolt Icon coming up in the wrong state (OFF when it was just turned on), has to do with how the OctoPi page refreshes itself:

If it automatically refreshes because it was off for a short time, or I click 'Attempt to Reconnect' and it succeeds, then it just reloads the main page and not the header bar. So the Bolt stays in the OFF color.

But if I hit the Browsers, refresh button to reload the entire page, then it refreshes the Bolt Icon as well and it changes to ON.

But even all this doesn't affect safety. Even if the Bolt Icon is showing OFF while OctoPi is actually ON, its still shuts down properly if I disconnect the OctoPi from the printer.

Hope this makes sense and not too much rambling.

Thank you! Thank you! Thank you!

If you decide to look into the conflict between 'Auto Disconnect' and 'Off on Disconnect', let me know. Happy to test it.

You can close this if you wish.
