### ISSUE TITLE
Make waiting for timelapse to complete prior to power off optional

### ISSUE THREAD

**Issue by Panoru84** [jneilliii/OctoPrint-Tasmota#147]
Hello,

I'm using a Tasmota plug to power my 3D-Printer.
But only the printer, while my OctoPi is running the whole time.
Now I printed for 14 hours and rendering the timelapse will take some more hours.
Unfortunately I cannot find any way to configure the printer plug to switch off after the idle mode is reached based on temperature only.

My log says:
`[2021-04-26 12:41:06,022] DEBUG: Waiting for timelapse before shutting off power...`

Thanks for your help and your great work, I really appreciate it a lot!

**Comment by jneilliii** [comment]
I think I may have this issue resolved with the above commit. If you could test the 1.1.0rc1 release and verify that would be great. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. If you are already on that release channel, you should get an update notice once your local cache times out, or if you force a check.
