### ISSUE TITLE
Assing a label and Icon.

### ISSUE THREAD

**Issue by asiersan** [jneilliii/OctoPrint-Tasmota#15]
It would be grat if could be posible to asing a name and an icon for diferent things like lights

**Comment by jneilliii** [comment]
I actually have done something like that in my tasmotamqtt plugin. I could definitely incorporate that into this version on my next update.

**Comment by jneilliii** [comment]
Just released version 0.5.0 to allow setting the title attribute (shows on mouseover) and the icon class.

**Comment by asiersan** [comment]
Runs perfect. Thanks
