### ISSUE TITLE
Status unknown for XXX.XXX.XXX.XXX. Double check IP Address\Hostname in Tasmota Settings.

### ISSUE THREAD

**Issue by pinguinone** [jneilliii/OctoPrint-Tasmota#152]
Hello,
I used your plugin with a [tasmota device](https://www.delock.de/produkte/G_11827/merkmale.html?setLanguage=it) and often it loose the connection with the device and in the upper part shows me a thunder with a question mark.
Octoprint show a alert with this text:

`Status unknown for XXX.XXX.XXX.XXX. Double check IP Address\Hostname in Tasmota Settings.`

Obiouvsly instead of XXX.XXX.XXX.XXX there is my IP Address.
I double check the addess in the Tasmota settings and they are correct. If I click the thunder the connection resume and it reconnect with out any problem. After a while the problem reappear. How can I solve that?

**Comment by jneilliii** [comment]
Enable debug logging, restart octoprint, share screenshots of your settings and the resulting plugin_tasmota_debug.log file from octoprint's lighting section after you ser this. Also, double check the developer tools (F12 key on your keyboard) console tab in your browser for errors.

**Comment by pinguinone** [comment]
Hello,
thanks for answer. I did what you asked me. No error on developer tools. Attached you'll find the debug log of Tasmota
[plugin_tasmota_debug (1).log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6506622/plugin_tasmota_debug.1.log)

**Comment by jneilliii** [comment]
So looking at your log it appears the device is not responding quick enough possibly when changing state. If you switch to the Release Candidate in OctoPrint's Software Update settings for the plugin's release channel and install there is configurable option to increase that timeout. Can you try that version and report back if increasing the timeout makes a difference?

![image](https://user-images.githubusercontent.com/5249455/118820751-903c5900-b884-11eb-8d92-79b8b1173037.png)

**Comment by pinguinone** [comment]
Hello,
thanks for your answer. I try but with not success. I do this thing:

1. Go to Octoprint >>> Software Update
2. Choose Maintenance RC
3. Reload
4. Click on Check for updates but everything is updated
5. I go to the Tasmota plugin but your setttings does not appear
6. I back to Octoprint >>> Software Update
7. Choose Devel RCs
8. Reload
9. Click on Check for updates but everything is updated
10. I go to the Tasmota plugin but your setttings does not appear
11. I unistall the plugin
12. I Install the plugin
13. I go to the Tasmota plugin but your setttings does not appear

Where am I wrong?

**Comment by jneilliii** [comment]
oh are you on an older version of OctoPrint? I was referring to this in Software Update settings....

![image](https://user-images.githubusercontent.com/5249455/118997651-d366fc80-b956-11eb-887f-eff5891131c6.png)

That will only be available in version 1.5.0+ I think. In any case, you can manually install by copying/pasting this URL in Plugin Manager > Get More > ...from URL

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/refs/tags/1.0.4rc4.zip
```

**Comment by pinguinone** [comment]
I think I figure out.
Well I have the latest version of Octoprint (greater than 1.5.0) but I didn't see the list of upgrade for plug in. Afer a long search it seems that is a bug that occurs if it's installed the older version of Canvas and Palette plug-in from Mosaic. I uninstall them and...boom all the plug in update are present in front of me.
I upgraded everything and put your as release candidate as you suggested and put on 30 seconds this parameter....after I try a print and....so far so good.

**Comment by lsaranto** [comment]
I'll try this too.
