### ISSUE TITLE
GCode Shutdown not Working

### ISSUE THREAD

**Issue by Bupher** [jneilliii/OctoPrint-Tasmota#153]
I have a fresh install of octoprint with a new tasmota flash outlet. The icon control works fine, but I cannot control the power with the M80/81 gcode commands, to shut it down at the end of the print. I have idle enabled, but I would rather it shut down right away anyways.

I tried running M81 192.168.1.39 in the terminal to no avail, it just says OK with no errors or acknowledgment. I don't have a relay number after it in the plugin settings and it works fine, it actually doesn't work if I do have a relay number after it.
The outlet works fine otherwise (but I have no MQTT integration if that matters).
The printer is an Ender 3 with the 4.2.2 board, so I need to run The Creality temp 2.x fix plugin.
The log doesn't appear to acknowledge me using the M81 command at all.

I attached the log as well as my settings for tasmota and the terminal window.

[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6713017/plugin_tasmota_debug.log)
![Tasmota 1](https://user-images.githubusercontent.com/17689133/123357991-9fc05900-d538-11eb-914f-176e31e36084.PNG)
![Tasmota 2](https://user-images.githubusercontent.com/17689133/123357994-9fc05900-d538-11eb-8ca6-d1b1f411d903.PNG)

**Comment by jneilliii** [comment]
Increase your delay for the gcode off command. It needs to be a value that is longer than it takes for the print to complete before sending the command from octoprint's queue.

**Comment by Bupher** [comment]
I tried that, and the printer still does not shut down with G-code commands or immediately after a print has completed. It always waits until the idle timeout is reached and then shuts down.

![image](https://user-images.githubusercontent.com/17689133/124139667-d248e500-da55-11eb-8501-2366e121a732.png)
![image](https://user-images.githubusercontent.com/17689133/124139756-e987d280-da55-11eb-8605-0140769d0e61.png)

**Comment by jneilliii** [comment]
Then tou ned tp enable debug logging in the plugin settings, restart octoprint and then try again. Them when it doesn't work supply your plugin_tasmota_debug.log done from the logging section of octoprint.

**Comment by Bupher** [comment]
I believe I had already turned it on, so I have a log already.
I see no mention of the gcode commands in the logs, but I have M81 192.168.1.39 in the "After print completes" gcode script.
It did power off on M112, but I assume that was error detection.

![image](https://user-images.githubusercontent.com/17689133/124165691-15b04d00-da70-11eb-830b-1f1b6f9b0606.png)

[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6749860/plugin_tasmota_debug.log)

**Comment by jneilliii** [comment]
Ah, this might be a bug with not having an index actually. Did you use the verify button and enable SetOption26 when prompted to do so? If so then index needs to be 1 and your gcode needs to be `M81 192.168.1.39 1`.

**Comment by Bupher** [comment]
I have not done either of those things, should I do that? I don't have an index set in the plugs UI afaik and the lighting bolt doesn't fork if I put in an index.

**Comment by jneilliii** [comment]
I would try that to see if it resolves the issue. Set index to 1 and press verify, say ok/yes to set the option ans adjust the gcode.

**Comment by Bupher** [comment]
Yep, that fixes it. I looked for an explanation of the index, and couldn't find one, or anything about the verify button the page prior to this,
