### ISSUE TITLE
Off with Idle Not  functioning

### ISSUE THREAD

**Issue by dredvard** [jneilliii/OctoPrint-Tasmota#154]
I have the Off with idle set to 1 minute, and I also have the disconnect monitoring.  But the printer doesnt't appear to shut off  I have On with Connect operating correctly and it works from the lightning icon.    The printer state is even Offline.

**Comment by jneilliii** [comment]
please enable debug logging, and restart octoprint. once it's back up let it go to the idle time and if it doesn't happen share screenshots of your settings and the file plugin_tasmota_debug.log from OctoPrint's logging section in settings.

**Comment by dredvard** [comment]
Don't understand what the difference.  I litterally did nothing different... walked away for 2hrs and suddenly it started working.  It now starts shutting down in 1 minute.  Even when I'm present.  Anyway, thanks!  Love the plugin!!
