### ISSUE TITLE
Status unknown for xxx.xxx.xxx.xxx. Double check IP Address\Hostname in Tasmota Settings.

### ISSUE THREAD

**Issue by augustozanellato** [jneilliii/OctoPrint-Tasmota#155]
Already tried installing the RC version but still getting the same error, checking the debug logs looks like the connection with tasmota itself is working fine but there's an exception within the plugin code
```
[2021-07-07 08:50:59,446] ERROR: Invalid ip or unknown error connecting to xxx.xxx.xxx.xxx.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 537, in check_status
    [plugip, plugidx, today.isoformat(' '), c, p, t, v])
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.
```

**Comment by augustozanellato** [comment]
Now it randomly started working, leaving the issue open in case you want to still troubleshoot this issue

**Comment by jneilliii** [comment]
interesting, possibly a race condition. does your tasmota have a sensor attached or a POW R2 or other power monitoring device?

**Comment by augustozanellato** [comment]
> interesting, possibly a race condition. does your tasmota have a sensor attached or a POW R2 or other power monitoring device?

Yup, it’s a sonoff dual r3 so two channels each independently power monitored

**Comment by jneilliii** [comment]
could you enable polling if not already using it and let it run for a bit and then share your debug log here please? I'd like to see if that error is consistently happening or in a specific combination of timings. I only have a single relay device to test with and while developing that part of the plugin for power monitoring.

**Comment by augustozanellato** [comment]
Here it is (be aware it's a 10mb text file), just edited out some personal infos. Pooling was set @ 1 minute because I often trigger the sonoff using mqtt.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6783646/plugin_tasmota_debug.2.log)

**Comment by jneilliii** [comment]
I think I might have an idea of the cause of the issue. With a single relay device the values returned for Power, Current, etc. is a single value. In your response it comes back as a list of values. I didn't think to account for that. I'll have an update shortly in the release candidate channel for you to test for me.

**Comment by jneilliii** [comment]
might be fixed with the above commit and included with 1.0.4rc5 version. Just change the release candidate setting for the plugin in OctoPrint's Software Update settings to Release Candidate. Let me know how it turns out.

**Comment by augustozanellato** [comment]
Yup, looks like it's working fine now, thanks for the quick update!

**Comment by jneilliii** [comment]
Great news.
