### ISSUE TITLE
Better graphing tab

### ISSUE THREAD

**Issue by augustozanellato** [jneilliii/OctoPrint-Tasmota#156]
Hi, just looked at the chart in the Tasmota tab in octoprint and it's not very readable imho, for example the single axis shared for all data series makes the cost series useless I disable the power series each time.
Would you mind if I try making it nicer? (I have some experience with frontend charts albeit not with plotly.js)

**Comment by jneilliii** [comment]
Always open to improvements. I don't personally use the graphing capabilities yet as I'm still working on building my dry box. If you'd like to submit a PR, please base it on the current RC branch and submit against it.
