### ISSUE TITLE
Auto connect not working without manual refresh

### ISSUE THREAD

**Issue by augustozanellato** [jneilliii/OctoPrint-Tasmota#157]
Having some issues with auto connect, looks like it tries to connect but it doesn't re-scan for serial ports before doing so. 
If I just power on the printer I get `No more candidates to test, and no working port/baudrate combination detected.` after the set delay. Could be due to the fact that when it tries to connect there are no serial ports detected in the web gui dropdown. 
Now I have an exaggeratedly long power on delay of 20 secs and it doesn't work, if I manually power on the printer, refresh ports and connect I just need to wait 2 secs in order for the port to appear in the dropdown.

**Comment by jneilliii** [comment]
Try setting the port and baudrate and saving the settings. I'm pretty sure that I use those during the connection command.

**Comment by augustozanellato** [comment]
> Try setting the port and baudrate and saving the settings. I'm pretty sure that I use those during the connection command.

Yup that was it, thanks!
