### ISSUE TITLE
Feature Request- Icon Color/Status

### ISSUE THREAD

**Issue by TheToxicant** [jneilliii/OctoPrint-Tasmota#166]
For one of my printers i am just using this plug in to monitor just temp/humidity for where the printer is located as a result because i don't have a "relay" assigned it and it just displays an unknown state icon while still showing temp/humidity readings . Is there any way for a future update to add a "sensor only" option so the unknown stats isn't displayed?

**Comment by jneilliii** [comment]
I'll see how best to implement something like that. It's kind of tricky because something has to be there for the hover. Could just be a matter of removing click events and hide the state text.

**Comment by jneilliii** [comment]
I've added a Hide setting that will prevent the button from being clickable. I do not know if this will resolve this request though. If you don't mind changing the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted and let me know that would be great. A screenshot of what you see would be helpful too as I don't have a device without a relay so state is always present.

**Comment by TheToxicant** [comment]
Sorry for the long delay just got back from a deployment but here is what i see


> I've added a Hide setting that will prevent the button from being clickable. I do not know if this will resolve this request though. If you don't mind changing the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted and let me know that would be great. A screenshot of what you see would be helpful too as I don't have a device without a relay so state is always present.

![Plug in](https://user-images.githubusercontent.com/77461994/163723599-6c73935a-1325-45cc-aff8-564eed0fd216.png)
