### ISSUE TITLE
Tasmota v10 Plugin dont works

### ISSUE THREAD

**Issue by PhilippeGalid** [jneilliii/OctoPrint-Tasmota#167]
Hi sinze i update my Sonoff Wlan Power Plug with the Tasmota Firmware v 10 your Plugin dont works in Octoprint after the Print when the heat go down to 50 c the Power dont shot down,befor the Firmware update all works fine. Can you please fix your Plugin for the Firmware v10. And thank you for you hard work. Can you please tell me how can i fix it,Thanks ?

**Comment by jneilliii** [comment]
Can you please enable debug logging for the plugin, restart octoprint and then share the octoprint and tasmota debug log here?

**Comment by PhilippeGalid** [comment]
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/7643716/octoprint.log
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/7643717/plugin_tasmota_debug.log)
)

**Comment by PhilippeGalid** [comment]
![Bildschirmfoto 2021-12-02 um 17 56 22](https://user-images.githubusercontent.com/34857501/144467504-a0d182aa-3db1-433d-bda1-40713c340089.png)

**Comment by PhilippeGalid** [comment]
The Plugin is green but after the print when the temp go down to under 50c the Power Plug dont switch off, befor the Update to Firmware v10 there was no problems. What do you think what is the problem ? Maybe you have to update the Plugin

**Comment by jneilliii** [comment]
Ah, I see the issue. In the individual devices setting you need to check the box for off on idle.

**Comment by PhilippeGalid** [comment]
Thanks you for your support it works now,and thank you for your hard work to make this super Plugin

**Comment by BlackBird11** [comment]
hi @jneilliii, i am having somewhat the same issue and just can't figure out why it won't shutoff the system when in idle

attached you can find screenshots. sadly couldn't figure how to only debug log the plugin or tasmota, only the whole octoprint log (screenshot attached, it wouldn't make new/updated tasmota log files)

thank you in advance!


![o4](https://user-images.githubusercontent.com/49521039/151449873-e47b283f-45bd-44f9-937f-2b5921104170.png)
![o3](https://user-images.githubusercontent.com/49521039/151449876-ebc88e7e-161b-4a83-911e-7c9ad0ba10ac.png)
![o2](https://user-images.githubusercontent.com/49521039/151449878-561f3768-9c37-4afc-a230-5f01343425c9.png)
![o1](https://user-images.githubusercontent.com/49521039/151449881-c475c662-1f23-4d5e-ab25-22e58f032ca3.png)

**Comment by BlackBird11** [comment]
> Ah, I see the issue. In the individual devices setting you need to check the box for off on idle.

thanks! had the same issue on my end
