### ISSUE TITLE
Status Polling broken?

### ISSUE THREAD

**Issue by TheDiNi74** [jneilliii/OctoPrint-Tasmota#169]
Tasmota (1.1.0)
OctoPrint 1.7.2 Python 3.7.3 OctoPi 0.18.0

Seems Status Polling from Tasmota plugin (I am using Sonoff RF with tasmota ) broken.
Tested Tasmota 8.5..failure..after this update to 10..
Tested Tasmota Tasmota 10.1.0 ... failure

tasmota config: Web-Log Level (Info)
http api enabled

Don't know, when this problem started.

When turn Tasmota Device off, over "external" Switch with.alexa oder rf or webinterface. The Tasomota Plugin does not change the status from green to red ...

checked - Enable polling of status.
Tryed 1 min or other .. min..

May be broken with an update of plugin in the past?

Sorry.. native language german ;.)

**Comment by jneilliii** [comment]
After enabling the option have you restarted OctoPrint?

**Comment by TheDiNi74** [comment]
Okay, after reboot pi polling works. 'to easy'
:-)

Wish: Tooltip/Mouse over to inform the users: When chaning this option, please restart the... ;.) ?
