### ISSUE TITLE
Read tasmota sensors.

### ISSUE THREAD

**Issue by asiersan** [jneilliii/OctoPrint-Tasmota#17]
Qould be posible to read tasmota sensors, like temperature an humisity and show them in navbar, like enclosure pluging?

**Comment by jneilliii** [comment]
I assume it would be possible, but because I don't have such a device I'm not 100% sure. I'll look initio it.

**Comment by jneilliii** [comment]
@asiersan, can you provide the result of going to the following url?

http://<ip of your tasmota>/cm?cmnd=SetOption8

**Comment by jneilliii** [comment]
Also, if possible the results of the following url as well.

http://<ip of your tasmota>/cm?cmnd=Status%200

**Comment by asiersan** [comment]
http://<ip of your tasmota>/cm?cmnd=SetOption8
{"SetOption8":"OFF"}

**Comment by asiersan** [comment]
http://<ip of your tasmota>/cm?cmnd=Status%200
`{"Status":{"Module":1,"FriendlyName":"Impresora","Topic":"sonoff","ButtonTopic":"0","Power":2,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","Uptime":0,"Sleep":0,"BootCount":43,"SaveCount":268,"SaveAddress":"FB000"},"StatusFWR":{"Version":"5.11.1","BuildDateTime":"2018-01-07T21:51:09","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"MYSID","SSId2":"SSIDCONFIG","TelePeriod":300,"SetOption":"00000001"},"StatusMEM":{"ProgramSize":484,"Free":516,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3},"StatusNET":{"Hostname":"IMPRESORA","IPAddress":"192.168.1.14","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"643:10","Webserver":2,"WifiConfig":2},"StatusTIM":{"UTC":"Fri Jan 12 18:20:15 2018","Local":"Fri Jan 12 19:20:15 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1},"StatusSNS":{"Time":"2018-01-12T19:20:15","DHT11":{"Temperature":17.0,"Humidity":58.0},"TempUnit":"C"},"StatusSTS":{"Time":"2018-01-12T19:20:15","Uptime":0,"Vcc":3.161,"POWER1":"OFF","POWER2":"ON","Wifi":{"AP":1,"SSId":"MYSIDD","RSSI":86,"APMac":"MAC"}}}`

**Comment by asiersan** [comment]
In the second command there is a section:

"StatusSNS":{"Time":"2018-01-12T19:20:15","DHT11":{"Temperature":17.0,"Humidity":58.0},"TempUnit":"C"},

**Comment by asiersan** [comment]
And it wold be grat to add an offset to temp or humidity because this cheap sensors.....

**Comment by mentlergy** [comment]
It is easier to use the cmnd=Status%2010 command, because it returns only the sensor information in JSON.
Like this: {"idx":2,"nvalue":0,"svalue":"34.0;11.0;2","StatusSNS":{"Time":"2018-02-22T14:52:03","DHT11":{"Temperature":34.0,"Humidity":11.0},"TempUnit":"C"}}

For the user interface it would be ideal to have variables for the names of the sensor values to configure the output.
In this case Temperature and Humidity could be variables from the JSON and we could configure the output format just like this: "Hőmérséklet: $DHT11_Temperature $DHT11_TempUnit \n Légnedvesség: $DHT11_Humidity %"
He words Hőmérséklet and Légnedvesség are temperature and humidity in hungarian.

**Comment by jneilliii** [comment]
Hey @asiersan  and @mentlergy, I know it's been a long time since this request was opened and I finally got around to getting a DHT11 connected to a sonoff device and can start working on this.  I don't foresee it taking too long, but wanted to see if either of your have an energy monitoring capable device that returns anything with `http://<ip of your tasmota>/cm?cmnd=Status 8`? That returns the same temp/humidity info for me, but I'm trying to find examples of energy data to also incorporate that into the next version.  The plan is to log the data and then display last polling result in sidebar and add a tab that graphs the data over time, similar to the TPLink-Smartplug plugin does now.

![screenshot](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/raw/master/screenshot_tab.png)

**Comment by steviehs** [comment]
{"StatusSNS":{"Time":"2019-12-12T00:53:02","ENERGY":{"TotalStartTime":"2019-04-07T18:46:49","Total":0.219,"Yesterday":0.025,"Today":0.194,"Power":205,"ApparentPower":356,"ReactivePower":290,"Factor":0.58,"Voltage":230,"Current":1.544}}}

That's what you want? Would even be great, if the energy consumption per print could be logged. Great work btw, just installed and works fine!

**Comment by jneilliii** [comment]
Thanks. I have a relatively working version that should in theory show sensor and energy data. Install using the url below in plugin manager and enable polling. Upon the first poll the data should show in a pop up when you hover over the icon. It will also start storing the data in a database for future graphing once I get around to integrating that. 

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.9.zip

**Comment by steviehs** [comment]
Just tested it, but the plugin complains it could not read the device status on this (doublechecked) IP. The old version works fine again. Should I produce some logs?

**Comment by jneilliii** [comment]
Yes please. Would need both octoprint log and the plugin's debug log.

**Comment by jneilliii** [comment]
So I just did an upgrade and remembered I may have changed some logic for single relay devices.  If you make the index blank and make sure single relay device is unchecked does it work?  It does for me and I was getting the same error. Or on your Tasmota device you can run the command `SetOption26 1` and leave the index as 1.

**Comment by steviehs** [comment]
Yes! This was it. removed index and single relay is unchecked. Now I see everything is fine and a lot of data in the debug log. This looks great!

**Comment by jneilliii** [comment]
So another issue was raised in regards to gcode triggering of the commands without setting the index to 1, so if that is important to you I recommend going the other route and setting SetOption26 to 1. I just pushed an update that adds the graphing tab. You can reinstall from the same url below for additional testing.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.9.zip

![image](https://user-images.githubusercontent.com/5249455/71635812-e2300080-2bf5-11ea-96d8-9bb3cfd081d0.png)

**Comment by DesC21** [comment]
I just tried the lastest version 8.9.0 for the energy monitoring. I stumbled across the same issue with the "can't read device status" message but now it is working fine. When I hover over the icon I can see the all the data. But the graph on the tasmota tab doesn't show up, is there anything else I have to enable?

**Comment by jneilliii** [comment]
@DesC21, are you looking for energy data or sensor data?  Do you have the polling option enabled to check the status on regular intervals?  That's when the data will be written out to the database.  Once that has run for a bit you may have to restart octoprint and force a browser cache refresh (ctrl+F5 or similar depending on your browser) for the reporting to be initially seen by the plugin.

**Comment by DesC21** [comment]
@jneilliii sorry for the late answer... I am looking for the energy data. I can see them when I hover over the icon but on the Tasmota tab. The polling option is enabled. Where is the database located, can I check manually if there is data in there? 
On the Tasmota tab I only get the Start/end boxes and the update buttons but no graph.

**Comment by jneilliii** [comment]
You should find the data files created in ~/.octoprint/data/tasmota/

**Comment by DesC21** [comment]
> You should find the data files created in ~/.octoprint/data/tasmota/

This is how my energy_data.db looks. Is this correct? 
![energy_data_db](https://user-images.githubusercontent.com/26366384/73979546-a55ed400-492e-11ea-9976-5e4b28fe82af.png)

**Comment by jneilliii** [comment]
That's probably correct. It's not a simple text file, so opening in nano is probably not the best option. Try restarting octoprint and force a refresh of your browser's cache by pressing either ctrl+f5 or shift+f5.

**Comment by jneilliii** [comment]
Also, check your browser's developer console (typically the f12 key on your keyboard) to see if there are any errors on page load or when you switch to the Tasmota tab.

**Comment by DesC21** [comment]
> That's probably correct. It's not a simple text file, so opening in nano is probably not the best option. Try restarting octoprint and force a refresh of your browser's cache by pressing either ctrl+f5 or shift+f5.

Ah okay, I thought it might be clear text because of the IP and time/date. Do you maybe plan on any export function?

> Also, check your browser's developer console (typically the f12 key on your keyboard) to see if there are any errors on page load or when you switch to the Tasmota tab.

I get a "Uncaught ReferenceError: Plotly is not defined" error when opening the Tasmota tab. Do I have to install anything beside the Tasmota plugin?

**Comment by jneilliii** [comment]
Yep, that's an error.  I forgot to include the plotly library, but it was installed by one of my other plugins.  I've just fixed that.  Reinstall and it should be fixed now.

**Comment by DesC21** [comment]
perfect, that fixed it ;)
