### ISSUE TITLE
Toggling the light 

### ISSUE THREAD

**Issue by pathia** [jneilliii/OctoPrint-Tasmota#172]
Hello,
I am currently using the tasmota plugin already to toggle my power supply of the printer.
But I want to add a second tasmota plug which toggles the light on my printer bed.
How can I make the second plug in octoprint a light switch? (with light icon in taskbar in the webgui, but preferably also in the octoapp application for my cellphone.

**Comment by jneilliii** [comment]
not sure on the octoapp side, but adding a second device to the plugin's settings, and editing the icon to use a different one would make it a bulb, is that what you're asking?

![image](https://user-images.githubusercontent.com/5249455/149680797-d69d7f72-3c23-47df-b76f-131e543a54ae.png)

![image](https://user-images.githubusercontent.com/5249455/149680817-fbb3f1f8-bbe1-42e3-91ed-b4f5fc05c9fb.png)

**Comment by pathia** [comment]
Well that's even easier than I thought. I'll have to check with the octoapp dev to see how this works over in his app.
Thanks a lot for the prompt response. You're reply was very helpful 👍🏻
