### ISSUE TITLE
could not activate 'On with upload/connect'

### ISSUE THREAD

**Issue by klkl140** [jneilliii/OctoPrint-Tasmota#174]
Hello
First thank you for this nice plugin.
In my case im not able to activate 'On with upload' or 'On with connect'. I cant see any reason. The help is showing the right information but the checkboxes are disabled.
Am I doing something wrong?

Greetings Klaus

<img width="325" alt="Bildschirmfoto 2022-03-16 um 17 32 13" src="https://user-images.githubusercontent.com/8624766/159120802-3f1297a5-8bf7-4eff-b4a7-5bbe18dfcd85.png">

**Comment by jneilliii** [comment]
Enable the appropriate event monitoring options in the general settings first.

**Comment by klkl140** [comment]
Thank you, that was the trick. I have not seen the connection. My proposal would be to start the corresponding event monitoring automatically, or to give a hint in the help text. Greetings Klaus
