### ISSUE TITLE
GCode being passed through to printer

### ISSUE THREAD

**Issue by RobeeeJay** [jneilliii/OctoPrint-Tasmota#178]
When I have `M80 192.168.1.101 1` in my GCode, it gets passed straight through to my printer running RepRap firmware, which then errors with a PS_ON message because it has nothing to turn on.

I'm not sure if my Marlin based Prusa Mini is okay with this because it ignores M80 or if it's correctly being filtered out for Marlin but not RepRap based printers.

**Comment by jneilliii** [comment]
It's probably because Prusa Mini just ignores it. To get around this I can add @ commands `@TASMOTAON 192.168.1.101 1` and `@TASMOTAOFF 192.168.1.101 1` and that should work in your case. I've done this with the TPLinkSmarplug plugin, shouldn't take long to implement.

**Comment by jneilliii** [comment]
Added with the above commit and available as [Version 1.1.3rc1](https://github.com/jneilliii/OctoPrint-Tasmota/releases/tag/1.1.3rc1) you can switch the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted and use the new gcode command options mentioned above.

**Comment by RobeeeJay** [comment]
Oooh super I will try it, thank you!!! 💜

**Comment by RobeeeJay** [comment]
This works wonderfully, thank you again!!!
