### ISSUE TITLE
API support for status

### ISSUE THREAD

**Issue by taker218** [jneilliii/OctoPrint-Tasmota#181]
Hello,

I'm already using the plugin for quite some time now and just recently started to use OctoFarm to monitor all my printers in one place.

I set up OctoFarm so I can power on my printers from the webinterface, but it seems like I can't get the status of the tasmota plug so all I can do is power on the printer, but from there on the power status in OctoFarm is still off.

These are the settings I put in OctoFarm (Power Toggle doesn't work either, maybe this could also be implemented? Tasmota can be toggled with the command POWER%20TOGGLE)

If the API already supports those commands they should be added to the API wiki as well :)

![grafik](https://user-images.githubusercontent.com/15029277/170526122-c434e24a-ce98-4594-8e72-fb7a2d0bbac1.png)

**Comment by jneilliii** [comment]
You're right. Someone had actually contributed the status check API endpoint but the wiki docs were not updated. What you have listed in your screenshot should work. If it's not working on OctoFarm side than @NotExpectedYet may need to update his side of things.

**Comment by jneilliii** [comment]
I will look into adding the Toggle option for a future release.

**Comment by taker218** [comment]
I tried the checkStatus manually via curl and it seems to return something, I'll open an issue on the octofarm github for that, maybe it's not parsed correctly

**Comment by NotExpectedYet** [comment]
Taker sent the response, didn't realise yours was on/off, will amend and sort no worries.

**Comment by jneilliii** [comment]
Thanks James. Technically since you're removing power toggle I don't see the benefit either from this side, so closing ticket.
