### ISSUE TITLE
switch via API call

### ISSUE THREAD

**Issue by DarthWeber** [jneilliii/OctoPrint-Tasmota#186]
Hi ! As i read in the documentation of the scheduler plugin, a simple curl command like

`curl -s -H "Content-Type: application/json" -H "X-Api-Key: <API_KEY>" -X POST -d '{ "command":"turnOn", "ip":"<IP>", "idx":"<IDX>" }' http://localhost/api/plugin/tasmota`

should turn the plug on, but this comman doesen't work even if i use it on the ssh prompt. It just return nothing, no error.

I need the command to schedule my print jobs, the curl command should first switch on the printer.

Did i misunderstoof something ?

**Comment by jneilliii** [comment]
I assume you've filled in the tokens `<API_KEY>`, `<IP>`, `<IDX>` with actual values?

**Comment by DarthWeber** [comment]
Yes, sure. Ip from tasmota plug, idx 1, API key I tried several application keys for an admin account as well as the api key itself. The plug itself works of course

**Comment by jneilliii** [comment]
Strange, I just tested on my setup and this is working for me.

```
curl -s -H "Content-Type: application/json" -H "X-Api-Key: my_appkey" -X POST -d '{ "command":"turnOn", "ip":"192.168.0.105", "idx":"2" }' http://localhost/api/plugin/tasmota
```
