### ISSUE TITLE
Lots of connection errors

### ISSUE THREAD

**Issue by lettore** [jneilliii/OctoPrint-Tasmota#187]
Hello,
I'm using a Tasmota plug maybe not of the best quality, as happens that it's not responding to call from the plugin. This throw an error in web-ui, and it's very annoying. It's possible to add an option to not raise the error if the plugin is unable to connect to the plug? I use this plugin only for monitoring the power consumption, as for directly control the plug I use PSU Control.
It would be nice also an option to remove the icon from the top bar.
Thanks

**Comment by jneilliii** [comment]
Sorry, not making options that don't make sense. If PSU control plugin is handling it why not use some other means to monitor the power consumption?

**Comment by lettore** [comment]
Yes, it doesn't make sense to handle a connection timeout without generating a useless error. Don't worry I already blacklisted this plugin, as you said there are other ways to monitor the power consumption.
