### ISSUE TITLE
power off on idle not working ?

### ISSUE THREAD

**Issue by PVerburg** [jneilliii/OctoPrint-Tasmota#190]
The window pops up counts down but Tasmota never receive power off command.
no problem when using gui lightning bolt.

**Comment by PVerburg** [comment]
![image](https://user-images.githubusercontent.com/7756751/200464158-45095b20-ffca-4829-ae76-fd9fb27f2ca9.png)
sure is?
![Screen Shot 11-08-22 at 03 55 PM](https://user-images.githubusercontent.com/7756751/200464372-92c11d6a-b65f-4850-a477-1f14a8231a6e.PNG)

**Comment by jneilliii** [comment]
> Ooops that's a trick for old people like me two places to enable ????

lol, not intentionally. the idea is that if you have multiple devices configured you might not want to power them all off.
