### ISSUE TITLE
S31 Sonoff plug   (Tasmota Error... status unknown for the IP)

### ISSUE THREAD

**Issue by LuckyFPV** [jneilliii/OctoPrint-Tasmota#193]
S31 Sonoff with power-management works fine via UI, (i.e. directly connected in a browser) but Octoprint will not turn it on.  Oddly if I manually turn on the switch Octoprint is reading  voltage when you hover over the button,   (pic attached)
OctoPrint and S31 are on same network and other Tasmota plugs work fine.

 Logging below, just flashed this plug with latest tasmota bin (Info below)

**Logs:**
[2023-01-26 00:35:26,057] ERROR: Invalid ip or unknown error connecting to 192.168.1.168.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 539, in turn_off
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'

**Pic of UI**
![TasmotaOct](https://user-images.githubusercontent.com/34111819/214767106-222e71f7-bb26-4f4e-a063-c29f6476ca13.png)

Program Version 12.3.1(tasmota)
Core/SDK Version | 2_7_4_9/2.2.2-dev(38a443e)

**Comment by jneilliii** [comment]
Did you enable SetOption26 or whatever it is? If you use the verify button I think it will set it for you.

**Comment by LuckyFPV** [comment]
set SetOption26 but unfortunately the behavior is the same
see this logging on the S31 device,  (i "XXXXXX" out a few items)
====================
15:24:27.349 RSL: STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
15:24:27.357 RSL: STATUS10 = {"StatusSNS":{"Time":"2023-01-26T15:24:27","ENERGY":{"TotalStartTime":"2023-01-26T02:02:24","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
15:24:27.363 RSL: STATUS11 = {"StatusSTS":{"Time":"2023-01-26T15:24:27","Uptime":"0T00:01:54","UptimeSec":114,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"XXXXXXXX","BSSId":"XXXXXXXX","Channel":1,"Mode":"11n","RSSI":78,"Signal":-61,"LinkCount":1,"Downtime":"0T00:00:05"}}}
15:24:41.252 RSL: STATUS = {"Status":{"Module":41,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_2AD9A2","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
15:24:41.257 RSL: STATUS1 = {"StatusPRM":{"Baudrate":4800,"SerialConfig":"8E1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:02:08","StartupUTC":"2023-01-26T14:22:33","Sleep":50,"CfgHolder":4617,"BootCount":10,"BCResetTime":"2023-01-26T02:02:24","SaveCount":48,"SaveAddress":"F4000"}}
15:24:41.260 RSL: STATUS2 = {"StatusFWR":{"Version":"12.3.1(tasmota)","BuildDateTime":"2022-12-16T10:28:17","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"350/699"}}
15:24:41.264 RSL: STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["XXXXXXXX",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000680003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
15:24:41.275 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":629,"Free":372,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000080"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"}}
15:24:41.279 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-2AD9A2-6562","IPAddress":"192.168.1.168","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.1","DNSServer2":"0.0.0.0","Mac":"XXXXXXXX","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
15:24:41.283 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_2AD9A2","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
15:24:41.288 RSL: STATUS7 = {"StatusTIM":{"UTC":"2023-01-26T14:24:41","Local":"2023-01-26T15:24:41","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"08:28","Sunset":"17:36"}}
15:24:41.291 RSL: STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
15:24:41.299 RSL: STATUS10 = {"StatusSNS":{"Time":"2023-01-26T15:24:41","ENERGY":{"TotalStartTime":"2023-01-26T02:02:24","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
15:24:41.304 RSL: STATUS11 = {"StatusSTS":{"Time":"2023-01-26T15:24:41","Uptime":"0T00:02:08","UptimeSec":128,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"XXXXXXXX","BSSId":"XXXXXXXX","Channel":1,"Mode":"11n","RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:05"}}}
15:26:52.915 RSL: STATUS = {"Status":{"Module":41,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_2AD9A2","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
15:26:52.920 RSL: STATUS1 = {"StatusPRM":{"Baudrate":4800,"SerialConfig":"8E1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:04:19","StartupUTC":"2023-01-26T14:22:33","Sleep":50,"CfgHolder":4617,"BootCount":10,"BCResetTime":"2023-01-26T02:02:24","SaveCount":48,"SaveAddress":"F4000"}}
15:26:52.923 RSL: STATUS2 = {"StatusFWR":{"Version":"12.3.1(tasmota)","BuildDateTime":"2022-12-16T10:28:17","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"350/699"}}
15:26:52.927 RSL: STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["XXXXXXXX",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000680003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
15:26:52.937 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":629,"Free":372,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DOUT","Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000080"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"}}
15:26:52.942 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-2AD9A2-6562","IPAddress":"192.168.1.168","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.1","DNSServer2":"0.0.0.0","Mac":"XXXXXXXX","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
15:26:52.946 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_2AD9A2","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
15:26:52.951 RSL: STATUS7 = {"StatusTIM":{"UTC":"2023-01-26T14:26:52","Local":"2023-01-26T15:26:52","StartDST":"2023-03-26T02:00:00","EndDST":"2023-10-29T03:00:00","Timezone":"+01:00","Sunrise":"08:28","Sunset":"17:36"}}
15:26:52.954 RSL: STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
15:26:52.962 RSL: STATUS10 = {"StatusSNS":{"Time":"2023-01-26T15:26:52","ENERGY":{"TotalStartTime":"2023-01-26T02:02:24","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
15:26:52.967 RSL: STATUS11 = {"StatusSTS":{"Time":"2023-01-26T15:26:52","Uptime":"0T00:04:19","UptimeSec":259,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"XXXXXXXX","BSSId":"XXXXXXXX","Channel":1,"Mode":"11n","RSSI":80,"Signal":-60,"LinkCount":1,"Downtime":"0T00:00:05"}}}

**Comment by jneilliii** [comment]
could you by chance please share a screenshot of your settings for the plug? With SetOption26 enabled (1) then the index needs to be set to 1. With SetOption26 disabled (0) then the index can be left blank. it would help if you could enable debug logging in the plugin's settings, save, restart OctoPrint and try to click the button. Then share plugin_tasmota_debug.log.

**Comment by LuckyFPV** [comment]
Will be away for a few days,  but will do when I return.
  As for now, is working fine with SetOption26 1

**Comment by jneilliii** [comment]
Oh, I thought with that option enabled it wasn't working. If that works completely then we can close this issue.
