### ISSUE TITLE
Gcode auto on/off not working?

### ISSUE THREAD

**Issue by Quintin9801** [jneilliii/OctoPrint-Tasmota#20]
Not sure if I'm missing something but after reading the setup page many times, from my understanding is I just put the PI of the sonoff after the M80 or M81 Command in the script for before and after printing. if I'm getting this wrong please someone explain this to me.

**Comment by jneilliii** [comment]
I may have to look into that. The recent finding of single relay devices not working with an index value may mean it's broke. Try with the following gcode (2 spaces after ip).

`M80 ip  `

**Comment by Quintin9801** [comment]
I've tried this command both in the gcode scripts that are configured in Octoprint's settings and just sending out the command via the terminal in octoprint. with the double space, I see how it could mimic the index number. Although this didn't work I also tried triple space in between the Gcode and the IP to better mimic the index this still didn't work after printing many calibration cubes.

**Comment by jneilliii** [comment]
It was what I thought.  I just released a new version 0.6.0 that should resolve the problem.  You will need to change the index to 1 and use the command `M80 ip 1` for your gcode.

**Comment by Quintin9801** [comment]
Thank you so much it works perfectly now!
