### ISSUE TITLE
Power off before reaching end of octoptint script

### ISSUE THREAD

**Issue by FajnB** [jneilliii/OctoPrint-Tasmota#208]
So I have found out that if your script has M81 command (with IP and index), no matter where in the script it is it will execute before it really should.

I believe it has something to do with how commands are buffered in octoprint terminal before they are actually needed/are sent to printer.

```
M256 B255 ; Set LCD brightness to max
M106 S128 ; Set fan to 100%
M104 S200 ; Heat nozzle
M140 S60  ; Heat bed
G28 ; Home
... a lot of gcode ...
M117 Script ended  ; Display message
M81 192.168.1.40 1 ; Turn off PSU (Smart socket)
```
So my question is, if I have a script like above, is it even possible for it to work? (_It does some fancy stuff like cleaning and such which can be unattended and I thought it would be nice that it turns off on its own._)
Like from what I observed the plugin detects the M81 command after a while, so the script does run for a bit. With the code above the printer gets to point where it homes XY and as soon as it moves to centre of the bed to probe Z, tasmota plugin sends turn off command.

It might be a bug or it also might be intended as this is kind of stretching the use case of the plugin as I can imagine it was never meant for execution of scripts rather than by regular print job gcode. Or do I have to put M81 command to the octoprint "After print job" script section only?

**Comment by jneilliii** [comment]
It should work in your end gcode or OctoPrint's gcode scripts section, but the issue is probably the printer buffer. That's what the delay times are for, you should be able to set those higher to account for the timing discrepancy. I personally just use the idle timeout options.

**Comment by FajnB** [comment]
I am kind of lost. I tried M85 and M86/M18, but this just either "kill" the printer or set a temp.
Is there any other option I am not aware of?

(Running marlin fw)

**Comment by jneilliii** [comment]
Where are you entering this M81 command, in your slicer end gcode or OctoPrint's GCODE Scripts settings? What did you set the gcode delay to? Please share screenshots of your settings, both the general plugin settings, and the detail settings for the specific device.

The alternative to M81 commands are @ commands, and that won't be picked up by your printer's firmware and do anything, it's all internal to the plugin/OctoPrint for processing. Try replacing 
```
M81 192.168.1.40 1 ; Turn off PSU (Smart socket)
``` 
with 
```
@TASMOTAOFF 192.168.1.40 1 ; Turn off PSU (Smart socket)
```

**Comment by FajnB** [comment]
You are a lifesaver! This is exactly what worked. Replacing/hiding the M81 under @TASMOTAOFF macro did the thing.



For anyone else who might find this thread in the future
======
I used [Gcode Macros](https://plugins.octoprint.org/plugins/gcode_macro/) plugin to create a macro (the @ symbol) named TASMOTAOFF.

1. The name of your macro goes to the "command" field (It has @ symbol on the beginning the field)
2. Under macro content, put `M81` and that is it.
3. You can optionally give it a description but who ever reeds these

After you create this macro, then you proceed and put your command where ever you need it in the gcode or script by writing the code as follows:

```
@NAME_OF_MACRO IP_ADDRESS_OF_THE_TASMOTA ID_NUMBER_OF_RELAY
```

As an example, I named my macro "TASMOTAOFF". I have a tasmota smartplug which has only one relay so its relay ID is 1. This socket is located under IP 192.168.1.40. So to turn off this tasmota I will put a command as flows:
```
@TASMOTAOFF 192.168.1.40 1
```

**Comment by jneilliii** [comment]
> I used [Gcode Macros](https://plugins.octoprint.org/plugins/gcode_macro/) plugin to create a macro (the @ symbol) named TASMOTAOFF.

This is not necessary, the plugin itself supports the @TASMOTAOFF command, so I have not idea what you are talking about.

**Comment by FajnB** [comment]
My bad. I'll rewrite it.
