### ISSUE TITLE
will not connect now after update

### ISSUE THREAD

**Issue by mszymura** [jneilliii/OctoPrint-Tasmota#21]
hi, after update will not connect using the ip address. can log onto the sonoff using ip address and toggle.
Have tried combinations of index , but reading notes should be one. firmware updated on sonoff. have another printer on the older version. how do i roll back to previous version?

**Comment by jneilliii** [comment]
If you are using a single relay device make sure to enable that option.

**Comment by mszymura** [comment]
Hi , yep done that, used index 1 , wil not connect, wouldn't mind rolling back to see if it's me! Will keep on trying, connects via web . Strange ! Tried switching my other radmira sonoff with this Octoprint and no joy here either . Thanks for the reply .

**Comment by jneilliii** [comment]
Which firmware version are you running on your devices?  Needs to be 5.11.0 minimum now.  If they are upgraded then enable debug logging and then upload the "plugin_tasmota_debug.log" file here.

**Comment by moskovskiy82** [comment]
Same here. I'm on 5.10.0a

**Comment by jneilliii** [comment]
Thanks for verification, hopefully @moskovskiy82 issue is the same but no response, closing.

**Comment by mszymura** [comment]
All sorted, upgraded to 5.11.1d and works a treat. Thanks
Mark
