### ISSUE TITLE
Not working with my TP Link HS110

### ISSUE THREAD

**Issue by fakio87** [jneilliii/OctoPrint-Tasmota#22]
Hi,

I cannot get the plugin working with my TP-Link Smartplug HS110.

TP-Link Smartplugin is working, but Tasmota is not getting the connection while using the very same settings. Any hint how to get it working?

**Comment by jneilliii** [comment]
Tasmota is a completely different device and configuration than tp-link, they are not interchangeable as they use different communication protocols and responses.
