### ISSUE TITLE
GCode off delay not working

### ISSUE THREAD

**Issue by Quintin9801** [jneilliii/OctoPrint-Tasmota#23]
I've set my GCode off delay to 20 seconds and the off command works great, but the delay function does not. It's not a huge deal but I also use the Telegram plugin to monitor my prints and the final picture when sent is black because my Tasmota controls the light above my printer. Please help me troubleshoot a fix.

**Comment by jneilliii** [comment]
I'm able to reproduce this.  Let me look into it.

**Comment by jneilliii** [comment]
Fixed with latest release 0.7.0.
