### ISSUE TITLE
Setup missing

### ISSUE THREAD

**Issue by OperatorB** [jneilliii/OctoPrint-Tasmota#27]
After installing Tasmota plugin i can not configure it properly. E.g. the 'user' and 'password' setting is missing. Can it be specific to my OrangePi Zero or the readme pictures are outdated?

![screenshot from 2018-02-24 10-20-16](https://user-images.githubusercontent.com/34603896/36628359-f75eb07c-194c-11e8-819c-a6344037b292.png)
![screenshot from 2018-02-24 10-20-04](https://user-images.githubusercontent.com/34603896/36628376-fcc5792e-194c-11e8-84a7-89166daaeb01.png)

**Comment by jneilliii** [comment]
You're completely right, when I re-designed the interface I totally dropped those fields from the settings.  I'll get that added back.  I do notice that your IP is configured incorrectly.  It should just be the IP address, not the full web url.

**Comment by jneilliii** [comment]
New release just pushed to add those fields back in.  For your other question, you can achieve this with the GCODE processing, using M81 and the GCODE off delay.  This will allow you to add the gcode commands to your end gcode, or within OctoPrint's settings for print complete gcode commands.  It will wait for the delay configured after receiving the M81 command and then power off the plug.

**Comment by OperatorB** [comment]
Thank you.
