### ISSUE TITLE
Icon Ref issue

### ISSUE THREAD

**Issue by PonyOny** [jneilliii/OctoPrint-Tasmota#29]
The link to Font Awesome icons is not correct the correct one should be
https://fontawesome.com/v3.2.1/icons/
as you are using Font Awesome 3.2.1 and does not have the latest icons you display in the link you added, this also have other format of css class "fa-plug", you could change the link or update the Font Awesome library to the latest for better icon compatibility or maybe change to material icons.

**Comment by jneilliii** [comment]
Thanks for pointing that out.  I am not the one that embeds the library, I'm just using it from what's already included with OctoPrint.  I'll update the link in the next release.

**Comment by jneilliii** [comment]
Actually looks like fontawesome.io changed,  That cheatsheet link did use to work and was correct.  As stated, I'll update the links and publish new release.

**Comment by jneilliii** [comment]
Links updated.
