### ISSUE TITLE
password field readable

### ISSUE THREAD

**Issue by VinceMasuka** [jneilliii/OctoPrint-Tasmota#34]
Hi there

It looks like the password field is readable what leads into a security issue.
![grafik](https://user-images.githubusercontent.com/24939202/48967617-91f27200-efe3-11e8-80ae-d7953280794d.png)

Do you mind to please make the password field unreadable?

Thanks!

Regards
Vince

**Comment by VinceMasuka** [comment]
That's what I thought. That's unfortunate. Thanks anyway.

**Comment by jneilliii** [comment]
Agreed, but even if I were to encode it in settings somehow the tasmota web call itself has to use a decoded password and would then just be in the web request in plain text. There's really no good way to handle it that I could think of, and I did think on it for a while.
