### ISSUE TITLE
Toggle is very slow

### ISSUE THREAD

**Issue by Palloquin** [jneilliii/OctoPrint-Tasmota#35]
Hi there,
What a great addition to octoprint! This way I can automatically switch off the printer after use and save 17 Watts of power!

The plugin seems to do what it should for me, but the toggle is often very slow. Sometimes it takes up to a minute or so before the printer is turned on after I press the lightning bolt icon in the toolbar. If instead I go to the device's tasmote page and press the on (or off) toggle there, the effect is instant.

Am I doing something wrong, is there a way to troubleshoot the delay?

**Comment by Palloquin** [comment]
Thank you for your quick response!

Does your plugin talk to the sonoff directly trough http requests or does it use mqtt?

I have to slightly disagree with you on how the web interface works. In that case I am also going over the network. 

1.  my browser requests the page, 
2.  I press to toggle on the web page 
3.  my browser sends a network command (http request) to the sonoff. 

So, this is not like flipping a a switch (or pressing the button on the sonoff), there is still some network traffic. So, I'm curious whether your plugin does (that same) http request, or if it does it through something else, like MQTT (I have no MQTT configured in my network).

I'll see if I can find the octoprint error logs, never looked for them before, and will update with that info!

thank you again!

**Comment by jneilliii** [comment]
So, yes, we are both kind of right on the communication aspect. Sorry, wasn't clear.  The plugin works as a middle man to the web request.  When you click the button in OctoPrint it doesn't send the command directly to the sonoff.  It sends a web request to the plugin and then the plugin sends the web request to the sonoff device while it does all the other options like disconnect, system commands, etc. This is where it takes into account any configured delays as well.  If you don't have any of those delay options enabled then it should be fairly quick. My other plugin OctoPrint-TasmotaMQTT is the one that utilizes a MQTT infrastructure, not this on.  This one only uses web requests.
