### ISSUE TITLE
Status Polling

### ISSUE THREAD

**Issue by jan-gerard** [jneilliii/OctoPrint-Tasmota#36]
Nice piece of code, this plugin. But would it be possible to somehow update the status? If after printing the Sonoff is switched off by the G-code sequence, and I want to print something else later, I have to reload the complete octoprint page, since otherwise it does not know that the Sonoff is off and not on. The green icon remains, and there is no way to make it turn red, other than reloading the page. 
Could there be an update option, or even some auto-update mechanism that checks the Sonoff status every now and then?

**Comment by jneilliii** [comment]
I could add a polling option like I have for the tplink smartplug plugin.

**Comment by jneilliii** [comment]
Or you could use the mqtt version of the plugin that is always up to date, but requires additional infrastructure.

**Comment by jneilliii** [comment]
@jan-gerard, @TheDiNi74, I've got a test build up that enables polling of status, allows for custom colors of the button for on/off, and enables the use of backlog as an external countdown timer.  The later would be helpful in the instance where you want to shutdown the pi using system commands, but tell the plug to power off later to allow the printer to cool down with it's fans on, etc. If you don't mind, please test by installing the plugin using the url below in plugin manager and report back here if you have any problems.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.6.zip

**Comment by TheDiNi74** [comment]
Test started
removed older Version from octoprint.
Restart octoprint
add newer release 0.8.6
Restart rasperberry pi
config one Device Sonoff RF
Polling Auto Refresh Status every  1 min seems working :-)

I changed Device Status with integrated Button, also with 433mhz remote...
fine

[Idea:
-Refresh button next to power Buttons to imeadeatly refresh Status
and/or mouseover? Button may be intuitive

Failure :-|
But can not add more Devices in config in octoprint. Only can edit the 1 prepared that comes with fresh plugin install.
Thats work at previous Version ;-)

Nice work.. so i don't have to use my rusty programming knowledge

**Comment by jneilliii** [comment]
Thanks.  I'll look into the issue of adding additional plugs, didn't test that on my end (oops).

**Comment by TheDiNi74** [comment]
no Problem ;-)
revert to 0.8.5 and i could add more devices, after restart system
thinks its in a Problem in 0.8.6

Thanks for your work in name of all users of this plugin:-)

**Comment by jneilliii** [comment]
I just pushed an update to the same branch.  You should be able to reinstall with the same url and be able to add additional plugs.  Still untested as I have a print in progress right now, but should take care of the issue.  I had transposed a couple of characters in one of the function calls, and was therefore causing a javascript error.

**Comment by TheDiNi74** [comment]
Ok, you fixed it.
know i can:
add more than one device again
let it check all 60 sek for real status of switches if triggerd external
change colors for the 3 status
Thanks

**Comment by jneilliii** [comment]
Thanks.  I've just pushed this to an official release version.
