### ISSUE TITLE
Single-shot shutdown-after-print button

### ISSUE THREAD

**Issue by jan-gerard** [jneilliii/OctoPrint-Tasmota#37]
Often, I start a print, and then realize that it will take longer than anticipated, and I would like to shutdown my printer after it finishes. 
Now, I add a G-code to my slicer output file via the Slic3r config, and it makes the printer shutdown afterwards. I can also add that via Octoprint. But in both cases, it's set for that print and if I didn't set it, the printer stays on.
My idea would be to make an overrule button, that can either leave what's configured, or shutdown the printer when the print is finished, or leave it on (even if the G-code tells to shut it down). And then after doing its jobs (when the current print had finished), the button should restore to its original (neutral) state. 
Could that be an option to add to OctoPrint-Tasmota(MQTT)? I think it should belong there, and not in a separate plugin, since it only makes sense if you have an automated power switch like a Tasmota.

**Comment by jneilliii** [comment]
You can actually accomplish that exact methodology with https://plugins.octoprint.org/plugins/shutdownprinter/ and my plugin.
