### ISSUE TITLE
[Feature request] Add auto shutdown after idle time and nozzle temperatur

### ISSUE THREAD

**Issue by pandel** [jneilliii/OctoPrint-Tasmota#38]
Hi!

Very nice plugin, it is working great with my Sonoff device. But I have a little feature request. On another Octoprint instance I am using the plugin "PSU Control", which has the capability to turn off the printer automatically after a certain amount of idle time in conjunction with a specified nozzle temperature, so that you can say "turn the printer off after 5 minutes, but, in any case, wait for the nozzle to cool down to 50 degrees". 

It would be really great, if you could add this timer feature, too.

Regards,
Holger

**Comment by Fettbemme** [comment]
@pandel for this feature you can use the plugin Shutdown Printer which works with OctoPrint-Tasmota.
https://github.com/devildant/OctoPrint-ShutdownPrinter

Or you can just set it in the End G-Code off your slicer. 
i run this:
M109 R40; wait for Hotend to drop to 40C
M104 S0 ; turn off temperature (just in case shutdown is not working)
M81 192.168.178.26 1; shutdown the printer via Tasmota-Sonoff on octopi

**Comment by jneilliii** [comment]
Thanks @Fettbemme, I was going to recommend that as well.  The logic is added when both plugins are installed.
