### ISSUE TITLE
Always switches on the printer when open or reload the octoprint in browser

### ISSUE THREAD

**Issue by CodeMedve** [jneilliii/OctoPrint-Tasmota#39]
Hi,

When I reload the octoprint in browser it is always switches on the the printer.
It makes makes for me an unwanted switch on.
Is it possible to switch off this function?

**Comment by jneilliii** [comment]
The plugin is not programmed to do that and this is the first time I've received a report of this behavior.  What version of OctoPrint are you running? Are there any errors in octoprint.log or the browser's developer console when you open/reload?
