### ISSUE TITLE
behaviour of tasmota replies changed

### ISSUE THREAD

**Issue by okuemmel** [jneilliii/OctoPrint-Tasmota#43]
Hi, 
tasmota is reporting status in lower case , in the plus in its checked against upper case

`9-06 11:10:03,405] DEBUG: {u'command': u'disconnectPrinter'}
[2019-09-06 11:10:03,406] DEBUG: Disconnecting printer.
[2019-09-06 11:10:03,557] DEBUG: {u'username': u'admin', u'idx': u'1', u'ip': u'192.168.100.39', u'command': u'turnOff', u'backlog_delay': 0, u'password': u'2cool4u'}
[2019-09-06 11:10:03,561] DEBUG: Using authentication for 192.168.100.39.
[2019-09-06 11:10:03,565] DEBUG: Turning off 192.168.100.39 index 1.
[2019-09-06 11:10:03,614] DEBUG: Response: {u'POWER1': u'off'}
[2019-09-06 11:10:03,616] DEBUG: {u'POWER1': u'off'}
^C
`

**Comment by jneilliii** [comment]
Is that effecting the plugin from working properly? Which firmware version?

**Comment by okuemmel** [comment]
Tasmota is V6.6.0 . And yes, due to case-sensitive the cause in the code will fail. if chk == "ON":				self._plugin_manager.send_plugin_message(self._identifier, dict(currentState="on",ip=plugip,idx=plugidx))			elif chk I changed ON to on and OFF to off n all cases and the plugin worksMit freundlichen Grüßen Oliver Kümmel Am 06.09.2019 18:09 schrieb jneilliii <notifications@github.com>:Is that effecting the plugin from working properly? Which firmware version?

**Comment by jneilliii** [comment]
I'm not getting the same results as you when I test the web command like below, which is what the plugin uses with firmware version 6.6.0.

http://192.168.100.39/cm?cmnd=Power1

responds with 

```
{"POWER1":"OFF"}
```

**Comment by okuemmel** [comment]
Thats crazy Mit freundlichen Grüßen Oliver Kümmel Am 06.09.2019 19:53 schrieb jneilliii <notifications@github.com>:I'm not getting the same results as you when I test the web command like below, which is what the plugin uses with firmware version 6.6.0.
http://192.168.100.39/cm?cmnd=Power1
responds with
{"POWER1":"OFF"}

**Comment by jneilliii** [comment]
I just pushed a new branch that should resolve this in theory by changing the comparison to be upper case.  I'm about to test it to make sure there are no errors, but if you could test as well that would be helpful.  Install using this url in plugin manager.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.7.zip

**Comment by okuemmel** [comment]
Ok, will test tomorrow Mit freundlichen Grüßen Oliver Kümmel Am 06.09.2019 21:28 schrieb jneilliii <notifications@github.com>:I just pushed a new branch that should resolve this in theory by changing the comparison to be upper case.  I'm about to test it to make sure there are no errors, but if you could test as well that would be helpful.  Install using this url in plugin manager.
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.7.zip
