### ISSUE TITLE
Question: How can I run turn off the plug via commandline with TemperatureFailSafe plugin

### ISSUE THREAD

**Issue by NovaViper** [jneilliii/OctoPrint-Tasmota#48]
Hi! I'm wondering if it's possible to turn off the plugs using the TemperatureFailSafe plugin. The plugin executes a shell command whenever the printer reaches pass a certain temperature.

**Comment by jneilliii** [comment]
The thermal runaway option has been requested in issue #44, I just haven't had the time to work on it lately.  You can however use the ShutdownPrinter plugin to achieve thermal related shutdown options.

https://github.com/devildant/OctoPrint-ShutdownPrinter
