### ISSUE TITLE
Power off on print complete

### ISSUE THREAD

**Issue by PonyOny** [jneilliii/OctoPrint-Tasmota#5]
It would be nice if there was a checkbox under the print status in OctoPrint that would let you automaticaly turn off the power once the print has successfuly finished, this could be checked on every print so if you need tu turn off the power once it’s finished, if it’s checked it would be nice once the print is finished to open a dialog with a 10 second countdown so in case you want to cancel the power off, if you dont cancel it in 10 seconds it would power off automatically.

**Comment by jneilliii** [comment]
There is no timer function, but you can achieve the other part using the m80 and m81 gcode commands and enable gcode processing in settings. You can either add the command to octoprint's gcode settings or individually in the gcode itself.

**Comment by jneilliii** [comment]
Check gcode section is settings explained in the [readme](https://github.com/jneilliii/OctoPrint-Tasmota/blob/master/README.md).
