### ISSUE TITLE
Readme doesn’t explain all options

### ISSUE THREAD

**Issue by GilDev** [jneilliii/OctoPrint-Tasmota#52]
Hi,

The README doesn’t say what the “Thermal Runaway” checkbox does, nor “Use Countdown Timers”, along with the 4 options on the main settings page (thermal runaway monitoring, debug logging, single relay device, status polling). I think it would be great if some explanations were given.

Thanks!

**Comment by jneilliii** [comment]
Yeah, recent updates that haven't been documented yet.  Thermal Runaway is more of a max temp threshold.  If you set that if the temps go above that point the plug will power off.  Debug Logging is to enable additional logging for me to help people with problems. Single Relay device may not be needed anymore as long as your Tasmota device has SetOption26 set to 1 (not default) or you leave the index value blank. Status polling is so the plug will check the status of the plug on a given interval.

**Comment by GilDev** [comment]
Thanks for your reply! What about "Use Countdown Timers"? I'm not sure about its purpose, would that be useful to shutdown the printer after a print or should this be made with GCode triggers on the "finished print" script?

**Comment by jneilliii** [comment]
That was added in the case where someone wanted to power off their pi, but give the pi plenty of time to properly shutdown using the system commands option before the power was killed to avoid SD card corruption (common issue).  You still have to initiate the power off using gcode either way by putting the command into the slicer's end gcode section or OctoPrint's gcode scripts `after print job completes` section.

**Comment by GilDev** [comment]
Great, thanks!

**Comment by karlkashofer** [comment]
Hi !

> Yeah, recent updates that haven't been documented yet. Thermal Runaway is more of a max temp threshold. If you set that if the temps go above that point the plug will power off. Debug Logging is to 

Are you watching the temperatures yourself or are you catching the "Error" event as suggested by Foosel here? https://community.octoprint.org/t/switching-smart-plug-on-thermal-runaway/5095/10

I want to upgrade my Anet A8 to a 600W 230V Heatbed and really need a second layer of protection in case the SSR controlling the heatbed fails in power on state. Marlin should report "Thermal Runaway" which is a unrecoverable printer error triggering the "Error" event in Octoprint.

**Comment by jneilliii** [comment]
Currently I'm watching the temps within the plugin itself. I've added a similar on firmware error option to the tplink plugin that could be ported over to this one.

**Comment by Delta-38** [comment]
Just popping in to say that Sensor Identifier isn't very clear either. 
As a side note, a missing option I'd gladly buy you a coffee for is a "On Print Upload" On button

:) Great work, loving it

**Comment by jneilliii** [comment]
Yeah, documentation is not my strong suit. If you have a sensor connected I assumed you'd be nerdy enough to know the sensor identified, lol. It should match the sensor listed in the tasmota config, so a setting like this

![image](https://user-images.githubusercontent.com/5249455/78060931-67909180-735a-11ea-8389-ba8c4a5c4f36.png)

the sensor identifier if DHT11.

**Comment by Delta-38** [comment]
Well no problem, know I see, I didn't know whether it was looking for a dropdown value or the GPIO id on the Tasmota, or the name of a sensor in octoprint (say hotend or bed). Especially since some of the settings are relative to the printer, some to the Pi, and some to the tasmota device being configured.  
In my setup for example the flame sensor is connected directly to the PI through GPIO so I wasn't sure what kind of input to give to the field.

Thanks for answering so quickly :)

**Comment by kreuzhofer** [comment]
Is there any way to override that GCODE files cannot be printed until I manually switch on the printer by clicking the lightning button? I would love to have the ability to click on the print button for a file. That file would contain a G80 in the first line to switch on the printer and wait for the connection and then the print could start. Is this somehow possible?

**Comment by jneilliii** [comment]
@kreuzhofer in a future update yes. I'm having the same debate on the TP-Link plugin currently too. I'm just trying to figure out the best way to implement this. As mentioned in your other post, you can use the OctoPrint Connection plugin in Cura to achieve automatic power on / auto start print with this plugin currently.

**Comment by copperfield74** [comment]
> 
> 
> Yeah, documentation is not my strong suit. If you have a sensor connected I assumed you'd be nerdy enough to know the sensor identifier, lol. It should match the sensor listed in the tasmota config, so a setting like this
> 
> ![image](https://user-images.githubusercontent.com/5249455/78060931-67909180-735a-11ea-8389-ba8c4a5c4f36.png)
> 
> the sensor identifier is DHT11.
I also have a question concerning the sensor identifier. Here are two screenshots that are different than yours. What identifier do I have to choose?
![grafik](https://user-images.githubusercontent.com/62651258/83335914-498ad300-a2b0-11ea-8d93-aeb3ea763314.png)
![grafik](https://user-images.githubusercontent.com/62651258/83335926-61625700-a2b0-11ea-8f19-69c6ba9c3cb1.png)

**Comment by jneilliii** [comment]
Are those two different devices? The sonoff pow device should just be detected, the other one appears to ne configured fie serial communication or have you added a sensor?

**Comment by copperfield74** [comment]
Yes these are to different devices. One is a smart plug and the other one is a sonoff POW 2 that can track and show power consumptions. So no sensors here.

**Comment by jneilliii** [comment]
Ok so that setting is specific for sensors, power should I think just work. You may have to enable polling

**Comment by copperfield74** [comment]
I will give it a try! But can you comment a little on the sensor identifier? What to do if our menues looks different than yours. Is the sensor identifier important?

**Comment by jneilliii** [comment]
That is only important if you have a sensor  (ie temperature/humidity). If you don't have one just leave it blank.

**Comment by ryancasler** [comment]
I'm a little confused on how to get the sensor working correctly.  I'm using a BME280 connected through I2C.  So, there is nothing selected in the setup drop-down except I2C SDC and I2C SDA (clock and data).  I tried putting in BME280-76 and BME280-77 but it didn't appear that OctoPrint was getting the data.

![image](https://user-images.githubusercontent.com/30270489/96354056-1189fe00-10a0-11eb-906c-12f7bf01ccd5.png)

Is there something else I should be putting in for Sensor Identifier?

**Comment by jneilliii** [comment]
Try with just BME280 in the sensor identifier field.

**Comment by jneilliii** [comment]
It might be helpful to see what the data looks like on the console side of the Tasmota web interface. Basically you need to match the sensor identifier to one of those properties that match up with your sensor.

**Comment by ryancasler** [comment]
You mean in the tele MQTT message? They are identified by "BME280-76" and "BME280-77" and one level below that in the JSON is "Temperature" and "Humidity".  Is the issue that it's a dual function sensor?  I have a print running now so I don't want to mess with it but I'll try it as soon as it's done.

**Comment by jneilliii** [comment]
Yeah, so that is something I've never tested before using BME280. It could be something to do with the dash, because I've only tested with DHT11 (which is what I had available and reports temperature and humidity). It should work the same but very well could be some random issue. Could you set the identifier to BME780-76, enable debug logging, enable polling of status, restart OctoPrint and then let it sit for a polling interval and lets see if it starts to log any data after a couple of polling intervals.

**Comment by ryancasler** [comment]
I guess I spoke too soon.  Using "BME280-76" did eventually start pulling data.  Guess I didn't wait long enough.  Sorry for the false alarm.

**Comment by jneilliii** [comment]
Documentation updated with the above commit and will be part of the next release version, currently available on the rc branch for review.
