### ISSUE TITLE
Sonoff with only 1 Switch can't be used in GCode Scripts

### ISSUE THREAD

**Issue by DocYester** [jneilliii/OctoPrint-Tasmota#53]
Sonoff with only 1 Switch can't be used in GCode Scripts

When you setup a wemos/esp device with tasmota 6.6.0.5 and have only one switch on it , is cant be used by gcode-scripts (before printing / after successful print) in octoprint.
It just does nothing ...
The Button works fine in Octoprint.

Wenn man einen Wemos d1 mini oder andere esp-basierte chips mit tasmota 6.6.0.5 verwendet und man hat nur einen schalter, kann dieser nicht in den scripten von octoprint verwendet werden.
Der Befehl ist in der Konsole sichtbar, aber wird nicht ausgeführt.
Der Button in der Titelzeile von Octoprint funktioniert ohne Probleme.

**Comment by DocYester** [comment]
![image](https://user-images.githubusercontent.com/46453559/71524290-2c9b3f80-28cd-11ea-8744-2218530f0c7d.png)

green works, red not

**Comment by jneilliii** [comment]
On those devices that don't work if you run the command `SetOption26 1` then use an index value of 1 it should work.

**Comment by DocYester** [comment]
Works - thanks

Should be written in the doc's instead of using no index
