### ISSUE TITLE
feature: Disable icon button

### ISSUE THREAD

**Issue by tablatronix** [jneilliii/OctoPrint-Tasmota#54]
I do not use this plugin, I only have it as a dependency for the auto shutdown and tplink, so now i have this useless spinning question mark that i do not need. Please allow this to be disabled.

![Screen Shot 2020-01-01 at 8 22 49 AM](https://user-images.githubusercontent.com/807787/71642410-40012e80-2c70-11ea-98a4-5f90b34dc197.png)

**Comment by jneilliii** [comment]
This plugin shouldn't be required if you're using tplink plugin.

**Comment by tablatronix** [comment]
Oh ok cause the automatic shutdown plugin says it is. Ill test again
