### ISSUE TITLE
Move System Commands and Connect/Disconnect logic to python code

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-Tasmota#55]
In order for future changes to Cura plugin for auto-powering on plugs need to change the auto-connect logic to the python side instead of the javascript side. While doing so, might as well do the same for disconnect and on disconnect commands as well. Also, need to make backlog_delay parameter optional in api calls.

**Comment by fieldOfView** [comment]
Hey, I did not mean my supporting your plugins to force you to refactor things :-/

> Also, need to make backlog_delay parameter optional in api calls.

Not necessarily, I have already added it to the parameters that are sent to the API here:
https://github.com/fieldOfView/Cura-OctoPrintPlugin/commit/0c359f7367a5c051b4463b4b1514c4639ba83fbc

See https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/141#issuecomment-575983934 and beyond for an explanation on how my code currently uses addresses the different plugins.

PS: I noticed though that the `backlog_delay` only gets included if there's a username included. I am not sure if that's intentional:
https://github.com/jneilliii/OctoPrint-Tasmota/blob/master/octoprint_tasmota/__init__.py#L187

**Comment by jneilliii** [comment]
Yeah, i noticed the backlog thing when I was testing, it's not intentional. This plugin is behind on a lot of the changes done in my other ones and needs to be adjusted anyway.

**Comment by jneilliii** [comment]
Slated for next release these changes will get integrated.  It will only require the ip and idx values passed to the api.

**Comment by steviehs** [comment]
Hmm... Maybe I am not really understanding that, but is this also related to the following behaviour I get: 
When I cancel a print - shortly after starting it, you discover "things" from time to time - it seems, the timeout for switching off by gcode remains still. I have set this to 600 seconds. So what happens: if I cancel a print (gcode for switching off Tasmota is also in the cancel part) and start a print... the power off sequence hits me....

**Comment by jneilliii** [comment]
Good point, not sure if I caught that in my latest updates, but you could test to see by installing thre plugin grin the url below and see if it still does the same. 

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.9.zip

**Comment by steviehs** [comment]
I guess you did not caught it, as I already use 0.8.9 because of the POW additions (which work great btw).

**Comment by jneilliii** [comment]
I've pushed a bunch of updates to that version since I started it, including integrating automatic power off options with abort shutdown pop-up.  Are you using that version?

**Comment by steviehs** [comment]
Hmm... I was using a version 0.8.9 I guess around November last year... dunno if there is a newer 0.8.9...

**Comment by jneilliii** [comment]
Correct, you were using an early development version.  Development has continued on that version and it's close to release now.  You can reinstall over your current one and it should be ok. I'm prepping it for official release and would love to get some additional testing by others prior.

**Comment by Wondro** [comment]
The plugin seems to be working great. I like the UI changes. I also got it to work with the cura plugin.

**Comment by steviehs** [comment]
looking forward to test it... unfortunately I found, that the actual Octolapse version stops when reading IP adresses in the GCode :-)

**Comment by jneilliii** [comment]
I don't know why the gcode would effect Octolapse unless he is monitoring for those same gcode commands.  @FormerLurker, does Octolapse do that or am I misunderstanding the problem here @steviehs?

**Comment by steviehs** [comment]
octolapse parses all gcode if waiting for gcode trigger and exits with "Can't parse gcode, multiple periods detected". This should be fixed in the next release.

**Comment by jneilliii** [comment]
ahhh, ok.  Issue on that side.

**Comment by FormerLurker** [comment]
@jneilliii, yes, the old version bit it when it encountered IP addresses as command parameters.  The new version should not do that.
