### ISSUE TITLE
No tasmota editor

### ISSUE THREAD

**Issue by lennvilardi** [jneilliii/OctoPrint-Tasmota#59]
Since 0.8.9 I don't have the possibility to access the Tasmota Editor....
The tasmota settings panel in plugins is nearly empty.
I tried to uninstall and reinstall it. 
Refresh with ctrl+f5. 
Restart the raspberry and shutdown and start.
![2020-02-20 18_03_09-Window](https://user-images.githubusercontent.com/10863269/74959695-5b382100-540b-11ea-90ab-db7a710aa16e.png)

**Comment by injectx** [comment]
Same problem here since v 0.8.9.

**Comment by umbynos** [comment]
Same Here

**Comment by jneilliii** [comment]
I'll have this fixed shortly guys.  I think I know what it is.

**Comment by jneilliii** [comment]
I just pushed an update to the 0.8.9 release.  If you guys reinstall it should be fixed now.  You can use the URL below in plugin manager.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/master.zip

**Comment by lennvilardi** [comment]
Thanks it works again :) and thanks for this great plugin !!!

**Comment by jneilliii** [comment]
Awesome and you're welcome, glad it was an easy fix.
