### ISSUE TITLE
[Request] Can no longer use hostname, MUST use IP

### ISSUE THREAD

**Issue by foosel** [jneilliii/OctoPrint-Tasmota#61]
OctoPrint-Tasmota version: 0.8.10
OctoPrint version: 1.4.0

Recently updated, had to reconfigure, and found I could not longer throw in my assigned hostname into the plug configurator because it explicitly checks for IPs, [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/4b78672c8b6038888481d327f005b08e1496ee99/octoprint_tasmota/templates/tasmota_settings.jinja2#L99) and [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/4b78672c8b6038888481d327f005b08e1496ee99/octoprint_tasmota/templates/tasmota_settings.jinja2#L104).

I usually don't assign fixed IPs to my IOT devices and instead just let my DNS setup handle stuff like this, so this is a tad annoying for this workflow.

Is there a chance to get back support for both IPs and hostnames here? :)

**Comment by jneilliii** [comment]
I don't remember putting that in there, I wonder if it got merged in from someone else's changes I incorporated. I have no issuse reverting that. Wouldn't you benefit from the mqtt version though?

**Comment by foosel** [comment]
Dunno, don't really need this as part of the overall HA system, I consider it more as a part of the printer and hence never even bothered hooking it up to either broker or HASS.

**Comment by jneilliii** [comment]
Changes applied and I just pushed an update. Because of my pihole implementation I can't test, but it should be working assuming name resolution works properly.
