### ISSUE TITLE
Status unknown since last update

### ISSUE THREAD

**Issue by paeppi88** [jneilliii/OctoPrint-Tasmota#62]
Tasmota 0.8.10
OctoPrint 1.4.0

Hey, first of all thanks for the development :)
Since the last update my Sonoff S20 with Tasmota has a problem showing me the correct status. An error message appears.

"Status unknown for 192.168.177.230. Double check IP Address\Hostname in Tasmota Settings."

I have to set the index to "1" to be able to switch the power socket via GCode. If I delete the index, the status display works perfectly, but I can't switch the power outlet by GCode anymore.

**Comment by jneilliii** [comment]
Did you enable SetOption26?

**Comment by paeppi88** [comment]
Thank you so much. Now it works fine.
First I had to update my power outlet.
