### ISSUE TITLE
Option to use backlog for delays

### ISSUE THREAD

**Issue by MakeNModify** [jneilliii/OctoPrint-Tasmota#63]
First of all thanks for your work and your great plugins.

Problem:
I would like to use "sudo shutdown now" to turn off my Pi and than kill the power.
From my understanding the delay used in the Plugin lets the Pi wait and than call the Power OFF command.
I would prefer or have the option to use Backlog and let Tasmota handle the delay.

Solution:
That would look like this:
`<IP>/cm?cmnd=Backlog%20Delay%2050%3BPower1%20OFF `
for a 5 second delay before powering off

More on Backlog:
https://github.com/arendst/Tasmota/wiki/Commands#using-backlog

Thank you :)
Max
_______________________
Edit: Sorry just had a look at the code (not a JS-Guy) and f you allready seam to use it so might also be user error

**Comment by jneilliii** [comment]
That's what the Use Countdown Timers option does.
