### ISSUE TITLE
Possible to launch a shell script afetr On/Off ?

### ISSUE THREAD

**Issue by zebons** [jneilliii/OctoPrint-Tasmota#64]
Hi,
I use Tasmota plugin to start my printer. As I have a webcam and a led bar, I'd be able to use the 'run system option' at start and stop.
I put the command 'sudo service webcamd start' and 'sudo service webcamd stop' as system commands abd it's work fine to start and stop my webcam.
To be able to manage also my leds, I write a script  : 
````
#!/bin/bash

#vérification si accès root
echo $(id -u)
echo $1
if [ "$(id -u)" != "0" ]; then
    echo "Il faut être root pour exécuter le script."
    echo "Usage: sudo `basename $0` [start/stop]"
    exit 1                                            #sortie
fi                                                  #fin if

#vérification passage de paramètre stop/start
if [ "$#" -ne 1 ]
then
    echo "paramètre attendu"
    echo "Usage: sudo `basename $0` [start/stop]"
    exit 1
fi
if [ $1 != 'start' ] && [ $1 != 'stop' ]
then
    echo "mauvais paramètre passé"
    echo "Usage: sudo `basename $0` [start/stop]"
    exit 1
fi

# Set up GPIO 4 and set to output
#echo "4" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio4/direction

if [ $1 == 'stop' ]
then
# Write output
    echo "1" > /sys/class/gpio/gpio4/value
    sudo service webcamd stop
fi
if [ $1 == 'start' ]
then
    echo "0" > /sys/class/gpio/gpio4/value
    sudo service webcamd start
fi
````
That script works fine when launched directly on the rpi connected via ssh (command : sudo /home/pi/scripts/Led_Webcam.sh start) but nothing happens when putting the same command into tasmota...
![image](https://user-images.githubusercontent.com/51046171/76209330-e8e48080-6201-11ea-8948-e47cac5b24c8.png)

What's wrong ?

**Comment by jneilliii** [comment]
Maybe related to the sudo command. When you run that via ssh are you prompted for a password?

**Comment by zebons** [comment]
yes a password is required the first time I launch the script

**Comment by zebons** [comment]
You are right, I add the user pi to the sudo group and now it's work fine
