### ISSUE TITLE
"Cancel Automatic Power Off Timer" is non-functional

### ISSUE THREAD

**Issue by fionnb** [jneilliii/OctoPrint-Tasmota#65]
I set the timer to 280s and the countdown runs, then nothing happens.
Printer still on, but can be switched off by clicking the icon in the top bar.

Version is 0.8.11 with octo 1.4.0

**Comment by jneilliii** [comment]
Try restarting octoprint

**Comment by fionnb** [comment]
There have been several restarts and updates since I have been here last time. The auto shutdown still does not work. I mitigated this by using a webhook event plugin that sends a trigger event to node-red on print-finished which in course starts a 300s cooldown timer and then a switch off event to the sonoff switch. But it would be of, of course, a lot less complicated if your plugin worked. :-)

**Comment by jneilliii** [comment]
Thanks for finally responding. Can you please post screenshots of your plugin settings so that I can make sure I've got everything the same for testing?

**Comment by fionnb** [comment]
![gkrellShoot_05-03-20_120532](https://user-images.githubusercontent.com/4482889/80911424-92457f80-8d36-11ea-8fd9-d16e723a2675.png)

Sorry for having been late to reply, things have become complicated these days and I had other priorities to pay attention to.

**Comment by jneilliii** [comment]
Yep, I see the problem and I could have worded this better. You need to enable the option `Print Complete Off`.

![image](https://user-images.githubusercontent.com/5249455/80915232-feb48480-8d1e-11ea-8c09-e955deca7a11.png)
