### ISSUE TITLE
Not seeing controls in Octopod after Octoprint upgrade

### ISSUE THREAD

**Issue by bdwilson** [jneilliii/OctoPrint-Tasmota#66]
There used to be an area where custom controls are now. Any way to get it back?

**Comment by jneilliii** [comment]
Sorry, but not sure I understand since I don't use octopod.

**Comment by bdwilson** [comment]
It may be an octopod issue. Here is the section that would show plugin controls, but now it just references custom control settings. https://bubba.d.pr/y625j5

**Comment by jneilliii** [comment]
And what buttons would show up there from this plugin? The one's that are normally in the navbar of the full web interface? I think this might be an octopod issue.

**Comment by bdwilson** [comment]
Just a power plug button. I agree I think its an OctoPod issue. I opened an issue with Octopod https://github.com/gdombiak/OctoPod/issues/279
