### ISSUE TITLE
Status Polling crashes Octoprint when set to 0

### ISSUE THREAD

**Issue by thoogland89** [jneilliii/OctoPrint-Tasmota#67]
May want to have the status polling set to 1 min minimum. Setting to the default of 0 causes Octoprint to get overloaded and crash. Took me a while to figure out what was going on.

**Comment by jneilliii** [comment]
Thanks. I'll take a look at handling this from the UI side by setting minimums on the inputs and changing the default setting.

**Comment by pazu86** [comment]
I think this is what has been killing my setup as well - is there a way to manually change that at the moment so I can keep using the plugin?

**Comment by jneilliii** [comment]
The setting is the Tasmota plugin's settings when you enable the polling status. Just change it from 0 to something else, 1 or greater.

![image](https://user-images.githubusercontent.com/5249455/79299026-e9cb9a80-7eb0-11ea-8e37-ff0539562ad0.png)

If you can't get OctoPrint to load, then setting that in config.yaml manually would be a way to go, or possibly clearing the plugin's data in the plugin manager using the new eraser button in version 1.4.0 of OctoPrint when you get OctoPrint to load in safe mode.

**Comment by pazu86** [comment]
ah perfect - thanks, will check this once current print finishes

**Comment by pazu86** [comment]
So mine was set at 5 (and enabled), I've disabled polling and everything has staying working. So maybe related but not the same issue?

**Comment by jneilliii** [comment]
That's odd, sounds like a different issue then. Any errors in the logs?

**Comment by pazu86** [comment]
Not that I can see - when tailing the main log, it just stalls after you try and load the main GUI initially, no errors, service is still there but not responding. Running in safe mode works fine and by process of elimination that’s what I’ve narrowed it down to.

I thought it might have been an SD card going so I tried a new card, fresh image and same issue.

Are there any other logs I should be looking at?

Matt Hodder
0422 610 560
________________________________

**Comment by jneilliii** [comment]
Since it's a ui related issue, I'd check the browser's developer console.
