### ISSUE TITLE
Graph values are completely off

### ISSUE THREAD

**Issue by chimcen** [jneilliii/OctoPrint-Tasmota#68]
Hi,

thank you for this great plugin.
But i've a problem - the graph values are completely off. Here you can see a screenshot for one printjob. the powersocket (Gosund SP111 v1.1 - Tasmota 8.2) shows me at the powermeter values between 40-280W during the print time. Your pluginbs graph shows only this:
 
![image](https://user-images.githubusercontent.com/22658487/78784377-8966c580-79a5-11ea-89ad-7224c2865fbf.png)

Can you help me?

**Comment by jneilliii** [comment]
This feature is fairly new and I haven't got much feedback on it yet. My best guess it's because you don't have polling enabled. It only gets the data when the status of the plug is checked if I remember correctly. It's not a real time monitor like you would see with tasmota web interface.

**Comment by chimcen** [comment]
Oh, you're right - polling was off... though it polls data for the graph automaticly in background...
