### ISSUE TITLE
turn off printer after print has finished

### ISSUE THREAD

**Issue by Fixel2012** [jneilliii/OctoPrint-Tasmota#70]
Hi,
first of all thanks for this awesome plugin!

Power on/off from the GUI works fine so far!

My goal is to automatically power off the Printer after completing a print. I didn't find a solution inside the documention except for M80/M81.

Can't I simply use the internal octoprint print status to power off the printer some how?

I hope my question is not too dumb.

Edit: what does "Print Complete Off" do? It's also not mentioned inside the Documentation.

**Comment by jneilliii** [comment]
Currently that's the only way; using gcode triggers, which can be added to octoprint's gcode scripts.

**Comment by jneilliii** [comment]
I take that back, you could use off on idle options and it will achieve the same goal.

**Comment by Fixel2012** [comment]
I figured out how to use it with the gcode now. The hint adding them to the scripts helped me.

Thank you very much for the help and also the great Plugin! :)
