### ISSUE TITLE
power on when connect pressed

### ISSUE THREAD

**Issue by brandonscholet** [jneilliii/OctoPrint-Tasmota#72]
Would it be possible to have an option where if you try to connect, and it doesn't work, then it turns on the power and then tries again?

**Comment by jneilliii** [comment]
Just adding a note for myself, this can be accomplished by adding an event monitor for `Connecting`.

**Comment by jneilliii** [comment]
This has been completed in the above commit and will be included in the next release. If you want to try it out you can install by copying/pasting the URL below into Plugin Manager > Get More > ...from URL and clicking install.
```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/develop.zip
```
