### ISSUE TITLE
Feature Request - API Control

### ISSUE THREAD

**Issue by houseofbugs** [jneilliii/OctoPrint-Tasmota#73]
Any chance we can see an API like the PSU Control plugin? Would go great with the OctoFarm software we use. https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/API

**Comment by jneilliii** [comment]
There actually is, it's just not documented. It's what the button press uses in the navbar, and what thre cura/ octoprint connect plugin uses as well. Check here for an example. 

https://github.com/jneilliii/OctoPrint-Tasmota/blob/05954c5a5d348a39b69a81ff378c8b3578d6ae88/octoprint_tasmota/static/js/tasmota.js#L361

**Comment by jneilliii** [comment]
BTW, all my power plugs are pretty much the same relative to this method of sending the commands to the server side, with minor variations like relay number for tasmota.

**Comment by NotExpectedYet** [comment]
> BTW, all my power plugs are pretty much the same relative to this method of sending the commands to the server side, with minor variations like relay number for tasmota.

Thanks for pointing that out, I can put some pre-sets in for things like this :)

**Comment by jneilliii** [comment]
Added to the wiki here on this plugin.

https://github.com/jneilliii/OctoPrint-Tasmota/wiki/API
