### ISSUE TITLE
Automatic Power Off not working

### ISSUE THREAD

**Issue by Sindel** [jneilliii/OctoPrint-Tasmota#74]
Hey, first of all thanks for the plugin, it's great! But both options Automatic Power Off and Enable Automatic Power Off of Enabled Relays do not work for me.
I left the printer idle for a long time and it never went off. How should it work? There is no documentation about it.

**Comment by jneilliii** [comment]
Can you share a screenshot if both the general plugin settings and the plug editor? You should enable both the general setting and the option in the plug editor.

**Comment by kreuzhofer** [comment]
I see the same issue. Enabled both options and turned the printer on via the lightning button in the upper status bar. Then waited but the printer never shut off.

**Comment by jneilliii** [comment]
This may just be a timing issue or I totally got the workflow logic wrong. Can you restart OctoPrint and see if that has any effect?

**Comment by jneilliii** [comment]
I just noticed something in that screenshot. I think I forgot some fields in settings. Let me dig into this deeper.

**Comment by kreuzhofer** [comment]
Thanks, would be great if you could fix that, I am just writing a script to make a video about this plugin on my YouTube channel.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by jneilliii** [comment]
Word, I plan on looking at it as soon as possible. Still on the job ATM.

**Comment by jneilliii** [comment]
Ok, I see now the difference between the way I did it in this plugin versus the TP-Link plugin. It's more of a automatic power off on print complete timer instead of an idle timer. I think this was because this plugin's changes were done prior to the TP-Link one but unpublished. I'm going to migrate the exact logic from TP-Link over to this plugin because I've been real happy with how it works for me.

**Comment by kreuzhofer** [comment]
So cool, thanks!

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by kreuzhofer** [comment]
Btw I am still wondering if starting the printer manually before you can start a print is something that could be changed. I would actually love to send my gcodes via CURA and have M80 in the start gcode

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by jneilliii** [comment]
@kreuzhofer if you use the OctoPrint Connection plugin in Cura it will detect this plugin installed and automatically power on for you.

**Comment by kreuzhofer** [comment]
I've just tried this and CURA still seems to see the printer as offline and just wants to queue the print so I have to first power on the printer and then start the print from Octoprint. Is this maybe also something that your other plugin supports, but not the Tasmota version?

**Comment by Sindel** [comment]
I agree with Kreuzhofer, that does not work for me as well. Have to start the printer from Octoprint and then after it connects it is possible to print.

**Comment by jneilliii** [comment]
It should work. Once the plugin is installed on OctoPrint the Cura plugin should show the following in the "printer settings".

![image](https://user-images.githubusercontent.com/5249455/81470062-9e0dc780-91b6-11ea-9ffa-922e31b04230.png)

I bet you guys have Ender 3s and the controller board is getting back-powered by the USB connection from the Pi? That might be why because the printer is "connected" and that's what the Cura plugin is looking for.

In any case this should be discussed in #72 

Relative to this ticket, I think I just finished up the idle timer stuff, if you guys would test prior to officially releasing that would be great. You can use the URL below in plugin manager to give it a go.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.13.zip

**Comment by Sindel** [comment]
Wonderful, it works great now! I tested the idle function and the Cura function to turn it on and both are working! In any case I am using an Ender 5 with the power pin blocked on the data cable.
Thanks for the Cura settings, that was my mistake.

**Comment by jneilliii** [comment]
Awesome. Going to check to see if there are any other quick fixes to incorporate and will officially release soon.

**Comment by kreuzhofer** [comment]
I don't get it. How did you get CURA to show this option? I am using latest CURA and latest Plugin and it does not work to start the printer. Do I have to power the Ender 3 board from the PI? I have disabled the backpowering by taping the plus cable.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by jneilliii** [comment]
What are the versions of the Cura and the Cura plugin you have @kreuzhofer?

**Comment by kreuzhofer** [comment]
Cura 4.6.1 and Octoprint Connection 3.5.12

I just tested it with the 0.8.13 version and guess what, it shows me the option! Thanks for fixing this. Going to give it some tests now...

**Comment by kreuzhofer** [comment]
Cool the Auto off after timeout and auto on with CURA works fine! I think you can release this new build. I will mention it in my video next week if you can release it until Friday next week.

**Comment by jneilliii** [comment]
Awesome, releasing now, that's 3 confirmed users without issues...thanks.

**Comment by jneilliii** [comment]
@kreuzhofer if you don't mind me embedding your video when you're done I'd love to include it in the readme or maybe in the wiki..

**Comment by kreuzhofer** [comment]
Thanks, I will send you the link next week Friday. And Thanks for being super responsive. Whats your first Name? Can I Mention that?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jneilliii** [comment]
Sure, it's Jim. Active in the community forum and now discord.

**Comment by kreuzhofer** [comment]
👍 thanks! Great to have you, this is really amazing!

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by kreuzhofer** [comment]
I have one little remark about the CURA connection. It worked for me when I restarted CURA and Octoprint exactly one time. When I tried it a second time, the printer is switched on but CURA waits forever in this dialog:
![image](https://user-images.githubusercontent.com/1763467/81493204-da1c5780-929e-11ea-9e7f-52d40387db0f.png)
And this can only be fixed when restarting OctoPrint and CURA.

**Comment by kreuzhofer** [comment]
I've done a few more tests. After restarting everything another time, it worked for tree prints in a row. Very strange. I will check if this behaviour comes up again...

**Comment by jneilliii** [comment]
It can be finicky sometimes with the connection option from the printer manager, etc. I think there used to be an issue that it wouldn't work until after setting in printer settings and then restarting Cura, but I thought fieldOfView fixed that. You may want to pop over to his repo and provide logs, etc. if you still experience the problem.

https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues
