### ISSUE TITLE
Single Relay Devices, Option for GCODE Trigger?

### ISSUE THREAD

**Issue by Quintin9801** [jneilliii/OctoPrint-Tasmota#75]
In this latest version of Octoprint-Tasmota, I noticed my relays not being triggered via my start and end gcode scripts. With some investigation of this problem, I found that single-relay Devices use a blank index instead of an index of 1 now. this means my code trigger is missing an argument.

**Old** GCODE Commands for triggering single relay devices:
On `M80 192.168.1.173 1`
Off `M81 192.168.1.173 1`

**NEW** GCODE Commands for triggering single relay devices:
On `M80 192.168.1.173`
Off `M81 192.168.1.173`

When sending the **old** GCODE Command (with the additional index argument) The response is:
`Send: M80 192.168.1.173 1`
`Recv: echo:Unknown command: "M80 192.168.1.173 1"`
`Recv: ok`

When sending the **New** GCODE command (Without the additional index argument) the response is:
`Send: M80 192.168.1.173`
`Recv: echo:Unknown command: "M80 192.168.1.173"`
`Recv: ok`

Here is my most recent log:
[https://pastebin.com/F6HkZWq5](url)

**Comment by jneilliii** [comment]
Try enabling SetOption26 on your Tasmota and put 1 in for the index. You can put 1 in the Index and press the Test button and I think it will give you an option for the plugin to enable the option for you as well.

**Comment by Quintin9801** [comment]
This worked perfectly, thank you!
