### ISSUE TITLE
Can't modify relays at all

### ISSUE THREAD

**Issue by pReya** [jneilliii/OctoPrint-Tasmota#77]
Love your plugin, however it stopped working for me. After reinstalling the plugin, I enter the full topic into the input and press "Save". After that I cannot modify any of the relays. I can't add a new one, modify the existing one or delete the relay. Nothing happens when I click the buttons. Console shows two errors, which already appear during initial load of OctoPrint:
<img width="632" alt="Screenshot 2020-05-20 20 36 35" src="https://user-images.githubusercontent.com/4677417/82484048-a54ba400-9ad9-11ea-9511-544f98e45278.png">

Any ideas how I could solve this?

**Comment by jneilliii** [comment]
Looks like maybe the configuration got corrupted. If you manually edit your config.yaml file on your pi AMD remote the tasmota settings from the plugin section it may resolve this issue. Also, if you can share a screenshot of your settings.

**Comment by pReya** [comment]
The config section for tasmotaMQTT:
`tasmota_mqtt: null`

Can I somehow initialize this config manually to a sane value? Anywhere I can find a proper filled out config object to copy and modify for my case?

**Comment by jneilliii** [comment]
Yep, that's the issue. It's caused by a bug in the core octoprint, slated to be fixed in the next release. If you just remove that entire line from your config.yaml and restart octoprint it will resolve the issue.
