### ISSUE TITLE
Connected devices can't be controlled by vis anymore

### ISSUE THREAD

**Issue by copperfield74** [jneilliii/OctoPrint-Tasmota#79]
Hi, today I installed your plugin and configured it.
I was able to to turn these on and off within Octoprint...BUT within my IOBroker Vis tool I wasn't able to controll these anymore. Alexa was still able to controll the devices but my vis is dead.
To be sure that this plugin is the problem I included a light switch that I'm sure is working right now... the same problem. After investigating this behaviour I found out that within IOBroker a new switch is introduced called POWER1 and my links are all on the switch POWER. Is there a reason that it doesn't take the old power switch?

Regards

**Comment by jneilliii** [comment]
Did you enable SetOption26?

**Comment by copperfield74** [comment]
It popped up when I activated the devices and if I remember correctly it had to be activated....so YES!
I found out that when you set SetOption26 to 1 that messages are send to POWER1. Is it a must?

**Comment by jneilliii** [comment]
It's not completely. Manually turn that off and clear your index, save and you should be good.

**Comment by copperfield74** [comment]
Thanks for your ultra fast response! Premium support from your side. Highly appreciated.

**Comment by copperfield74** [comment]
There is one other thing that I noticed. All my connected devies are green in Octoprint and the polling is set to 1min. But when I turn of the devices the status isn't synchronized to Octoprint, so even when they are OFF Octoprint is still green

**Comment by jneilliii** [comment]
Consider becoming a Patron to receive continued support and future plugin development... lol. As for the out of sync status. That usually will straighten itself out, but you may have to actually restart octoprint after setting the polling option or changing how often it's checking.

**Comment by jneilliii** [comment]
Just a heads up, another option is using the TasmotaMQTT plugin for real-time updates of status as the plugin can subscribe to updates sent by the device directly versus having to poll for status updates.

**Comment by copperfield74** [comment]
Thanks, but how do I configure TasmotaMQTT? I can't enter the MQTT server IP and in the manual there are no prerequirements.

**Comment by jneilliii** [comment]
https://github.com/jneilliii/OctoPrint-TasmotaMQTT#prerequisites
