### ISSUE TITLE
What is the "sensor" field for?

### ISSUE THREAD

**Issue by cayetano** [jneilliii/OctoPrint-Tasmota#80]
In interface show a fiel d ñame d “sensor” .... What is the "sensor" field for?
Thanks

**Comment by jneilliii** [comment]
Tasmota devices have the ability to add sensors like a BME280 or  DHT11. If you have a sensor connected and enter that sensor identifier (ie BME280) in that field, the plugin will be able to pull that sensor data and graph it on a tab.
