### ISSUE TITLE
Problems with auto off

### ISSUE THREAD

**Issue by ultimase** [jneilliii/OctoPrint-Tasmota#81]
Followed the video online here: https://www.youtube.com/watch?v=mhabOaa92-0&t=317s
And I can print directly from cura and I've configured it the same as the video. The switch tests correctly in setup (Tasmota device responded and is configured properly) and I can turn on the switch and turn off the switch on the main page of Octoprint, but for some reason I cannot get the printer to shut off after a print.

I had thought perhaps Cura wasn't allowing the printer to shut off if I kept it open, but leaving the window open or closing the program does not appear to have any affect. Starting the print directly within octopi doesn't appear to have an effect either.

The IP address is correct and tested as above, I just deleted it, though it is internal, but I guess you can never be too safe.

![octoprint2](https://user-images.githubusercontent.com/55076493/85677480-6ed6eb00-b67c-11ea-8421-e8c78a4bf31a.jpg)
![octoprint](https://user-images.githubusercontent.com/55076493/85677486-70081800-b67c-11ea-9644-1aa4b9f3252d.jpg)

**Comment by ultimase** [comment]
well ok that was weird, I opened octopi to heat the printer head to remove the filament for the night, and while it was doing that I installed some other plugins that I was considering. After a few that I installed the printer just shut itself off...

So I'm doing something right, and something very wrong.

**Comment by jneilliii** [comment]
Sometimes restarting OctoPrint ends up getting things back in sync as it pertains to settings changes to the plugin, so my assumption is that it took after you installed one of those other plugins and restarted OctoPrint.

**Comment by ultimase** [comment]
Didn't have time to do a small test print to see if it would shut off following the print. Will get to that shortly.

**Comment by ultimase** [comment]
Just finished a quick print, and unfortunately, it's not shutting off. Temps down to 38 degrees on the print bed based on reading the lcd screen. Oddly both cura and octoprint don't have any updated temps from after the print finished.

**Comment by jneilliii** [comment]
So if octoprint is losing its connection and the temperature reporting never gets below the set threshold not sure there is much the plugin can do to resolve that.

**Comment by ultimase** [comment]
The weird thing is, Octoprint appears to be connected throughout the print. But when the print completes it doesn't seem like Octoprint continues to update the temperature. Since Octoprint never updates the temperature, then it never drops below 50 and wouldn't trigger the switch to turn off. 

I'll try another small print with brave off to see if it's something brave is blocking. Otherwise, it looks like I'll need to try to contact someone over at octoprint.

**Comment by ultimase** [comment]
This appears to be a thing with octoprint and the ender 3 v2.

https://community.octoprint.org/t/temperature-reporting-now-working-with-new-ender-3-v2/21053/16

Unfortunately, I can't figure out how to get the file they posted to octopi without errors, via the plugin manager and uploading it.

**Comment by ultimase** [comment]
I'll go ahead and close this, as this was a known issue, the thread above has a link to the file needed and my clumsy efforts to figure out where to put it.
