### ISSUE TITLE
Turn On/Off over gcode not works

### ISSUE THREAD

**Issue by micharaze** [jneilliii/OctoPrint-Tasmota#83]
I am not able to turn off my tasmota device over the gcode. I am getting the following message:

Send: M81 192.168.178.32
Recv: Deletion(bin) failed.
Recv: ok

In the OctoPrint settings I let the index blank, otherwise the Tasmota plugin was not working at all.

OctoPrint Version 1.4.0
Tasmota Plugin (0.8.13)
Sonoff-Tasmota 5.11.1

**Comment by jneilliii** [comment]
> Deletion(bin) failed.
I'm not familiar with that response. But the issue is probably related to SetOption26 and a blank index.  Enter 1 in index value and press the Verify button. It should prompt you to enable SetOption26 on your tasmota, and once done it should work with `M81 192.168.178.32 1`.

**Comment by micharaze** [comment]
Thanks, it worked! But how can I put the Tasmota device ON when Octoprint is not connected? Sure I can use the Button on the Navbar but over GCODE its not possible. 

My situation: 
I am using Octopad and I created commands (over GCODE) to put On and Off the Tasmota device. On is not problem during Octoprint is connected to the printer. But when my Printer is Off i cannot activate the On command. Any suggestions?

**Comment by jneilliii** [comment]
Yeah, that's harder to handle. There are some printers that are powered from the USB connection from the Pi, which allows the printer to stay connected even though the PSU is powered down. I haven't really found a good way around the situations where that connection doesn't exist.

**Comment by jneilliii** [comment]
It's a similar request to #72
