### ISSUE TITLE
TypeError: turn_off() takes exactly 3 arguments (2 given)   

### ISSUE THREAD

**Issue by rknobbe** [jneilliii/OctoPrint-Tasmota#86]
Tasmota never turns off my outlet automatically with M81 or after idle or disconnect. Turning on works fine, either with the icon or with M80. Turning off with the icon works fine.

`2020-08-25 13:41:55,862 - octoprint.plugin - ERROR - Error while calling plugin tasmota                                 Traceback (most recent call last):                                                                                        
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 230, in call_plugin           result = getattr(plugin, method)(*args, **kwargs)                                                                     File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 279, in on_event             self.turn_off(plug["ip"])                                                                                           TypeError: turn_off() takes exactly 3 arguments (2 given) `

`    tasmota:                                                                                                                    _config_version: 8                                                                                                      arrSmartplugs:                                                                                                          -   autoConnect: true                                                                                                       autoConnectDelay: '30'                                                                                                  autoDisconnect: true                                                                                                    autoDisconnectDelay: 0                                                                                                  automaticShutdownEnabled: false                                                                                         backlog_off_delay: '5'                                                                                                  backlog_on_delay: 0                                                                                                     currentState: 'on'                                                                                                      displayWarning: true                                                                                                    event_on_disconnect: true                                                                                               event_on_error: true                                                                                                    gcodeEnabled: true                                                                                                      gcodeOffDelay: '5'                                                                                                      gcodeOnDelay: 0                                                                                                         icon: icon-bolt                                                                                                         idx: '1'                                                                                                                ip: 192.168.1.213                                                                                                       label: CR10                                                                                                             label_extended: 'CR10<br>ApparentPower: 18<br>Power: 12<br>Yesterday:                                                       0.943<br>TotalStartTime: 2020-08-15T15:00:26<br>Current: 0.146<br>Voltage:                                              122<br>Factor: 0.69<br>ReactivePower: 13<br>Total: 19.144<br>Today:                                                     4.428'                                                                                                              off_color: '#FF0000'                                                                                                    on_color: '#00FF00'                                                                                                     password: ''                                                                                                            sensor_identifier: ''                                                                                                   sysCmdOff: false                                                                                                        sysCmdOffDelay: 0                                                                                                       sysCmdOn: false                                                                                                         sysCmdOnDelay: 0                                                                                                        sysRunCmdOff: ''                                                                                                        sysRunCmdOn: ''                                                                                                         thermal_runaway: true                                                                                                   unknown_color: '#808080'                                                                                                use_backlog: true                                                                                                       username: admin                                                                                                         warnPrinting: false                                                                                                 event_on_disconnect_monitoring: true                                                                                    event_on_error_monitoring: true                                                                                         polling_enabled: true                                                                                                   thermal_runaway_monitoring: true                                                                                 
`
[octoprint-1.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5126429/octoprint-1.log)

**Comment by rknobbe** [comment]
Octoprint version 1.4.2
Tasmota version 0.8.14

**Comment by jneilliii** [comment]
This should be fixed with the above commit. If you don't mind testing and verifying you no longer get the error that would be great. It appears it was related to the power off on disconnect option for one of your plugs probably. You can install copying/pasting the URL below in Plugin Manager > Get More > ...from URL and clicking the install button.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.15.zip
```

**Comment by rknobbe** [comment]
Installing 0.8.15 ended up with a very unstable Octopi, including flooding of log messages indicating "notification cleared" or something similar and some kind of weird effect in the web UI where the "Save" button appeared to select on its own -- rapidly.  Uninstalled and running another print with 0.8.14 before trying again.

**Comment by jneilliii** [comment]
Your log had a bunch of errors from other plugins too, and it appears there was a bunch of api calls, which I assume is octodash or some other client connection. You may be experiencing that issue of instantly powering off because of the on disconnect monitoring. There's a bug with some boards that get power from the usb of the pi, and when you power on, the connection gets dropped and triggers the power off. If your printer is back powered over usb I recommend disabling that option and only use error monitoring.

**Comment by jneilliii** [comment]
please open a new issue if you're still experiencing issues with the 0.8.15 version that I just released officially.
