### ISSUE TITLE
Feature Request: Electricity Consumption Calculation

### ISSUE THREAD

**Issue by war1000** [jneilliii/OctoPrint-Tasmota#87]
The tplink plug plugin has a electricity calculation/reporting function. Can we please have that? :D Thank you!

**Comment by jneilliii** [comment]
I thought I did already add that. The caveat being, you have to be running a POW device that provides that information.

**Comment by war1000** [comment]
> I thought I did already add that. The caveat being, you have to be running a POW device that provides that information.
In the configuration, I didn't find any place to put in the kwh cost. In the report it shows Current, Power, Total.

![image](https://user-images.githubusercontent.com/57807544/93812399-8a23a900-fc1f-11ea-973e-0269d6bb4ddb.png)

**Comment by jneilliii** [comment]
Oh, I understand now. Yeah, I can add that at some point.

**Comment by jneilliii** [comment]
I've made a little progress on this request. I have the cost rate added to settings and getting the start and end total kWh from the tasmota and calculating the overall cost for a print at the file level.

![image](https://user-images.githubusercontent.com/5249455/105575204-f6cac380-5d37-11eb-8a66-706b0d3bc8b6.png)

Just need to add the graphing side for the cost now.

**Comment by jneilliii** [comment]
This has been completed in the above commit and will be included in the next release. If you want to try it out you can install by copying/pasting the URL below into Plugin Manager > Get More > ...from URL and clicking install.
```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/develop.zip
```

**Comment by war1000** [comment]
> This has been completed in the above commit and will be included in the next release. If you want to try it out you can install by copying/pasting the URL below into Plugin Manager > Get More > ...from URL and clicking install.
> 
> ```
> https://github.com/jneilliii/OctoPrint-Tasmota/archive/develop.zip
> ```

Thank you very much! it is working. Quick question...is the cost in cents or $...i.e. should i put 8.5 for c8.5 or 0.085? Thanks!

**Comment by jneilliii** [comment]
No units defined, so you put in whichever makes more sense. I put in as cents being a whole number for testing.

**Comment by war1000** [comment]
> No units defined, so you put in whichever makes more sense. I put in as cents being a whole number for testing.

Here is what I am getting now. 
![image](https://user-images.githubusercontent.com/57807544/105613835-fb709580-5d92-11eb-9b4f-e879f435b3b7.png)

**Comment by jneilliii** [comment]
Yeah, your plug's been on for a while I suppose you might want to use the other 0.085 format maybe. It's literally a direct multiplication of Total (kWh since initial reflashing of plug or resetting) by your entered cost rate.

**Comment by jneilliii** [comment]
that input might turn red, I was going to increase the stepping value so it doesn't do that, but it shouldn't prevent you from saving.

**Comment by war1000** [comment]
> Yeah, your plug's been on for a while I suppose you might want to use the other 0.085 format maybe. It's literally a direct multiplication of Total (kWh since initial reflashing of plug or resetting) by your entered cost rate.

Thanks...yeah I figured right after posting. The Kasa plug had a way to reset it. Not sure how to reset power consumption info in Tasmota. Will do some research.

**Comment by jneilliii** [comment]
I'm sure it's some simple command. But if you expand the details of the file that you print it will show you the cost of just that file during the last print. The math there is the difference in Total kWh from print start and print end multiplied by your rate.

**Comment by war1000** [comment]
Ok. I will try this on the next print. It is not retroactive and the last print was 14 days ago. Thanks for implementing this!

**Comment by jneilliii** [comment]
Cool. Since the feature has so far proven to be working, I'm going to go ahead and close now. Once I release final version with these improvements you should get an update notice during the normal software update checks and not be on the rc1 version anymore.
