### ISSUE TITLE
[Feature Request] Generic REST Commands

### ISSUE THREAD

**Issue by sreknob** [jneilliii/OctoPrint-Tasmota#88]
Firstly, thank you for this and all you do!

I currently use Tasmota for my printer power but am slowly migrating to ESPHome for most of my ESP devices. They also can use RESTful commands like Tasmota.

I am wondering if you could add in an advance config that allows me to just specify a ON/OFF REST URL/PATH which could make this plugin generic to any outlet that can be REST controlled. 

For example, just allow me to input:

ON --> "http://192.168.2.10/switch/cloudbar_3/turn_on"
OFF --> "http://192.168.2.10/switch/cloudbar_3/turn_off"

The documentation for ESPHome's REST API is here: https://esphome.io/web-api/index.html

Thanks for your consideration :-)

**Comment by jneilliii** [comment]
Fair point, but I've developed so much within this plugin for Tasmota specific environment, it would probably make more sense to create a separate ESPHome specific plugin.

**Comment by sreknob** [comment]
Thanks for the response :-)
True. I was just looking through the code and I see that you use backlog for instance.
There is simplicity with Tasmota because it is so standardized, ESPHome sensors and switches can be named anything so need to construct any statements from user input of sensor and switch names.
I was trying to find a way to send a curl POST command using G-code triggers to try and replicate some of the function of this plugin. (the extra features and G-code M80/81 commands that are used in the plugin are so elegant) but I couldn't find a way to make it work. Is there any easy(ish) way to send a curl command on a G-code trigger?
Thanks you!

**Comment by jneilliii** [comment]
Sorry for not getting back yet. You also have the option of `GCODE System Commands]( https://plugins.octoprint.org/plugins/gcodesystemcommands/). Works pretty much the same with custom gcode commands.

**Comment by sreknob** [comment]
Wow - great, thank you for getting back to me!
I think I will try and stick with using one of your smart plug plugin-ins using "run system command" configuration as it has all the bells and whistles like thermal protection and the nice toggle along the status bar.
Thanks again!
