### ISSUE TITLE
port

### ISSUE THREAD

**Issue by Lawrencezarb** [jneilliii/OctoPrint-Tasmota#9]
My sonoff is configured with a port, ie 192.168.1.20:2020, but it does not seem to work with this plugin, as I get the message on Octoprint that the device statsu is unknown.

**Comment by jneilliii** [comment]
Can you let me know how you configured that port in Tasmota?  Once I can configure mine the same way I'll check into adding the functionality.

**Comment by Lawrencezarb** [comment]
Its under user_config.h

 

 

// -- HTTP ----------------------------------------

#define USE_WEBSERVER                            // Enable web server and wifi manager (+62k code, +8k mem) - Disable by //

  #define WEB_SERVER           2                 // [WebServer] Web server (0 = Off, 1 = Start as User, 2 = Start as Admin)

  #define WEB_PORT             3131                // Web server Port for User and Admin mode

**Comment by jneilliii** [comment]
Thanks.  Just to confirm, if you enter the ip in the plugin settings as 192.168.1.20:2020 it doesn't work?  Based on the code, that should work unless I'm missing something. If you have tried that, please enable debug logging and try again and send a copy of your octoprint.log and plugin_tasmota_debug.log.  I just tested with 192.168.1.20:80 (default port) and that is working for me.

**Comment by Lawrencezarb** [comment]
That is exactly as I enter it, attached are the logs. Hope this helps.

**Comment by jneilliii** [comment]
I don't think github allow attachments from email replies, they didn't come through.

**Comment by Lawrencezarb** [comment]
Try this, I have attached directly via github.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1538422/plugin_tasmota_debug.log)
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1538424/octoprint.log)

**Comment by jneilliii** [comment]
Ok, I see what's happening.  The web sever is responding that you need to include a username and password to send the commands.  Did you set those fields in the settings?

**Comment by Lawrencezarb** [comment]
Yes I did. I edited the log to show xxxxx as the password not the one I set.

 

I even had the same problem when I removed to login/password

**Comment by jneilliii** [comment]
Yeah, I assumed the xxxx was replacing those, but the username field appears blank.  Set that to admin and it should in theory work, unless you also changed the admin username from the user_config.h file (assuming that's an option).

**Comment by Lawrencezarb** [comment]
That’s got it working. I think because I saw admin already populated in the field I did not think to write over it.

 

Thanks for your time and effort.

**Comment by jneilliii** [comment]
No problem.  It actually made me realize that I wasn't setting admin in the username field by default and it was just there as a placeholder in the html page.  I adjusted that and now by default admin will be populated.  BTW, if you're using MQTT; I'm in the process of creating an OctoPrint plugin to manage these over MQTT.  Right now it's just a simple framework but is able to toggle the power on and off from a button in the navbar.  Requires the [MQTT](https://plugins.octoprint.org/plugins/mqtt/) plugin to be installed first. Any feedback welcome over on its [repository](https://github.com/jneilliii/OctoPrint-TasmotaMQTT).
