### ISSUE TITLE
Same-Day Date/Time Range Power Graphing Failure

### ISSUE THREAD

**Issue by DodgeDeBoulet** [jneilliii/OctoPrint-Tasmota#92]
OctoPrint 1.4.2 on Raspbian Buster, RPi 4, Tasmota plugin 0.8.15. Have not yet migrated to Python v3.

When graphing power consumption, selecting a time range with the start and end on the same day does not display a graph. For example, I'm using a smart plug on my printer to monitor power consumption. The plug was turned on at 8am and as I write this (close to 11am) I can see power consumption graphed over the last 24 hours, and the date range displayed is 10/**15**/2020 8:00am through 10/**16**/2020 11:00am. The graph shows data collected starting as of 8:00am on 10/**16**/2020.

If I manually narrow the range to start at 10/**16**/2020 8:00am and end at 10/**16**/2020 11:00am, no data shows. The Update button does not affect the display.

If I manually set the range starting at 10/**15**/2020 11:59pm to 10/**16**/2020 11:00am, the graph displays. No start time on the same day as the end time produces results, though.

**Comment by jneilliii** [comment]
This should be resolve by the above commit and included with the next release. If you want to test it out you can install by copying/pasting the URL below into Plugin Manager > Get More > ...from URL and clicking Install over your existing installation.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/develop.zip
```
