### ISSUE TITLE
Shelly support

### ISSUE THREAD

**Issue by DaafSamson** [jneilliii/OctoPrint-Tasmota#93]
Hi,

I've used this plugin for a long while and am very happy with it. But. I'm moving to a Shelly smart plug and that is not supported.

The API for the shelly plus is similar to the Tasmota API, simple HTTP requests give access to all data. I know nothing about building Octoprint plugins, but would be willing to collaborate in porting this plugin to a shelly version, or to add shelly support to this one?

Would that be of interest?

**Comment by jneilliii** [comment]
I'm not really looking to add a plugin for a device I don't have personally, but if the shelly api is as similar as you say, I'd be more than happy to assist you in troubleshooting through the changes on your own fork of the plugin.

**Comment by DaafSamson** [comment]
> 
> 
> I'm not really looking to add a plugin for a device I don't have personally, but if the shelly api is as similar as you say, I'd be more than happy to assist you in troubleshooting through the changes on your own fork of the plugin.

That would be most welcome. What would be a good way to communicate? Does GitHub have a private messaging function?

**Comment by jneilliii** [comment]
I'm not aware of any, but I regularly hang out in octoprint discord server ans on the community forum.
