### ISSUE TITLE
Looping of Plugin when Auto Disconnect and Off on Disconnect enabled at the same time

### ISSUE THREAD

**Issue by houseofbugs** [jneilliii/OctoPrint-Tasmota#96]
If you have the auto disconnect option set (tested with 0 second delay) and the Off on Disconnect option set it creates a loop in the plugin that makes the UI unusable. The outlet also will not turn back on since the plugin is telling it to turn off constantly.

**Comment by jneilliii** [comment]
Thanks, I'll have a look at that scenario and see if there's a way to rectify it. I would think that it would just send an off command twice to the relay.

**Comment by jneilliii** [comment]
@houseofbugs do your printers get back-powered by the USB connection from the pi or are you using the blough-r on them?

**Comment by jneilliii** [comment]
I think I have this fixed in my current rc branch. You can test by copying/pasting the URL below into plugin manager > get more > ...from URL and clicking install.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/rc.zip
```

**Comment by FeepingCreature** [comment]
Had the same issue, RC fixed it.

**Comment by houseofbugs** [comment]
RC fixed it for me as well.

**Comment by jneilliii** [comment]
Thanks guys. I will look to release this version official over the weekend.
