### ISSUE TITLE
Auto-Connect causes multiple Handshake attempts, ignoring timeout

### ISSUE THREAD

**Issue by DodgeDeBoulet** [jneilliii/OctoPrint-Tasmota#97]
I have a smartplug that controls the printer power configured through Tasmota to auto-connect after 10 seconds. The connection appears to succeed and the main board starts sending its usual configuration data. However, interspersed periodically during this startup configuration dump are additional handshake attempts. After 3 attempts it stops trying and appears to settle down.

I've verified that this does not happen when the plugin is not configured to auto-start the connection, i.e. when the connection is established manually by clicking the Octoprint "Connect" button, or when Octoprint is configured to connect automatically on server start. Here's a section of the console log from OctoPrint that shows the issue. I've prefixed the connection attempt lines with >>:

```
Changing monitoring state from "Offline" to "Detecting serial connection"
Performing autodetection with 1 port/baudrate candidates: /dev/ttyACM0@512000
Trying port /dev/ttyACM0, baudrate 512000
Connecting to port /dev/ttyACM0, baudrate 512000
>>Handshake attempt #1 with timeout 5.0s
Connected to: Serial<id=0xac1610b0, open=True>(port='/dev/ttyACM0', baudrate=512000, bytesize=8, parity='N', stopbits=1, timeout=5.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Send: N0 M110 N0*125
Recv: //action:notification Ender5++ Ready.
Recv: DIGIPOTS Loading
Recv: DIGIPOTS Loaded
Recv: DIGIPOTS Loading
Recv: DIGIPOTS Loaded
Recv: echo:V82 stored settings retrieved (674 bytes; crc 19026)
Recv: Unified Bed Leveling System v1.01 active
Recv: 
>>Handshake attempt #2 with timeout 5.0s
Recv: Unified Bed Leveling initialized.
Send: N0 M110 N0*125
Recv: 
>>Handshake attempt #3 with timeout 5.0s
Recv: Mesh loaded from slot 0
Recv: Mesh 0 loaded from storage.
Send: N0 M110 N0*125
Recv: //action:prompt_end
Recv: Testing X connection... OK
Recv: Testing Y connection... OK
Recv: Testing Z connection... OK
Recv: Testing Z2 connection... OK
Recv: Testing E connection... OK
Recv: echo:SD card ok
Recv: ok N0 P63 B27
Changing monitoring state from "Detecting serial connection" to "Operational"
Send: N0 M110 N0*125
Recv: ok N0 P63 B29
Recv: ok N0 P63 B30
Send: N1 M115*39
Send: N2 M20*19
Recv: ok N0 P63 B29
```
The handshake attempts aren't even coming close to hitting their 5 second timeouts before another "Handshake attempt" log entry appears.

In the end I am successfully connected, but this is unexpected behavior. If it matters, the version of Marlin is 2.0.7.2, and I'm running an SKR 1.4 Turbo with a TFT35 v3.0 on an Ender 5 Plus. Serial and Octoprint logs attached.
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5433556/octoprint.log)
[serial.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5433558/serial.log)

**Comment by jneilliii** [comment]
Does your printer happen to be back powered by the USB connection from the pi?

**Comment by DodgeDeBoulet** [comment]
No, the SKR 1.4 can be specifically configured via a jumper to be powered
exclusively through the PSU, and mine is. And if it was powered via USB, I
would be able to connect to it from OctoPrint even when the printer was
powered off, right? I definitely can't...

**Comment by jneilliii** [comment]
Ok, perfect. I just wanted to make sure. There have been some weird things happens before when this was the case. Curious, are you using Auto or do you have your port and baudrate saved for your printer's connection? I can't remember if I'm sending the connect command with these defined from octoprint's settings or not. I know I've done that on one of the power plugins.

**Comment by DodgeDeBoulet** [comment]
I have Baud rate set to 512000 and the port set to AUTO. I have Auto-connect on server start enabled as well. I was previously running the PortLister plugin because it seemed to help with ... something. But it also interfered with the Firmware Updater plugin and I've disabled it.

I have two additional baud rates defined; 512000 and 1000000. Any baud rate will actually connect, though; seems to be a feature of an acm-type connection. I tried changing some of the connection timeouts in OctoPrint settings before I discovered that the issue with multiple handshakes only occurs when the Tasmota plugin triggers the connection. I should probably set those back to the defaults, but they don't seem to have had a negative impact.

**Comment by jneilliii** [comment]
ugh, I just had a chance to look at your octoprint.log...you're using OctoDash aren't you? That app floods the log so bad. Can you do me a favor and enable debug logging in the plugin, restart OctoPrint to initialize the plugin's log file and then reproduce the issue. I want to try and get a correlation between what and when the plugin is sending the connect command. It should only send the connect command once per plug that it's configured for.  

I just recently added some additional checks in the disconnect monitoring event in my rc branch to only send disconnect when connected. Probably need to add the same for sending the connection command. Should be a fairly quick fix. I'll try that now and provide you a URL to use to install with and test.

**Comment by jneilliii** [comment]
So I went to add this to the code and it's actually already there. It should only send the connect command if the connection is not already established.

https://github.com/jneilliii/OctoPrint-Tasmota/blob/7a4fbaeebc39309bec281c810d99086e53ed8447/octoprint_tasmota/__init__.py#L323-L327

**Comment by jneilliii** [comment]
I also just realized I never incorporated debug logging in this plugin. It's not my day with this plugin, lol. Quick question, have you tried extending the autoconnect delay to a larger value to make sure your printer has plenty of time to power on prior to attempting the connection?

**Comment by DodgeDeBoulet** [comment]
Well, first things first ... not using OctoDash (as far as I know), but if my logs are polluted, I'll see if I can figure out what's doing it.

I enabled debug logging for the plugin, but it's a zero byte file. Given that you haven't implemented debug logging in this plugin, I guess that's unsurprising 😁

Connection timeout is set at the default of 10 seconds, but the connection succeeds and the printer starts sending data immediately:

```
Connecting to port /dev/ttyACM0, baudrate 512000
Handshake attempt #1 with timeout 5.0s
Connected to: Serial<id=0xa84e66f0, open=True>(port='/dev/ttyACM0', baudrate=512000, bytesize=8, parity='N', stopbits=1, timeout=5.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Send: N0 M110 N0*125
Recv: //action:notification Ender5++ Ready.
Recv: DIGIPOTS Loading
Recv: DIGIPOTS Loaded
Recv: DIGIPOTS Loading
Recv: DIGIPOTS Loaded
```
Everything you see above happens within the first second following the 10 second connect delay. By the time 5 seconds have passed, 3 handshake attempts have occurred.

##THAT SAID ...
Changing the connect delay to **12** seconds seems to have eliminated the multiple handshake attempts.

**Comment by jneilliii** [comment]
Yeah, that's what I'm wondering is if there is some weird timing condition during initial connection that if it doesn't succeed right away it retries to connect. Definitely unexpected, but hard to say for sure without looking at OctoPrint's core code to see how it handles the connection. At least by extending the delay you are able to resolve the retries. I'll let this ticket stick here until the stalebot closes just in case the issue does resurface with the extended connection delay. Just let me know if it does.
