### ISSUE TITLE
Tasmota plugin blocks events being sent to other plugins

### ISSUE THREAD

**Issue by Cylindric** [jneilliii/OctoPrint-Tasmota#98]
I've been using the Octorant plugin for a while now, and it utilises standard events to trigger stuff on print completion.
When I enable the Tasmota plugin, it seems to block other events from reaching other plugins, specifically in my case the `PrintDone` event, although others may be affected too.
Is there something that might be blocking `on_event` from returning?

**Comment by Cylindric** [comment]
Gah. Typical. I enable all the logging, re-enable the plugin to capture some data, and now it's working.
Not sure what the problem was now, but a disable/restart/enable/restart cycle _seems_ to have worked for now...

**Comment by jneilliii** [comment]
There's nothing in the plugin that should block events from getting passed on to other events. All those callbacks are run from the core OctoPrint side.

**Comment by Cylindric** [comment]
That's not entirely accurate, it's quite possible for plugins to block the event queue. As per the `on_event` documentation:

> Please note that until your plugin returns from that method, further event processing within OctoPrint will block

Either way, uninstalling the Tasmota plugin and reinstalling it seems to have fixed whatever was wrong with it.
